# Generated by Django 2.2.13 on 2020-06-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataoceanuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataoceanuser',
            name='organization',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='dataoceanuser',
            name='position',
            field=models.CharField(default='', max_length=150),
        ),
    ]
