# Generated by Django 2.2.13 on 2020-06-18 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200618_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataoceanuser',
            name='date_of_birth',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='dataoceanuser',
            name='organization',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='dataoceanuser',
            name='position',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
