# Generated by Django 3.0.7 on 2020-06-25 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200618_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateUserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('first_name', models.CharField(max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(max_length=150, verbose_name='last name')),
                ('confirm_code', models.CharField(blank=True, default='', max_length=256, verbose_name='confirm code')),
                ('expire_at', models.DateTimeField(blank=True, null=True, verbose_name='expire at')),
            ],
        ),
    ]
