# Generated by Django 3.0.7 on 2020-06-25 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_candidateusermodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateusermodel',
            name='confirm_code',
        ),
    ]
