# Generated by Django 3.0.7 on 2021-01-25 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateusermodel',
            name='language',
            field=models.CharField(blank=True, choices=[('uk', 'Ukrainian'), ('en', 'English')], default='uk', max_length=2, verbose_name='language'),
        ),
    ]
