# Generated by Django 3.0.7 on 2021-02-08 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataoceanuser',
            name='can_admin_payment_system',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='dataoceanuser',
            name='can_admin_registers',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='dataoceanuser',
            name='can_view_users',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
