# Generated by Django 3.0.7 on 2021-02-11 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210208_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, editable=False, null=True),
        ),
    ]
