# Generated by Django 3.0.7 on 2021-02-17 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20210215_1042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataoceanuser',
            old_name='can_admin_registers',
            new_name='datasets_admin',
        ),
        migrations.RenameField(
            model_name='dataoceanuser',
            old_name='can_admin_payment_system',
            new_name='payment_system_admin',
        ),
        migrations.RenameField(
            model_name='dataoceanuser',
            old_name='can_view_users',
            new_name='users_viewer',
        ),
    ]
