# Generated by Django 3.0.7 on 2021-03-26 08:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20210305_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataoceanuser',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='dataoceanuser',
            name='edrpou',
            field=models.CharField(blank=True, default='', max_length=8, validators=[django.core.validators.RegexValidator(message='This field must contain 8 characters, only numbers', regex='^\\d{8}$')]),
        ),
        migrations.AddField(
            model_name='dataoceanuser',
            name='iban',
            field=models.CharField(blank=True, default='', max_length=29, validators=[django.core.validators.RegexValidator(message='Wrong IBAN format', regex='^[A-Za-z]{2}\\d{27}$')]),
        ),
        migrations.AddField(
            model_name='dataoceanuser',
            name='person_status',
            field=models.CharField(blank=True, choices=[('individual', 'Individual'), ('individual_entrepreneur', 'Individual entrepreneur'), ('legal_entity', 'Legal entity')], default='individual', max_length=23),
        ),
        migrations.AddField(
            model_name='dataoceanuser',
            name='registration_address',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
