# Generated by Django 3.1.7 on 2021-04-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20210330_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateusermodel',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='dataoceanuser',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
    ]
