# Generated by Django 3.1.7 on 2021-04-07 09:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20210330_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateusermodel',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='dataoceanuser',
            name='first_name',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(message="Only alphanumeric characters, digits, and '-. are allowed", regex="^[a-zA-Zа-яА-Я0-9 'іїёєґЄЇҐІЭ.`-]*$"), django.core.validators.RegexValidator(inverse_match=True, message='No more than 2 identical symbols in a row are allowed', regex='(.)\\1{2,}')]),
        ),
    ]
