# Generated by Django 3.1.7 on 2021-04-13 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20210407_0900'),
        ('users', '0018_auto_20210409_1357'),
    ]

    operations = [
    ]
