# Generated by Django 3.1.8 on 2021-04-15 08:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_merge_20210413_0752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataoceanuser',
            name='edrpou',
        ),
        migrations.RemoveField(
            model_name='dataoceanuser',
            name='registration_address',
        ),
        migrations.AddField(
            model_name='dataoceanuser',
            name='company_address',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Company registration address'),
        ),
        migrations.AddField(
            model_name='dataoceanuser',
            name='identification_code',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='EDRPOU/ITN'),
        ),
        migrations.AddField(
            model_name='dataoceanuser',
            name='mfo',
            field=models.CharField(blank=True, default='', max_length=6, validators=[django.core.validators.RegexValidator(message='Wrong MFO format', regex='^\\d{6}$')], verbose_name='MFO'),
        ),
        migrations.AlterField(
            model_name='dataoceanuser',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Company name'),
        ),
        migrations.AlterField(
            model_name='dataoceanuser',
            name='iban',
            field=models.CharField(blank=True, default='', max_length=29, validators=[django.core.validators.RegexValidator(message='Wrong IBAN format', regex='^[A-Za-z]{2}\\d{27}$')], verbose_name='IBAN'),
        ),
    ]
