# Generated by Django 3.0.7 on 2020-10-22 13:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectsubscription',
            options={'verbose_name': 'relation between the project and its subscriptions'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='disabled',
        ),
        migrations.AddField(
            model_name='project',
            name='disabled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='subscriptions',
            field=models.ManyToManyField(related_name='subscription_projects', through='payment_system.ProjectSubscription', to='payment_system.Subscription'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='custom',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='info',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='paid_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='token',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='users',
            field=models.ManyToManyField(related_name='user_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectsubscription',
            name='expiring_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='duration',
            field=models.SmallIntegerField(blank=True, default=30),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='grace_period',
            field=models.SmallIntegerField(blank=True, default=30),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='price',
            field=models.SmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='requests_limit',
            field=models.IntegerField(verbose_name='limit for API requests from the project'),
        ),
    ]
