# Generated by Django 3.0.7 on 2020-10-23 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment_system', '0002_auto_20201022_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='subscriptions',
            field=models.ManyToManyField(related_name='projects', through='payment_system.ProjectSubscription', to='payment_system.Subscription'),
        ),
        migrations.AlterField(
            model_name='project',
            name='users',
            field=models.ManyToManyField(related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectsubscription',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_subscriptions', to='payment_system.Project'),
        ),
        migrations.AlterField(
            model_name='projectsubscription',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_subscriptions', to='payment_system.Subscription'),
        ),
    ]
