# Generated by Django 3.0.7 on 2020-11-09 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_system', '0006_auto_20201106_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsubscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('past', 'Past'), ('future', 'Future')], max_length=10),
        ),
    ]
