# Generated by Django 3.0.7 on 2020-11-18 14:58

from django.db import migrations, models
import django.db.models.deletion


choices_sql = """
DELETE FROM payment_system_userproject
WHERE status='invited';

UPDATE payment_system_userproject
SET role='owner'
WHERE role='initiator';

UPDATE payment_system_userproject
SET role='member'
WHERE role='participant';
"""

reverse_choices_sql = """
UPDATE payment_system_userproject
SET role='initiator'
WHERE role='owner';

UPDATE payment_system_userproject
SET role='participant'
WHERE role='member';
"""


class Migration(migrations.Migration):

    dependencies = [
        ('payment_system', '0010_userproject_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproject',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('member', 'Member')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userproject',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('deactivated', 'Deactivated')], max_length=11),
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='payment_system.Project')),
            ],
            options={
                'unique_together': {('email', 'project')},
            },
        ),
        migrations.RunSQL(choices_sql, reverse_sql=reverse_choices_sql)
    ]
