# Generated by Django 3.0.7 on 2020-11-24 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_system', '0011_auto_20201118_1458'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['price']},
        ),
        migrations.AlterField(
            model_name='subscription',
            name='custom',
            field=models.BooleanField(blank=True, default=False, help_text='Custom subscription not shown to users'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='duration',
            field=models.SmallIntegerField(default=30, help_text='days'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='grace_period',
            field=models.SmallIntegerField(default=10, help_text='days'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='price',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='requests_limit',
            field=models.IntegerField(help_text='Limit for API requests from the project'),
        ),
    ]
