# Generated by Django 3.0.7 on 2020-11-27 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment_system', '0012_auto_20201124_1915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='info',
            new_name='note',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='project',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='subscription',
        ),
        migrations.RunSQL('DELETE FROM payment_system_invoice;', reverse_sql=migrations.RunSQL.noop),
        migrations.AddField(
            model_name='invoice',
            name='project_subscription',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='payment_system.ProjectSubscription'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectsubscription',
            name='is_grace_period',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='paid_at',
            field=models.DateField(blank=True, help_text='This operation is irreversible, you cannot cancel the payment of the subscription for the project.', null=True),
        ),
    ]
