# Generated by Django 3.0.7 on 2020-11-29 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_system', '0014_auto_20201129_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='disable_grace_period_block',
            field=models.BooleanField(blank=True, default=False, help_text='If set to True, then the user will be allowed to use "grace period" again, the opportunity to pay will be lost'),
        ),
    ]
