# Generated by Django 3.0.7 on 2020-12-01 18:02

from django.db import migrations, models


def set_requests_left(apps, schema):
    ProjectSubscription = apps.get_model('payment_system', 'ProjectSubscription')

    for p2s in ProjectSubscription.objects.all():
        p2s.requests_left = p2s.subscription.requests_limit
        p2s.save()


class Migration(migrations.Migration):

    dependencies = [
        ('payment_system', '0015_invoice_disable_grace_period_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsubscription',
            name='requests_left',
            field=models.IntegerField(default=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectsubscription',
            name='requests_used',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='token',
            field=models.CharField(db_index=True, max_length=40, unique=True),
        ),
        migrations.RunPython(
            code=set_requests_left,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='projectsubscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('past', 'Past'), ('future', 'Future')],
                                   db_index=True, max_length=10),
        ),
    ]
