# Generated by Django 3.0.7 on 2020-12-03 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_system', '0016_auto_20201201_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsubscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('past', 'Past'), ('future', 'Future')], db_index=True, max_length=10),
        ),
    ]
