# Generated by Django 3.0.7 on 2020-12-03 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment_system', '0017_auto_20201203_2113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectsubscription',
            options={'ordering': ['-created_at'], 'verbose_name': 'relation between the project and its subscriptions'},
        ),
        migrations.AlterField(
            model_name='invoice',
            name='project_subscription',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='payment_system.ProjectSubscription'),
        ),
    ]
