# Generated by Django 3.0.7 on 2020-12-04 19:04

from django.db import migrations, models
import django.utils.timezone
from django.utils import timezone


def set_start_date(apps, schema):
    ProjectSubscription = apps.get_model('payment_system', 'ProjectSubscription')

    for p2s in ProjectSubscription.objects.all():
        if p2s.is_grace_period:
            p2s.start_date = p2s.expiring_date - timezone.timedelta(days=p2s.subscription.grace_period)
        else:
            p2s.start_date = p2s.expiring_date - timezone.timedelta(days=p2s.subscription.duration)
        p2s.save()


class Migration(migrations.Migration):

    dependencies = [
        ('payment_system', '0018_auto_20201203_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsubscription',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='projectsubscription',
            name='expiring_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.RunPython(
            code=set_start_date,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='projectsubscription',
            name='expiring_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='projectsubscription',
            name='start_date',
            field=models.DateField(),
        ),
    ]
