# Generated by Django 3.0.7 on 2020-12-07 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def set_owners(apps, schema):
    Project = apps.get_model('payment_system', 'Project')
    for project in Project.objects.all():
        owner = project.users.filter(user_projects__role='owner').first()
        if not owner:
            project.delete()
        else:
            project.owner = owner
            project.save()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment_system', '0020_project_owner'),
    ]

    operations = [
        migrations.RunPython(
            code=set_owners,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
