# Generated by Django 3.0.7 on 2020-12-07 20:56

from django.db import migrations, models


def set_durations(apps, schema):
    ProjectSubscription = apps.get_model('payment_system', 'ProjectSubscription')
    for p2s in ProjectSubscription.objects.all():
        p2s.duration = p2s.subscription.duration
        p2s.grace_period = p2s.subscription.grace_period
        p2s.save()


class Migration(migrations.Migration):

    dependencies = [
        ('payment_system', '0022_auto_20201207_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsubscription',
            name='duration',
            field=models.SmallIntegerField(default=30, help_text='days'),
        ),
        migrations.AddField(
            model_name='projectsubscription',
            name='grace_period',
            field=models.SmallIntegerField(default=10, help_text='days'),
        ),
        migrations.RunPython(
            code=set_durations,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='projectsubscription',
            name='duration',
            field=models.SmallIntegerField(help_text='days'),
        ),
        migrations.AlterField(
            model_name='projectsubscription',
            name='grace_period',
            field=models.SmallIntegerField(help_text='days'),
        ),
    ]
