# Generated by Django 3.0.7 on 2020-12-11 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment_system', '0023_auto_20201207_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='project_subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='payment_system.ProjectSubscription'),
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='disable_grace_period_block',
            new_name='grace_period_block',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='grace_period_block',
            field=models.BooleanField(blank=True, default=True,
                                      help_text='If set to False, then the user will be allowed to use "grace period" again, the opportunity to pay will be lost'),
        ),
    ]
