# Generated by Django 3.0.7 on 2020-12-11 15:11

from django.db import migrations, models


def set_grace_period_block(apps, schema):
    Invoice = apps.get_model('payment_system', 'Invoice')
    for invoice in Invoice.objects.all():
        invoice.grace_period_block = not bool(invoice.paid_at)
        invoice.save()


class Migration(migrations.Migration):

    dependencies = [
        ('payment_system', '0024_auto_20201211_1454'),
    ]

    operations = [
        migrations.RunPython(
            code=set_grace_period_block,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
