# Generated by Django 3.0.7 on 2021-02-02 14:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment_system', '0028_auto_20210119_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='token',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4),
        ),
    ]
