# Generated by Django 3.0.7 on 2021-02-11 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_system', '0029_invoice_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproject',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('deactivated', 'Deactivated'), ('deleted', 'Deleted')], max_length=11),
        ),
    ]
