# Generated by Django 3.0.7 on 2021-02-15 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment_system', '0032_auto_20210211_0935'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customsubscriptionrequest',
            options={'ordering': ['is_processed', '-created_at'], 'verbose_name': 'invitation', 'verbose_name_plural': 'invitations'},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-created_at'], 'verbose_name': 'invoice', 'verbose_name_plural': 'invoices'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'project', 'verbose_name_plural': 'projects'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['price'], 'verbose_name': 'subscription', 'verbose_name_plural': 'subscriptions'},
        ),
        migrations.AlterField(
            model_name='invitation',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='payment_system.Project', verbose_name='project'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='end_date',
            field=models.DateField(verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='grace_period_block',
            field=models.BooleanField(blank=True, default=True, help_text='If set to False, then the user will be allowed to use "grace period" again, the opportunity to pay will be lost', verbose_name='is grace period blocked'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='is_custom_subscription',
            field=models.BooleanField(verbose_name='is subscription custom'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='paid_at',
            field=models.DateField(blank=True, help_text='This operation is irreversible, you cannot cancel the payment of the subscription for the project.', null=True, verbose_name='subscription'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='price',
            field=models.IntegerField(verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='project_name',
            field=models.CharField(max_length=100, verbose_name='project`s name'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='project_subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='payment_system.ProjectSubscription', verbose_name='project`s subscription'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='requests_limit',
            field=models.IntegerField(verbose_name='requests limit'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='start_date',
            field=models.DateField(verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='subscription_name',
            field=models.CharField(max_length=200, verbose_name='subscription`s name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='disabled_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='disabled_at'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
        migrations.AlterField(
            model_name='project',
            name='subscriptions',
            field=models.ManyToManyField(related_name='projects', through='payment_system.ProjectSubscription', to='payment_system.Subscription', verbose_name='subscriptions'),
        ),
        migrations.AlterField(
            model_name='project',
            name='users',
            field=models.ManyToManyField(related_name='projects', through='payment_system.UserProject', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='duration',
            field=models.SmallIntegerField(default=30, help_text='days', verbose_name='duration'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='grace_period',
            field=models.SmallIntegerField(default=10, help_text='days', verbose_name='grace_period'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='is_custom',
            field=models.BooleanField(blank=True, default=False, help_text='Custom subscription not shown to users', verbose_name='is_custom'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='is_default',
            field=models.BooleanField(blank=True, default=False, verbose_name='is_default'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='platform_requests_limit',
            field=models.IntegerField(help_text='Limit for API requests from the project via platform', verbose_name='platform_requests_limit'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='price',
            field=models.SmallIntegerField(default=0, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='requests_limit',
            field=models.IntegerField(help_text='Limit for API requests from the project', verbose_name='requests limit'),
        ),
    ]
