# Generated by Django 3.0.7 on 2021-02-16 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_system', '0033_auto_20210215_1042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customsubscriptionrequest',
            options={'ordering': ['is_processed', '-created_at']},
        ),
    ]
