# Generated by Django 3.0.7 on 2021-02-16 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_system', '0034_auto_20210216_0923'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customsubscriptionrequest',
            options={'ordering': ['is_processed', '-created_at'], 'verbose_name': 'custom subscription request', 'verbose_name_plural': 'custom subscription requests'},
        ),
        migrations.AlterModelOptions(
            name='invitation',
            options={'verbose_name': 'invitation', 'verbose_name_plural': 'invitations'},
        ),
    ]
