# Generated by Django 3.0.7 on 2021-02-24 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_system', '0035_auto_20210216_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='paid_at',
            field=models.DateField(blank=True, help_text='This operation is irreversible, you cannot cancel the payment of the subscription for the project.', null=True, verbose_name='paid at'),
        ),
    ]
