# Generated by Django 3.0.7 on 2021-03-05 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_system', '0036_auto_20210304_1001'),
        ('payment_system', '0036_auto_20210224_1515'),
    ]

    operations = [
    ]
