# Generated by Django 3.0.7 on 2021-03-24 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_system', '0041_auto_20210312_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsubscription',
            name='pep_checks_count_per_minute',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectsubscription',
            name='pep_checks_minute',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscription',
            name='pep_checks',
            field=models.BooleanField(blank=True, default=False, help_text='Allow to use api/pep/check/ endpoint'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='pep_checks_per_minute',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='price'),
        ),
    ]
