# Generated by Django 3.0.7 on 2021-03-31 10:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_system', '0041_auto_20210312_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceDailyReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(verbose_name='created_at')),
                ('should_complete_count', models.SmallIntegerField(default=0, verbose_name='should complete counter')),
                ('was_complete_count', models.SmallIntegerField(default=0, verbose_name='was complete counter')),
                ('was_overdue_count', models.SmallIntegerField(default=0, verbose_name='was overdue counter')),
                ('was_overdue_grace_period_count', models.SmallIntegerField(default=0, verbose_name='was overdue grace period')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_registration_date',
            field=models.DateField(default=datetime.date(2021, 3, 31), verbose_name='payment registration date'),
        ),
    ]
