# Generated by Django 3.1.7 on 2021-03-26 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment_system', '0042_auto_20210324_0818'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['position', 'price'], 'verbose_name': 'subscription', 'verbose_name_plural': 'subscriptions'},
        ),
        migrations.AddField(
            model_name='subscription',
            name='pep_db_downloading',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='position',
            field=models.PositiveSmallIntegerField(default=1, help_text='Position of subscription on frontend'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='yearly_subscription',
            field=models.ForeignKey(blank=True, default=None, help_text='Related yearly subscription. Example: Business -> Business +', null=True, on_delete=django.db.models.deletion.PROTECT, to='payment_system.subscription'),
        ),
    ]
