# Generated by Django 3.1.7 on 2021-04-07 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_system', '0044_auto_20210330_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='grace_period_block',
            field=models.BooleanField(blank=True, default=True, help_text='If set to False, then the user will be allowed to use "grace period" again', verbose_name='is grace period blocked'),
        ),
    ]
