# Generated by Django 3.1.8 on 2021-04-18 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_system', '0046_auto_20210408_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='company_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='company_name',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='iban',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='identification_code',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='mfo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='person_status',
            field=models.TextField(blank=True),
        ),
    ]
