# Generated by Django 3.1.8 on 2021-04-26 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_system', '0049_projectsubscription_renewal_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsubscription',
            name='renewal_date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
