# Generated by Django 2.0.9 on 2020-03-31 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfop',
            name='kved',
            field=models.IntegerField(default=0),
        ),
    ]
