# Generated by Django 2.0.9 on 2020-03-31 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rfop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('adress', models.CharField(max_length=100)),
                ('kved', models.IntegerField(default=0)),
                ('state', models.CharField(max_length=30)),
            ],
        ),
    ]
