# Generated by Django 2.0.9 on 2020-04-13 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratu', '0002_auto_20200413_1438'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stateruo',
            new_name='State',
        ),
    ]
