# Generated by Django 2.0.9 on 2020-03-31 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratu', '0002_rfop_kved'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rfop',
        ),
    ]
