# Generated by Django 2.0.9 on 2020-03-31 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratu', '0002_rfop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rfop',
            old_name='adress',
            new_name='address',
        ),
    ]
