# Generated by Django 2.0.9 on 2020-04-13 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ratu', '0003_auto_20200413_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfop',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ratu.State'),
        ),
    ]
