# Generated by Django 2.0.9 on 2020-03-31 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratu', '0003_auto_20200331_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfop',
            name='kved',
            field=models.CharField(max_length=100),
        ),
    ]
