# Generated by Django 2.0.9 on 2020-03-31 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ratu', '0008_auto_20200331_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True)),
                ('short_name', models.CharField(max_length=100, null=True)),
                ('edrpou', models.CharField(max_length=8, null=True)),
                ('address', models.CharField(max_length=300, null=True)),
                ('boss', models.CharField(max_length=100, null=True)),
                ('kved', models.CharField(max_length=250, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Founders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('founder', models.CharField(max_length=300, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ratu.Company')),
            ],
        ),
    ]
