# Generated by Django 2.0.9 on 2020-03-31 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratu', '0009_company_founders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='founders',
            name='company',
            field=models.IntegerField(),
        ),
    ]
