# Generated by Django 2.0.9 on 2020-03-31 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratu', '0011_auto_20200331_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='founders',
            name='founder',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
