# Generated by Django 2.0.9 on 2020-03-31 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratu', '0012_auto_20200331_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='founders',
            name='founder',
            field=models.CharField(max_length=800, null=True),
        ),
    ]
