# Generated by Django 2.0.9 on 2020-03-31 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratu', '0014_auto_20200331_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='boss',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='edrpou',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='kved',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='short_name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='state',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='founders',
            name='founder',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
