# Generated by Django 2.0.9 on 2020-04-01 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratu', '0015_auto_20200331_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='founders',
            name='founder',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
