# Generated by Django 2.0.9 on 2020-04-02 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ratu', '0016_auto_20200401_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='founders',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ratu.Company'),
        ),
        migrations.AlterField(
            model_name='founders',
            name='founder',
            field=models.TextField(null=True),
        ),
    ]
