# Generated by Django 2.0.9 on 2020-04-02 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratu', '0017_auto_20200402_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='founders',
            name='company',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Founders',
        ),
    ]
