# Generated by Django 2.0.9 on 2020-04-02 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ratu', '0018_auto_20200402_2012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, null=True)),
                ('short_name', models.CharField(max_length=500, null=True)),
                ('edrpou', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=500, null=True)),
                ('boss', models.CharField(max_length=250, null=True)),
                ('kved', models.CharField(max_length=500, null=True)),
                ('state', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Founders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('founder', models.TextField(null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ratu.Company')),
            ],
        ),
    ]
