# Generated by Django 2.0.9 on 2020-04-03 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratu', '0019_company_founders'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rfop',
        ),
    ]
