# Generated by Django 2.0.9 on 2020-04-03 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratu', '0021_auto_20200403_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='founders',
            name='company',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Founders',
        ),
    ]
