# Generated by Django 2.0.9 on 2020-04-06 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratu', '0023_auto_20200403_1557'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='State_Rfop',
            new_name='Staterfop',
        ),
        migrations.RenameModel(
            old_name='State_Ruo',
            new_name='Stateruo',
        ),
    ]
