# Generated by Django 2.0.9 on 2020-04-06 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratu', '0026_auto_20200406_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ruo',
            name='kved',
        ),
        migrations.DeleteModel(
            name='Kved',
        ),
    ]
