# Generated by Django 2.0.9 on 2020-04-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratu', '0027_auto_20200406_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, null=True, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='founders',
            name='company',
        ),
        migrations.RemoveField(
            model_name='ruo',
            name='state',
        ),
        migrations.DeleteModel(
            name='Founders',
        ),
        migrations.DeleteModel(
            name='Ruo',
        ),
    ]
