# Generated by Django 2.0.9 on 2020-04-06 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ratu', '0028_auto_20200406_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='Founders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('founder', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ruo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, null=True)),
                ('short_name', models.CharField(max_length=500, null=True)),
                ('edrpou', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=500, null=True)),
                ('boss', models.CharField(max_length=250, null=True)),
                ('kved', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ratu.Kved')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ratu.Stateruo')),
            ],
        ),
        migrations.AddField(
            model_name='founders',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ratu.Ruo'),
        ),
    ]
