# Generated by Django 2.0.9 on 2020-04-06 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratu', '0029_auto_20200406_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rfop',
            name='state',
        ),
        migrations.DeleteModel(
            name='Rfop',
        ),
        migrations.DeleteModel(
            name='Staterfop',
        ),
    ]
