# Generated by Django 2.0.9 on 2020-04-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratu', '0006_auto_20200416_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='koatuu',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='citydistrict',
            name='koatuu',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='district',
            name='koatuu',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='region',
            name='koatuu',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
