# Generated by Django 2.0.9 on 2020-04-21 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratu', '0007_auto_20200417_1433'),
        ('ratu', '0032_auto_20200417_1531'),
    ]

    operations = [
    ]
