# Generated by Django 2.0.9 on 2020-04-21 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ratu', '0033_merge_20200421_0929'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kzed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True)),
                ('name', models.CharField(max_length=1000)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ratu.Division')),
            ],
        ),
        migrations.AlterField(
            model_name='group',
            name='code',
            field=models.CharField(max_length=5, unique=True),
        ),
        migrations.AddField(
            model_name='kzed',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ratu.Group'),
        ),
        migrations.AddField(
            model_name='kzed',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ratu.Section'),
        ),
    ]
