# Generated by Django 2.0.9 on 2020-04-22 12:25

from django.db import migrations
from django.apps import apps
from ratu.models.kzed_models import Section, Division, Group, Kzed


class Migration(migrations.Migration):

    def add_kved_not_found (apps, schema_editor):
        Section = apps.get_model('ratu', 'Section')
        section = Section()
        section.code = "EMP"
        section.name = "EMPTY"
        section.save()

        Division = apps.get_model('ratu', 'Division')
        division = Division()
        division.section = section
        division.code = "EMP"
        division.name = "EMPTY"
        division.save()

        Group = apps.get_model('ratu', 'Group')
        group = Group() 
        group.section = section
        group.division = division
        group.code = "EMP"
        group.name = "EMPTY"
        group.save()

        Kzed = apps.get_model('ratu', 'Kzed')
        kzed = Kzed() 
        kzed.section = section
        kzed.division = division
        kzed.group = group
        kzed.code = "EMP"
        kzed.name = "EMPTY"
        kzed.save()

    dependencies = [
        ('ratu', '0035_auto_20200422_1059'),
    ]

    operations = [
        migrations.RunPython(add_kved_not_found),
    ]
