# Generated by Django 2.0.9 on 2020-04-28 06:53

from django.db import migrations, models
import django.db.models.deletion
from django.apps import apps
from ratu.models.kved_models import Section, Division, Group, Kved


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# ratu.migrations.0036_auto_20200422_1225

class Migration(migrations.Migration):

    replaces = [('ratu', '0036_auto_20200422_1225'), ('ratu', '0037_auto_20200423_1237'), ('ratu', '0038_auto_20200423_1406'), ('ratu', '0039_auto_20200424_0814'), ('ratu', '0040_auto_20200424_1005')]

    dependencies = [
        ('ratu', '0035_auto_20200422_1059'),
    ]

    def add_kved_not_found (apps, schema_editor):
        Section = apps.get_model('ratu', 'Section')
        section = Section()
        section.code = "EMP"
        section.name = "EMPTY"
        section.save()

        Division = apps.get_model('ratu', 'Division')
        division = Division()
        division.section = section
        division.code = "EMP"
        division.name = "EMPTY"
        division.save()

        Group = apps.get_model('ratu', 'Group')
        group = Group() 
        group.section = section
        group.division = division
        group.code = "EMP"
        group.name = "EMPTY"
        group.save()

        Kved = apps.get_model('ratu', 'Kved')
        kved = Kved() 
        kved.section = section
        kved.division = division
        kved.group = group
        kved.code = "EMP"
        kved.name = "EMPTY"
        kved.save()

    operations = [
        migrations.RunPython(add_kved_not_found),
        migrations.AddField(
            model_name='kved',
            name='code',
            field=models.CharField(default=1, max_length=5, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kved',
            name='division',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ratu.Division'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kved',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ratu.Group'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kved',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ratu.Section'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kved',
            name='name',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ruo',
            name='kved',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ratu.Kved'),
        ),
        migrations.DeleteModel(
            name='Kzed',
        ),
        migrations.AlterField(
            model_name='division',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='kved',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
