# Generated by Django 2.0.9 on 2020-04-23 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ratu', '0036_auto_20200422_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='founders',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='founders', to='ratu.Ruo'),
        ),
    ]
