# Generated by Django 2.0.9 on 2020-04-23 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ratu', '0036_auto_20200422_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kzed',
            name='name',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='ruo',
            name='kved',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ratu.Kzed'),
        ),
    ]
