# Generated by Django 2.0.9 on 2020-04-23 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratu', '0037_auto_20200423_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kzed',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
