# Generated by Django 2.0.9 on 2020-04-24 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ratu', '0038_auto_20200423_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kzed',
            name='division',
        ),
        migrations.RemoveField(
            model_name='kzed',
            name='group',
        ),
        migrations.RemoveField(
            model_name='kzed',
            name='section',
        ),
        migrations.AddField(
            model_name='kved',
            name='code',
            field=models.CharField(default=1, max_length=5, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kved',
            name='division',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ratu.Division'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kved',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ratu.Group'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kved',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ratu.Section'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kved',
            name='name',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ruo',
            name='kved',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ratu.Kved'),
        ),
        migrations.DeleteModel(
            name='Kzed',
        ),
    ]
