# Generated by Django 2.0.9 on 2020-04-24 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratu', '0039_auto_20200424_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='kved',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
