# Generated by Django 2.0.9 on 2020-05-20 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_ocean', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business_register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalfop',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalfop',
            name='status',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='data_ocean.Status'),
        ),
        migrations.AddField(
            model_name='historicalcompanydetail',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='business_register.Company'),
        ),
        migrations.AddField(
            model_name='historicalcompanydetail',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcompany',
            name='authority',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='data_ocean.Authority'),
        ),
        migrations.AddField(
            model_name='historicalcompany',
            name='bylaw',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='business_register.Bylaw'),
        ),
        migrations.AddField(
            model_name='historicalcompany',
            name='company_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='business_register.CompanyType'),
        ),
        migrations.AddField(
            model_name='historicalcompany',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcompany',
            name='parent',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='business_register.Company'),
        ),
        migrations.AddField(
            model_name='historicalcompany',
            name='state',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='business_register.State'),
        ),
        migrations.AddField(
            model_name='group',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_register.Division'),
        ),
        migrations.AddField(
            model_name='group',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_register.Section'),
        ),
        migrations.AddField(
            model_name='founders',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='founders', to='business_register.Ruo'),
        ),
        migrations.AddField(
            model_name='founderfull',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_register.Company'),
        ),
        migrations.AddField(
            model_name='foptokved',
            name='fop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kveds', to='business_register.Fop'),
        ),
        migrations.AddField(
            model_name='foptokved',
            name='kved',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_register.Kved'),
        ),
        migrations.AddField(
            model_name='fop',
            name='authority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_ocean.Authority'),
        ),
        migrations.AddField(
            model_name='fop',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_ocean.Status'),
        ),
        migrations.AddField(
            model_name='exchangedatafop',
            name='authority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_ocean.Authority'),
        ),
        migrations.AddField(
            model_name='exchangedatafop',
            name='fop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_data', to='business_register.Fop'),
        ),
        migrations.AddField(
            model_name='exchangedatafop',
            name='taxpayer_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_ocean.TaxpayerType'),
        ),
        migrations.AddField(
            model_name='exchangedatacompany',
            name='authority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_ocean.Authority'),
        ),
        migrations.AddField(
            model_name='exchangedatacompany',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_register.Company'),
        ),
        migrations.AddField(
            model_name='exchangedatacompany',
            name='taxpayer_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_ocean.TaxpayerType'),
        ),
        migrations.AddField(
            model_name='division',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_register.Section'),
        ),
        migrations.AddField(
            model_name='companytopredecessor',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_register.Company'),
        ),
        migrations.AddField(
            model_name='companytopredecessor',
            name='predecessor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_register.Predecessor'),
        ),
        migrations.AddField(
            model_name='companytokved',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_register.Company'),
        ),
        migrations.AddField(
            model_name='companytokved',
            name='kved',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_register.Kved'),
        ),
        migrations.AddField(
            model_name='companydetail',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_register.Company'),
        ),
        migrations.AddField(
            model_name='company',
            name='authority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_ocean.Authority'),
        ),
        migrations.AddField(
            model_name='company',
            name='bylaw',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_register.Bylaw'),
        ),
        migrations.AddField(
            model_name='company',
            name='company_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_register.CompanyType'),
        ),
        migrations.AddField(
            model_name='company',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='business_register.Company'),
        ),
        migrations.AddField(
            model_name='company',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_register.State'),
        ),
        migrations.AddField(
            model_name='bancruptcyreadjustment',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_register.Company'),
        ),
        migrations.AddField(
            model_name='assignee',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_register.Company'),
        ),
    ]
