# Generated by Django 2.0.9 on 2020-05-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_register', '0002_auto_20200520_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='fop',
            name='hash_code',
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalfop',
            name='hash_code',
            field=models.IntegerField(),
            preserve_default=False,
        ),
    ]
