# Generated by Django 2.0.9 on 2020-05-27 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_register', '0004_auto_20200527_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fop',
            name='hash_code',
            field=models.CharField(max_length=700),
        ),
        migrations.AlterField(
            model_name='historicalfop',
            name='hash_code',
            field=models.CharField(max_length=700),
        ),
    ]
