# Generated by Django 2.0.9 on 2020-05-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_register', '0005_auto_20200527_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fop',
            name='hash_code',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalfop',
            name='hash_code',
            field=models.IntegerField(max_length=10),
        ),
    ]
