# Generated by Django 2.0.9 on 2020-05-28 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business_register', '0006_auto_20200527_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangedatafop',
            name='taxpayer_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_ocean.TaxpayerType'),
        ),
    ]
