# Generated by Django 2.0.9 on 2020-05-28 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_register', '0007_auto_20200528_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fop',
            name='hash_code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='historicalfop',
            name='hash_code',
            field=models.IntegerField(),
        ),
    ]
