# Generated by Django 2.2 on 2020-06-05 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_ocean', '0002_register'),
        ('business_register', '0008_auto_20200528_0707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='state',
        ),
        migrations.RemoveField(
            model_name='historicalcompany',
            name='state',
        ),
        migrations.AddField(
            model_name='company',
            name='hash_code',
            field=models.CharField(default='1', max_length=510),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='status',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='data_ocean.Status'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='founderfull',
            name='hash_code',
            field=models.CharField(default='1', max_length=510),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcompany',
            name='hash_code',
            field=models.CharField(default='1', max_length=510),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcompany',
            name='status',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='data_ocean.Status'),
        ),
        migrations.AlterField(
            model_name='company',
            name='contact_info',
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='registration_info',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='companytype',
            name='name',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='contact_info',
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='registration_info',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
