# Generated by Django 2.2 on 2020-06-03 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_ocean', '0002_register'),
        ('business_register', '0009_auto_20200603_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='founderfull',
            name='hash_code',
            field=models.CharField(default='1', max_length=510),
            preserve_default=False,
        ),
    ]
