# Generated by Django 2.2.13 on 2020-06-15 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('business_register', '0010_auto_20200611_1348'), ('business_register', '0011_remove_founderfull_name2'), ('business_register', '0012_auto_20200615_1037'), ('business_register', '0013_foundernew')]

    dependencies = [
        ('business_register', '0013_auto_20200613_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='founderfull',
            name='edrpou',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='assignee',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignees', to='business_register.Company'),
        ),
        migrations.AlterField(
            model_name='bancruptcyreadjustment',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bancruptcy_readjustment', to='business_register.Company'),
        ),
        migrations.AlterField(
            model_name='companydetail',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_detail', to='business_register.Company'),
        ),
        migrations.AlterField(
            model_name='companytokved',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kveds', to='business_register.Company'),
        ),
        migrations.AlterField(
            model_name='companytopredecessor',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predecessors', to='business_register.Company'),
        ),
        migrations.AlterField(
            model_name='exchangedatacompany',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_data', to='business_register.Company'),
        ),
        migrations.AlterField(
            model_name='founderfull',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='founders', to='business_register.Company'),
        ),
        migrations.AlterField(
            model_name='signer',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signers', to='business_register.Company'),
        ),
        migrations.AlterField(
            model_name='terminationstarted',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='termination_started', to='business_register.Company'),
        ),
        migrations.AddField(
            model_name='founderfull',
            name='equity',
            field=models.FloatField(null=True),
        ),
        migrations.CreateModel(
            name='FounderNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('name', models.TextField(null=True)),
                ('edrpou', models.CharField(max_length=9, null=True)),
                ('equity', models.FloatField(null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='founders', to='business_register.Company')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
