# Generated by Django 2.2.13 on 2020-06-11 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business_register', '0009_auto_20200605_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignee',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignees', to='business_register.Company'),
        ),
        migrations.AlterField(
            model_name='bancruptcyreadjustment',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bancruptcy_readjustment', to='business_register.Company'),
        ),
        migrations.AlterField(
            model_name='companydetail',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_detail', to='business_register.Company'),
        ),
        migrations.AlterField(
            model_name='companytokved',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kveds', to='business_register.Company'),
        ),
        migrations.AlterField(
            model_name='companytopredecessor',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predecessors', to='business_register.Company'),
        ),
        migrations.AlterField(
            model_name='exchangedatacompany',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_data', to='business_register.Company'),
        ),
        migrations.AlterField(
            model_name='founderfull',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='founders', to='business_register.Company'),
        ),
        migrations.AlterField(
            model_name='signer',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signers', to='business_register.Company'),
        ),
        migrations.AlterField(
            model_name='terminationstarted',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='termination_started', to='business_register.Company'),
        ),
    ]
