# Generated by Django 2.2 on 2020-06-04 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_ocean', '0002_register'),
        ('business_register', '0010_auto_20200603_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companytype',
            name='name',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
