# Generated by Django 2.2.13 on 2020-06-12 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_register', '0010_auto_20200611_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignee',
            name='hash_code',
            field=models.CharField(default='1', max_length=510),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bancruptcyreadjustment',
            name='hash_code',
            field=models.CharField(default='1', max_length=510),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companydetail',
            name='hash_code',
            field=models.CharField(default='1', max_length=510),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companytokved',
            name='hash_code',
            field=models.CharField(default='1', max_length=510),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companytopredecessor',
            name='hash_code',
            field=models.CharField(default='1', max_length=510),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exchangedatacompany',
            name='hash_code',
            field=models.CharField(default='1', max_length=510),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcompanydetail',
            name='hash_code',
            field=models.CharField(default='1', max_length=510),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signer',
            name='hash_code',
            field=models.CharField(default='1', max_length=510),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='terminationstarted',
            name='hash_code',
            field=models.CharField(default='1', max_length=510),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bylaw',
            name='name',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='companydetail',
            name='managing_paper',
            field=models.CharField(max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='companydetail',
            name='superior_management',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='companydetail',
            name='terminated_info',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='companydetail',
            name='termination_cancel_info',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='companydetail',
            name='vp_dates',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompanydetail',
            name='managing_paper',
            field=models.CharField(max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompanydetail',
            name='superior_management',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompanydetail',
            name='terminated_info',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompanydetail',
            name='termination_cancel_info',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompanydetail',
            name='vp_dates',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='predecessor',
            name='name',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
