# Generated by Django 2.2.13 on 2020-06-13 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_register', '0011_auto_20200612_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='contact_info',
            field=models.CharField(max_length=310, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='contact_info',
            field=models.CharField(max_length=310, null=True),
        ),
    ]
