# Generated by Django 2.2 on 2020-06-04 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_ocean', '0002_register'),
        ('business_register', '0011_auto_20200604_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='contact_info',
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='registration_info',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='contact_info',
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='registration_info',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
