# Generated by Django 2.2.13 on 2020-06-13 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_register', '0012_auto_20200613_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignee',
            name='name',
            field=models.CharField(max_length=610, null=True),
        ),
        migrations.AlterField(
            model_name='bancruptcyreadjustment',
            name='head_name',
            field=models.CharField(max_length=515, null=True),
        ),
        migrations.AlterField(
            model_name='bancruptcyreadjustment',
            name='sbj_state',
            field=models.CharField(max_length=345, null=True),
        ),
        migrations.AlterField(
            model_name='bylaw',
            name='name',
            field=models.CharField(max_length=320, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='edrpou',
            field=models.CharField(max_length=260),
        ),
        migrations.AlterField(
            model_name='company',
            name='registration_info',
            field=models.CharField(max_length=450, null=True),
        ),
        migrations.AlterField(
            model_name='companydetail',
            name='authorized_capital',
            field=models.CharField(max_length=560, null=True),
        ),
        migrations.AlterField(
            model_name='companydetail',
            name='executive_power',
            field=models.CharField(max_length=390, null=True),
        ),
        migrations.AlterField(
            model_name='companydetail',
            name='founding_document_number',
            field=models.CharField(max_length=375, null=True),
        ),
        migrations.AlterField(
            model_name='companydetail',
            name='managing_paper',
            field=models.CharField(max_length=360, null=True),
        ),
        migrations.AlterField(
            model_name='companydetail',
            name='superior_management',
            field=models.CharField(max_length=620, null=True),
        ),
        migrations.AlterField(
            model_name='companydetail',
            name='terminated_info',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='companydetail',
            name='termination_cancel_info',
            field=models.CharField(max_length=570, null=True),
        ),
        migrations.AlterField(
            model_name='companytype',
            name='name',
            field=models.CharField(max_length=270, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='exchangedatacompany',
            name='end_number',
            field=models.CharField(max_length=555, null=True),
        ),
        migrations.AlterField(
            model_name='exchangedatacompany',
            name='start_number',
            field=models.CharField(max_length=555, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='edrpou',
            field=models.CharField(max_length=260),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='registration_info',
            field=models.CharField(max_length=450, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompanydetail',
            name='authorized_capital',
            field=models.CharField(max_length=560, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompanydetail',
            name='executive_power',
            field=models.CharField(max_length=390, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompanydetail',
            name='founding_document_number',
            field=models.CharField(max_length=375, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompanydetail',
            name='managing_paper',
            field=models.CharField(max_length=360, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompanydetail',
            name='superior_management',
            field=models.CharField(max_length=620, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompanydetail',
            name='terminated_info',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompanydetail',
            name='termination_cancel_info',
            field=models.CharField(max_length=570, null=True),
        ),
        migrations.AlterField(
            model_name='predecessor',
            name='code',
            field=models.CharField(max_length=405, null=True),
        ),
        migrations.AlterField(
            model_name='signer',
            name='name',
            field=models.CharField(max_length=390, null=True),
        ),
        migrations.AlterField(
            model_name='terminationstarted',
            name='sbj_state',
            field=models.CharField(max_length=530, null=True),
        ),
        migrations.AlterField(
            model_name='terminationstarted',
            name='signer_name',
            field=models.CharField(max_length=480, null=True),
        ),
    ]
