# Generated by Django 3.0.7 on 2020-06-17 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_register', '0013_auto_20200617_0820'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='foundernew',
            index=models.Index(fields=['name', 'company'], name='business_re_name_df35a3_idx'),
        ),
    ]
