# Generated by Django 3.0.7 on 2020-07-08 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_register', '0016_auto_20200626_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignee',
            name='edrpou',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
