# Generated by Django 3.0.7 on 2020-07-10 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business_register', '0017_auto_20200707_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='KvedDivision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KvedSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='group',
            name='division',
        ),
        migrations.RemoveField(
            model_name='group',
            name='section',
        ),
        migrations.AddField(
            model_name='kved',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='kved',
            name='code',
            field=models.CharField(max_length=10),
        ),
        migrations.CreateModel(
            name='KvedGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=500)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_register.KvedDivision')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_register.KvedSection')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='kveddivision',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_register.KvedSection'),
        ),
        migrations.AlterField(
            model_name='kved',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_register.KvedDivision'),
        ),
        migrations.AlterField(
            model_name='kved',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_register.KvedGroup'),
        ),
        migrations.AlterField(
            model_name='kved',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_register.KvedSection'),
        ),
        migrations.DeleteModel(
            name='Division',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
