# Generated by Django 3.0.7 on 2020-07-17 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_register', '0020_auto_20200717_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='founderfull',
            name='address',
            field=models.CharField(max_length=505, null=True),
        ),
        migrations.AlterField(
            model_name='historicalfounderfull',
            name='address',
            field=models.CharField(max_length=505, null=True),
        ),
    ]
