# Generated by Django 3.0.7 on 2020-07-20 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business_register', '0023_auto_20200717_1902'),
    ]

    operations = [

        migrations.CreateModel(
            name='HistoricalAssignee',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=610, null=True)),
                ('edrpou', models.CharField(max_length=11, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical assignee',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),

        migrations.RenameField(
            model_name='company',
            old_name='hash_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='historicalcompany',
            old_name='hash_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='predecessor',
            old_name='code',
            new_name='edrpou',
        ),
        migrations.RemoveField(
            model_name='assignee',
            name='hash_code',
        ),
        migrations.RemoveField(
            model_name='bancruptcyreadjustment',
            name='hash_code',
        ),
        migrations.RemoveField(
            model_name='companydetail',
            name='hash_code',
        ),
        migrations.RemoveField(
            model_name='companytokved',
            name='hash_code',
        ),
        migrations.RemoveField(
            model_name='companytopredecessor',
            name='hash_code',
        ),
        migrations.RemoveField(
            model_name='exchangedatacompany',
            name='hash_code',
        ),
        migrations.RemoveField(
            model_name='historicalcompanydetail',
            name='hash_code',
        ),
        migrations.RemoveField(
            model_name='historicalsigner',
            name='hash_code',
        ),
        migrations.RemoveField(
            model_name='signer',
            name='hash_code',
        ),
        migrations.RemoveField(
            model_name='terminationstarted',
            name='hash_code',
        ),

        migrations.RemoveField(
            model_name='founderfull',
            name='hash_code',
        ),
        migrations.RemoveField(
            model_name='historicalfounderfull',
            name='hash_code',
        ),

        migrations.RenameModel('FounderFull', 'Founder'),

        migrations.RenameModel('HistoricalFounderFull', 'HistoricalFounder'),

        migrations.AddField(
            model_name='historicalassignee',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True,
                                    on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                    to='business_register.Company'),
        ),
        migrations.AddField(
            model_name='historicalassignee',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+',
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalfounder',
            name='info',
            field=models.CharField(max_length=2015, default='default'),
        ),
        migrations.AddField(
            model_name='founder',
            name='info',
            field=models.CharField(max_length=2015, default='default'),
        ),

    ]
