# Generated by Django 3.0.7 on 2020-07-24 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_ocean', '0006_auto_20200724_1128'),
        ('business_register', '0025_auto_20200722_1314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignee',
            options={'verbose_name': 'правонаступник', 'verbose_name_plural': 'правонаступники'},
        ),
        migrations.AlterModelOptions(
            name='bylaw',
            options={'verbose_name': 'статут'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'компанія/організація'},
        ),
        migrations.AlterModelOptions(
            name='companydetail',
            options={'verbose_name': 'додаткові дані'},
        ),
        migrations.AlterModelOptions(
            name='companytokved',
            options={'verbose_name': 'КВЕДи компанії'},
        ),
        migrations.AlterModelOptions(
            name='companytype',
            options={'verbose_name': 'організаційно-правова форма'},
        ),
        migrations.AlterModelOptions(
            name='fop',
            options={'verbose_name': 'фізична особа-підприємець'},
        ),
        migrations.AlterModelOptions(
            name='foptokved',
            options={'verbose_name': 'КВЕДи ФОП'},
        ),
        migrations.AlterModelOptions(
            name='founder',
            options={'verbose_name': 'засновник', 'verbose_name_plural': 'засновники'},
        ),
        migrations.AlterModelOptions(
            name='historicalassignee',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical правонаступник'},
        ),
        migrations.AlterModelOptions(
            name='historicalcompany',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical компанія/організація'},
        ),
        migrations.AlterModelOptions(
            name='historicalcompanydetail',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical додаткові дані'},
        ),
        migrations.AlterModelOptions(
            name='historicalfop',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical фізична особа-підприємець'},
        ),
        migrations.AlterModelOptions(
            name='historicalfounder',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical засновник'},
        ),
        migrations.AlterModelOptions(
            name='historicalsigner',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical має право підпису'},
        ),
        migrations.AlterModelOptions(
            name='kved',
            options={'verbose_name': 'КВЕД'},
        ),
        migrations.AlterModelOptions(
            name='kveddivision',
            options={'verbose_name': 'розділ'},
        ),
        migrations.AlterModelOptions(
            name='kvedgroup',
            options={'verbose_name': 'група'},
        ),
        migrations.AlterModelOptions(
            name='kvedsection',
            options={'verbose_name': 'секція'},
        ),
        migrations.AlterModelOptions(
            name='predecessor',
            options={'verbose_name': 'попередник', 'verbose_name_plural': 'попередники'},
        ),
        migrations.AlterModelOptions(
            name='signer',
            options={'verbose_name': 'має право підпису', 'verbose_name_plural': 'мають право підпису'},
        ),
        migrations.AlterField(
            model_name='assignee',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignees', to='business_register.Company', verbose_name='є правонаступником'),
        ),
        migrations.AlterField(
            model_name='assignee',
            name='edrpou',
            field=models.CharField(max_length=11, null=True, verbose_name='код ЄДРПОУ'),
        ),
        migrations.AlterField(
            model_name='assignee',
            name='name',
            field=models.CharField(max_length=610, null=True, verbose_name='правонаступник'),
        ),
        migrations.AlterField(
            model_name='bancruptcyreadjustment',
            name='reason',
            field=models.TextField(null=True, verbose_name='підстава'),
        ),
        migrations.AlterField(
            model_name='bylaw',
            name='name',
            field=models.CharField(max_length=320, null=True, unique=True, verbose_name='статут'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(max_length=1000, null=True, verbose_name='адреса'),
        ),
        migrations.AlterField(
            model_name='company',
            name='authority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_ocean.Authority', verbose_name='орган реєстрації'),
        ),
        migrations.AlterField(
            model_name='company',
            name='authorized_capital',
            field=models.FloatField(null=True, verbose_name='статутний капітал'),
        ),
        migrations.AlterField(
            model_name='company',
            name='bylaw',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_register.Bylaw', verbose_name='статут'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='business_register.CompanyType', verbose_name='організаційно-правова форма'),
        ),
        migrations.AlterField(
            model_name='company',
            name='contact_info',
            field=models.CharField(max_length=310, null=True, verbose_name='контакти'),
        ),
        migrations.AlterField(
            model_name='company',
            name='edrpou',
            field=models.CharField(db_index=True, max_length=260, verbose_name='код ЄДРПОУ'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=500, null=True, verbose_name='назва'),
        ),
        migrations.AlterField(
            model_name='company',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='business_register.Company', verbose_name='є підрозділом компанії/організації'),
        ),
        migrations.AlterField(
            model_name='company',
            name='registration_date',
            field=models.DateField(null=True, verbose_name='дата реєстрації'),
        ),
        migrations.AlterField(
            model_name='company',
            name='registration_info',
            field=models.CharField(max_length=450, null=True, verbose_name='реєстраційні дані'),
        ),
        migrations.AlterField(
            model_name='company',
            name='short_name',
            field=models.CharField(max_length=500, null=True, verbose_name='коротка назва'),
        ),
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_ocean.Status', verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='companytokved',
            name='kved',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_register.Kved', verbose_name='КВЕД'),
        ),
        migrations.AlterField(
            model_name='companytokved',
            name='primary_kved',
            field=models.BooleanField(default=False, verbose_name='зазначений як основний'),
        ),
        migrations.AlterField(
            model_name='companytopredecessor',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predecessors', to='business_register.Company', verbose_name='є попередником організації'),
        ),
        migrations.AlterField(
            model_name='companytype',
            name='name',
            field=models.CharField(max_length=270, null=True, unique=True, verbose_name='назва'),
        ),
        migrations.AlterField(
            model_name='exchangedatacompany',
            name='authority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_ocean.Authority', verbose_name='орган реєстрації'),
        ),
        migrations.AlterField(
            model_name='exchangedatafop',
            name='authority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_ocean.Authority', verbose_name='орган реєстрації'),
        ),
        migrations.AlterField(
            model_name='exchangedatafop',
            name='fop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_data', to='business_register.Fop', verbose_name='ФОП'),
        ),
        migrations.AlterField(
            model_name='exchangedatafop',
            name='taxpayer_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_ocean.TaxpayerType', verbose_name='тип платника податків'),
        ),
        migrations.AlterField(
            model_name='fop',
            name='address',
            field=models.CharField(max_length=500, null=True, verbose_name='адреса'),
        ),
        migrations.AlterField(
            model_name='fop',
            name='authority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_ocean.Authority', verbose_name='орган реєстрації'),
        ),
        migrations.AlterField(
            model_name='fop',
            name='contact_info',
            field=models.CharField(max_length=200, null=True, verbose_name='контакти'),
        ),
        migrations.AlterField(
            model_name='fop',
            name='fullname',
            field=models.CharField(max_length=100, verbose_name="повне ім'я"),
        ),
        migrations.AlterField(
            model_name='fop',
            name='registration_date',
            field=models.DateField(null=True, verbose_name='дата реєстрації'),
        ),
        migrations.AlterField(
            model_name='fop',
            name='registration_info',
            field=models.CharField(max_length=300, null=True, verbose_name='реєстраційні дані'),
        ),
        migrations.AlterField(
            model_name='fop',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_ocean.Status', verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='foptokved',
            name='fop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kveds', to='business_register.Fop', verbose_name='ФОП'),
        ),
        migrations.AlterField(
            model_name='foptokved',
            name='kved',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_register.Kved', verbose_name='КВЕД'),
        ),
        migrations.AlterField(
            model_name='foptokved',
            name='primary_kved',
            field=models.BooleanField(default=False, verbose_name='зазначений як основний'),
        ),
        migrations.AlterField(
            model_name='founder',
            name='address',
            field=models.CharField(max_length=2015, null=True, verbose_name='адреса'),
        ),
        migrations.AlterField(
            model_name='founder',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='founders', to='business_register.Company', verbose_name='є засновником компанії/організації'),
        ),
        migrations.AlterField(
            model_name='founder',
            name='edrpou',
            field=models.CharField(max_length=9, null=True, verbose_name='код ЄДРПОУ'),
        ),
        migrations.AlterField(
            model_name='founder',
            name='equity',
            field=models.FloatField(null=True, verbose_name='участь в статутному капіталі'),
        ),
        migrations.AlterField(
            model_name='founder',
            name='info',
            field=models.CharField(max_length=2015, verbose_name='наявні дані'),
        ),
        migrations.AlterField(
            model_name='founder',
            name='name',
            field=models.TextField(null=True, verbose_name="назва/повне ім'я"),
        ),
        migrations.AlterField(
            model_name='historicalassignee',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='business_register.Company', verbose_name='є правонаступником'),
        ),
        migrations.AlterField(
            model_name='historicalassignee',
            name='edrpou',
            field=models.CharField(max_length=11, null=True, verbose_name='код ЄДРПОУ'),
        ),
        migrations.AlterField(
            model_name='historicalassignee',
            name='name',
            field=models.CharField(max_length=610, null=True, verbose_name='правонаступник'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='address',
            field=models.CharField(max_length=1000, null=True, verbose_name='адреса'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='authority',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='data_ocean.Authority', verbose_name='орган реєстрації'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='authorized_capital',
            field=models.FloatField(null=True, verbose_name='статутний капітал'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='bylaw',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='business_register.Bylaw', verbose_name='статут'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='company_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='business_register.CompanyType', verbose_name='організаційно-правова форма'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='contact_info',
            field=models.CharField(max_length=310, null=True, verbose_name='контакти'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='edrpou',
            field=models.CharField(db_index=True, max_length=260, verbose_name='код ЄДРПОУ'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='name',
            field=models.CharField(max_length=500, null=True, verbose_name='назва'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='parent',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='business_register.Company', verbose_name='є підрозділом компанії/організації'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='registration_date',
            field=models.DateField(null=True, verbose_name='дата реєстрації'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='registration_info',
            field=models.CharField(max_length=450, null=True, verbose_name='реєстраційні дані'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='short_name',
            field=models.CharField(max_length=500, null=True, verbose_name='коротка назва'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='status',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='data_ocean.Status', verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='historicalfop',
            name='address',
            field=models.CharField(max_length=500, null=True, verbose_name='адреса'),
        ),
        migrations.AlterField(
            model_name='historicalfop',
            name='authority',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='data_ocean.Authority', verbose_name='орган реєстрації'),
        ),
        migrations.AlterField(
            model_name='historicalfop',
            name='contact_info',
            field=models.CharField(max_length=200, null=True, verbose_name='контакти'),
        ),
        migrations.AlterField(
            model_name='historicalfop',
            name='fullname',
            field=models.CharField(max_length=100, verbose_name="повне ім'я"),
        ),
        migrations.AlterField(
            model_name='historicalfop',
            name='registration_date',
            field=models.DateField(null=True, verbose_name='дата реєстрації'),
        ),
        migrations.AlterField(
            model_name='historicalfop',
            name='registration_info',
            field=models.CharField(max_length=300, null=True, verbose_name='реєстраційні дані'),
        ),
        migrations.AlterField(
            model_name='historicalfop',
            name='status',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='data_ocean.Status', verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='historicalfounder',
            name='address',
            field=models.CharField(max_length=2015, null=True, verbose_name='адреса'),
        ),
        migrations.AlterField(
            model_name='historicalfounder',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='business_register.Company', verbose_name='є засновником компанії/організації'),
        ),
        migrations.AlterField(
            model_name='historicalfounder',
            name='edrpou',
            field=models.CharField(max_length=9, null=True, verbose_name='код ЄДРПОУ'),
        ),
        migrations.AlterField(
            model_name='historicalfounder',
            name='equity',
            field=models.FloatField(null=True, verbose_name='участь в статутному капіталі'),
        ),
        migrations.AlterField(
            model_name='historicalfounder',
            name='info',
            field=models.CharField(max_length=2015, verbose_name='наявні дані'),
        ),
        migrations.AlterField(
            model_name='historicalfounder',
            name='name',
            field=models.TextField(null=True, verbose_name="назва/повне ім'я"),
        ),
        migrations.AlterField(
            model_name='historicalsigner',
            name='name',
            field=models.CharField(max_length=390, null=True, verbose_name="повне ім'я"),
        ),
        migrations.AlterField(
            model_name='kved',
            name='code',
            field=models.CharField(max_length=10, verbose_name='код'),
        ),
        migrations.AlterField(
            model_name='kved',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_register.KvedDivision', verbose_name='розділ'),
        ),
        migrations.AlterField(
            model_name='kved',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_register.KvedGroup', verbose_name='група'),
        ),
        migrations.AlterField(
            model_name='kved',
            name='is_valid',
            field=models.BooleanField(default=True, verbose_name='є чинним'),
        ),
        migrations.AlterField(
            model_name='kved',
            name='name',
            field=models.CharField(max_length=500, verbose_name='назва'),
        ),
        migrations.AlterField(
            model_name='kved',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_register.KvedSection', verbose_name='секція'),
        ),
        migrations.AlterField(
            model_name='kveddivision',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name='код'),
        ),
        migrations.AlterField(
            model_name='kveddivision',
            name='name',
            field=models.CharField(max_length=500, verbose_name='назва'),
        ),
        migrations.AlterField(
            model_name='kveddivision',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_register.KvedSection', verbose_name='секція'),
        ),
        migrations.AlterField(
            model_name='kvedgroup',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name='код'),
        ),
        migrations.AlterField(
            model_name='kvedgroup',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_register.KvedDivision', verbose_name='розділ'),
        ),
        migrations.AlterField(
            model_name='kvedgroup',
            name='name',
            field=models.CharField(max_length=500, verbose_name='назва'),
        ),
        migrations.AlterField(
            model_name='kvedgroup',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_register.KvedSection', verbose_name='секція'),
        ),
        migrations.AlterField(
            model_name='kvedsection',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name='код'),
        ),
        migrations.AlterField(
            model_name='kvedsection',
            name='name',
            field=models.CharField(max_length=500, verbose_name='назва'),
        ),
        migrations.AlterField(
            model_name='predecessor',
            name='edrpou',
            field=models.CharField(max_length=405, null=True, verbose_name='код ЄДРПОУ'),
        ),
        migrations.AlterField(
            model_name='predecessor',
            name='name',
            field=models.CharField(max_length=500, null=True, verbose_name='назва'),
        ),
        migrations.AlterField(
            model_name='signer',
            name='name',
            field=models.CharField(max_length=390, null=True, verbose_name="повне ім'я"),
        ),
        migrations.AlterField(
            model_name='terminationstarted',
            name='reason',
            field=models.TextField(null=True, verbose_name='підстава'),
        ),
    ]
