# Generated by Django 3.0.7 on 2020-07-28 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_register', '0026_auto_20200727_1413'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['id'], 'verbose_name': 'компанія/організація'},
        ),
    ]
