# Generated by Django 3.0.7 on 2020-07-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_register', '0027_auto_20200728_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fop',
            name='vp_dates',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='historicalfop',
            name='vp_dates',
            field=models.CharField(max_length=240, null=True),
        ),
    ]
