# Generated by Django 3.0.7 on 2020-07-31 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_register', '0028_auto_20200729_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fop',
            name='code',
            field=models.CharField(db_index=True, max_length=675),
        ),
        migrations.AlterField(
            model_name='fop',
            name='fullname',
            field=models.CharField(max_length=175, verbose_name="повне ім'я"),
        ),
        migrations.AlterField(
            model_name='historicalfop',
            name='code',
            field=models.CharField(db_index=True, max_length=675),
        ),
        migrations.AlterField(
            model_name='historicalfop',
            name='fullname',
            field=models.CharField(max_length=175, verbose_name="повне ім'я"),
        ),
    ]
