# Generated by Django 3.0.7 on 2020-08-10 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_ocean', '0006_auto_20200724_1128'),
        ('business_register', '0030_companylinkwithpep_historicalpep_pep_pepdeclaration_peprelatedcountry_peprelatedperson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalpep',
            old_name='last_workplace',
            new_name='last_employer',
        ),
        migrations.RenameField(
            model_name='historicalpep',
            old_name='last_workplace_eng',
            new_name='last_employer_eng',
        ),
        migrations.RenameField(
            model_name='pep',
            old_name='last_workplace',
            new_name='last_employer',
        ),
        migrations.RenameField(
            model_name='pep',
            old_name='last_workplace_eng',
            new_name='last_employer_eng',
        ),
        migrations.RenameField(
            model_name='pepdeclaration',
            old_name='office',
            new_name='employer',
        ),
        migrations.RenameField(
            model_name='pepdeclaration',
            old_name='office_eng',
            new_name='employer_eng',
        ),
        migrations.RemoveField(
            model_name='historicalpep',
            name='is_alive',
        ),
        migrations.RemoveField(
            model_name='pep',
            name='is_alive',
        ),
        migrations.AddField(
            model_name='company',
            name='from_antac_only',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='historicalcompany',
            name='from_antac_only',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='historicalpep',
            name='code',
            field=models.CharField(default='111', max_length=135),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalpep',
            name='is_dead',
            field=models.BooleanField(default=False, verbose_name='помер'),
        ),
        migrations.AddField(
            model_name='pep',
            name='code',
            field=models.CharField(default='111', max_length=135),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pep',
            name='is_dead',
            field=models.BooleanField(default=False, verbose_name='помер'),
        ),
        migrations.AddField(
            model_name='peprelatedperson',
            name='confirmation_date',
            field=models.CharField(max_length=12, null=True, verbose_name="дата підтвердження зв'язку із публічним діячем"),
        ),
        migrations.AddField(
            model_name='peprelatedperson',
            name='end_date',
            field=models.CharField(max_length=12, null=True, verbose_name="дата припинення зв'язку із публічним діячем"),
        ),
        migrations.AddField(
            model_name='peprelatedperson',
            name='fullname_eng',
            field=models.CharField(max_length=75, null=True, verbose_name="повне ім'я"),
        ),
        migrations.AddField(
            model_name='peprelatedperson',
            name='relationship_type_eng',
            field=models.CharField(max_length=90, null=True, verbose_name="тип зв'язку із публічним діячем англійською"),
        ),
        migrations.AddField(
            model_name='peprelatedperson',
            name='start_date',
            field=models.CharField(max_length=12, null=True, verbose_name="дата виникнення зв'язку із публічним діячем"),
        ),
        migrations.AlterField(
            model_name='company',
            name='authority',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_ocean.Authority', verbose_name='орган реєстрації'),
        ),
        migrations.AlterField(
            model_name='company',
            name='bylaw',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='business_register.Bylaw', verbose_name='статут'),
        ),
        migrations.AlterField(
            model_name='company',
            name='edrpou',
            field=models.CharField(db_index=True, max_length=260, null=True, verbose_name='код ЄДРПОУ'),
        ),
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_ocean.Status', verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='companylinkwithpep',
            name='confirmation_date',
            field=models.CharField(max_length=12, null=True, verbose_name="дата підтвердження зв'язку із публічним діячем"),
        ),
        migrations.AlterField(
            model_name='companylinkwithpep',
            name='end_date',
            field=models.CharField(max_length=12, null=True, verbose_name="дата припинення зв'язку із публічним діячем"),
        ),
        migrations.AlterField(
            model_name='companylinkwithpep',
            name='pep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_companies', to='business_register.Pep', verbose_name="пов'язаний з компанією публічний діяч"),
        ),
        migrations.AlterField(
            model_name='companylinkwithpep',
            name='relationship_type',
            field=models.CharField(max_length=550, null=True, verbose_name="тип зв'язку із публічним діячем"),
        ),
        migrations.AlterField(
            model_name='companylinkwithpep',
            name='relationship_type_eng',
            field=models.CharField(max_length=550, null=True, verbose_name="тип зв'язку із публічним діячем англійською"),
        ),
        migrations.AlterField(
            model_name='companylinkwithpep',
            name='start_date',
            field=models.CharField(max_length=12, null=True, verbose_name="дата виникнення зв'язку із публічним діячем"),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='edrpou',
            field=models.CharField(db_index=True, max_length=260, null=True, verbose_name='код ЄДРПОУ'),
        ),
        migrations.AlterField(
            model_name='historicalpep',
            name='fullname_transcriptions_eng',
            field=models.TextField(verbose_name='варіанти написання повного імені англійською'),
        ),
        migrations.AlterField(
            model_name='historicalpep',
            name='last_job_title',
            field=models.CharField(max_length=340, null=True, verbose_name='остання посада'),
        ),
        migrations.AlterField(
            model_name='historicalpep',
            name='last_job_title_eng',
            field=models.CharField(max_length=340, null=True, verbose_name='остання посада англійською'),
        ),
        migrations.AlterField(
            model_name='historicalpep',
            name='reason_of_termination',
            field=models.CharField(max_length=125, null=True, verbose_name='причина припинення статусу публічного діяча'),
        ),
        migrations.AlterField(
            model_name='historicalpep',
            name='reason_of_termination_eng',
            field=models.CharField(max_length=125, null=True, verbose_name='причина припинення статусу публічного діяча англійською'),
        ),
        migrations.AlterField(
            model_name='historicalpep',
            name='termination_date',
            field=models.CharField(max_length=10, null=True, verbose_name='дата припинення статусу публічного діяча'),
        ),
        migrations.AlterField(
            model_name='pep',
            name='fullname_transcriptions_eng',
            field=models.TextField(verbose_name='варіанти написання повного імені англійською'),
        ),
        migrations.AlterField(
            model_name='pep',
            name='last_job_title',
            field=models.CharField(max_length=340, null=True, verbose_name='остання посада'),
        ),
        migrations.AlterField(
            model_name='pep',
            name='last_job_title_eng',
            field=models.CharField(max_length=340, null=True, verbose_name='остання посада англійською'),
        ),
        migrations.AlterField(
            model_name='pep',
            name='reason_of_termination',
            field=models.CharField(max_length=125, null=True, verbose_name='причина припинення статусу публічного діяча'),
        ),
        migrations.AlterField(
            model_name='pep',
            name='reason_of_termination_eng',
            field=models.CharField(max_length=125, null=True, verbose_name='причина припинення статусу публічного діяча англійською'),
        ),
        migrations.AlterField(
            model_name='pep',
            name='termination_date',
            field=models.CharField(max_length=10, null=True, verbose_name='дата припинення статусу публічного діяча'),
        ),
        migrations.AlterField(
            model_name='peprelatedperson',
            name='pep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_persons', to='business_register.Pep', verbose_name="публічний діяч, з яким є зв'язок"),
        ),
        migrations.AlterField(
            model_name='peprelatedperson',
            name='relationship_type',
            field=models.CharField(max_length=90, null=True, verbose_name="тип зв'язку із публічним діячем"),
        ),
    ]
