# Generated by Django 3.0.7 on 2020-08-12 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_register', '0031_auto_20200810_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpep',
            name='fullname',
            field=models.CharField(db_index=True, max_length=75, verbose_name="повне ім'я"),
        ),
        migrations.AlterField(
            model_name='historicalpep',
            name='fullname_eng',
            field=models.CharField(db_index=True, max_length=75, verbose_name="повне ім'я англійською"),
        ),
        migrations.AlterField(
            model_name='pep',
            name='fullname',
            field=models.CharField(db_index=True, max_length=75, verbose_name="повне ім'я"),
        ),
        migrations.AlterField(
            model_name='pep',
            name='fullname_eng',
            field=models.CharField(db_index=True, max_length=75, verbose_name="повне ім'я англійською"),
        ),
    ]
