# Generated by Django 3.0.7 on 2020-08-14 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_register', '0033_auto_20200812_1811'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FounderNew',
        ),
    ]
