# Generated by Django 3.0.7 on 2020-08-19 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_register', '0034_delete_foundernew'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpep',
            name='first_name',
            field=models.CharField(default='', max_length=20, verbose_name="ім'я"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalpep',
            name='last_name',
            field=models.CharField(default='', max_length=30, verbose_name='прізвище'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalpep',
            name='middle_name',
            field=models.CharField(default='', max_length=25, verbose_name='по батькові'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pep',
            name='first_name',
            field=models.CharField(default='', max_length=20, verbose_name="ім'я"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pep',
            name='last_name',
            field=models.CharField(default='', max_length=30, verbose_name='прізвище'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pep',
            name='middle_name',
            field=models.CharField(default='', max_length=25, verbose_name='по батькові'),
            preserve_default=False,
        ),
    ]
