# Generated by Django 3.0.7 on 2020-08-19 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_register', '0035_auto_20200819_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='founder',
            name='name',
            field=models.TextField(db_index=True, null=True, verbose_name="назва/повне ім'я"),
        ),
        migrations.AlterField(
            model_name='historicalfounder',
            name='name',
            field=models.TextField(db_index=True, null=True, verbose_name="назва/повне ім'я"),
        ),
    ]
