# Generated by Django 3.0.7 on 2020-08-20 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_register', '0036_auto_20200819_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpep',
            name='code',
        ),
        migrations.RemoveField(
            model_name='historicalpep',
            name='url',
        ),
    ]
