# Generated by Django 3.0.7 on 2020-08-28 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location_register', '0010_country'),
        ('business_register', '0038_auto_20200827_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='country',
            field=models.ForeignKey(max_length=60, null=True, on_delete=django.db.models.deletion.CASCADE, to='location_register.Country', verbose_name='країна'),
        ),
        migrations.AddField(
            model_name='historicalcompany',
            name='country',
            field=models.ForeignKey(blank=True, db_constraint=False, max_length=60, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='location_register.Country', verbose_name='країна'),
        ),
    ]
