# Generated by Django 3.0.7 on 2020-09-11 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_register', '0039_auto_20200828_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='registration_date',
            field=models.DateField(db_index=True, null=True, verbose_name='дата реєстрації'),
        ),
        migrations.AlterField(
            model_name='fop',
            name='registration_date',
            field=models.DateField(db_index=True, null=True, verbose_name='дата реєстрації'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='registration_date',
            field=models.DateField(db_index=True, null=True, verbose_name='дата реєстрації'),
        ),
        migrations.AlterField(
            model_name='historicalfop',
            name='registration_date',
            field=models.DateField(db_index=True, null=True, verbose_name='дата реєстрації'),
        ),
        migrations.AlterField(
            model_name='kved',
            name='code',
            field=models.CharField(db_index=True, max_length=10, verbose_name='код'),
        ),
    ]
