# Generated by Django 3.0.7 on 2020-09-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_register', '0039_auto_20200828_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='companytype',
            name='name_eng',
            field=models.CharField(max_length=270, null=True, unique=True, verbose_name='назва англійською'),
        ),
    ]
