# Generated by Django 3.0.7 on 2020-09-15 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_register', '0040_companytype_name_eng'),
        ('business_register', '0040_auto_20200911_1738'),
    ]

    operations = [
    ]
