# Generated by Django 3.0.7 on 2020-09-15 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_register', '0041_merge_20200915_1923'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fop',
            options={'ordering': ['id'], 'verbose_name': 'фізична особа-підприємець'},
        ),
    ]
