# Generated by Django 3.0.7 on 2020-10-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_register', '0044_auto_20201009_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpep',
            name='source_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='id from original ANTAC`s DB'),
        ),
        migrations.AddField(
            model_name='pep',
            name='source_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, unique=True, verbose_name='id from original ANTAC`s DB'),
        ),
    ]
