# Generated by Django 3.0.7 on 2020-11-12 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_register', '0046_auto_20201029_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='boss',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='керівник'),
        ),
        migrations.AddField(
            model_name='founder',
            name='is_beneficiary',
            field=models.BooleanField(blank=True, default=False, verbose_name='є бенефіціаром'),
        ),
        migrations.AddField(
            model_name='founder',
            name='is_founder',
            field=models.BooleanField(blank=True, default=False, verbose_name='є офіційним засновником'),
        ),
        migrations.AddField(
            model_name='historicalcompany',
            name='boss',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='керівник'),
        ),
        migrations.AddField(
            model_name='historicalfounder',
            name='is_beneficiary',
            field=models.BooleanField(blank=True, default=False, verbose_name='є бенефіціаром'),
        ),
        migrations.AddField(
            model_name='historicalfounder',
            name='is_founder',
            field=models.BooleanField(blank=True, default=False, verbose_name='є офіційним засновником'),
        ),
        migrations.AlterField(
            model_name='company',
            name='code',
            field=models.CharField(db_index=True, max_length=510),
        ),
        migrations.AlterField(
            model_name='company',
            name='registration_date',
            field=models.DateField(null=True, verbose_name='дата реєстрації'),
        ),
        migrations.AlterField(
            model_name='founder',
            name='address',
            field=models.CharField(blank=True, default='', max_length=2015, null=True, verbose_name='адреса'),
        ),
        migrations.AlterField(
            model_name='founder',
            name='edrpou',
            field=models.CharField(blank=True, db_index=True, default='', max_length=9, null=True, verbose_name='код ЄДРПОУ'),
        ),
        migrations.AlterField(
            model_name='founder',
            name='equity',
            field=models.FloatField(blank=True, null=True, verbose_name='участь в статутному капіталі'),
        ),
        migrations.AlterField(
            model_name='founder',
            name='name',
            field=models.TextField(db_index=True, verbose_name="назва/повне ім'я"),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='code',
            field=models.CharField(db_index=True, max_length=510),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='registration_date',
            field=models.DateField(null=True, verbose_name='дата реєстрації'),
        ),
        migrations.AlterField(
            model_name='historicalfounder',
            name='address',
            field=models.CharField(blank=True, default='', max_length=2015, null=True, verbose_name='адреса'),
        ),
        migrations.AlterField(
            model_name='historicalfounder',
            name='edrpou',
            field=models.CharField(blank=True, db_index=True, default='', max_length=9, null=True, verbose_name='код ЄДРПОУ'),
        ),
        migrations.AlterField(
            model_name='historicalfounder',
            name='equity',
            field=models.FloatField(blank=True, null=True, verbose_name='участь в статутному капіталі'),
        ),
        migrations.AlterField(
            model_name='historicalfounder',
            name='name',
            field=models.TextField(db_index=True, verbose_name="назва/повне ім'я"),
        ),
    ]
