# Generated by Django 3.0.7 on 2020-11-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_register', '0047_auto_20201112_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pep',
            name='url',
        ),
        migrations.AlterField(
            model_name='historicalpep',
            name='pep_type',
            field=models.CharField(blank=True, choices=[('national PEP', 'National PEP'), ('foreign PEP', 'Foreign PEP'), ('PEP with political functions in international organization', 'PEP with political functions in international organization'), ('associated person with PEP', 'Associated person with PEP'), ('member of PEP`s family', 'Member of PEP`s family')], max_length=60, null=True, verbose_name='тип публічного діяча'),
        ),
        migrations.AlterField(
            model_name='historicalpep',
            name='reason_of_termination',
            field=models.CharField(blank=True, choices=[('died', 'Died'), ('resigned', 'Resigned'), ('linked pep died', 'Linked pep died'), ('linked pep resigned', 'Linked pep resigned'), ('legislation changed', 'Legislation changed'), ('company status changed', 'Company status changed')], max_length=125, null=True, verbose_name='причина припинення статусу публічного діяча'),
        ),
        migrations.AlterField(
            model_name='pep',
            name='pep_type',
            field=models.CharField(blank=True, choices=[('national PEP', 'National PEP'), ('foreign PEP', 'Foreign PEP'), ('PEP with political functions in international organization', 'PEP with political functions in international organization'), ('associated person with PEP', 'Associated person with PEP'), ('member of PEP`s family', 'Member of PEP`s family')], max_length=60, null=True, verbose_name='тип публічного діяча'),
        ),
        migrations.AlterField(
            model_name='pep',
            name='reason_of_termination',
            field=models.CharField(blank=True, choices=[('died', 'Died'), ('resigned', 'Resigned'), ('linked pep died', 'Linked pep died'), ('linked pep resigned', 'Linked pep resigned'), ('legislation changed', 'Legislation changed'), ('company status changed', 'Company status changed')], max_length=125, null=True, verbose_name='причина припинення статусу публічного діяча'),
        ),
    ]
