# Generated by Django 3.0.7 on 2020-11-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_register', '0049_auto_20201125_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companylinkwithpep',
            name='category',
            field=models.CharField(blank=True, choices=[('bank_customer', 'Клієнт банку'), ('owner', 'Власник'), ('manager', 'Керівник'), ('other', 'Інше')], default=None, max_length=15, null=True, verbose_name='категорія'),
        ),
        migrations.AlterField(
            model_name='historicalpep',
            name='pep_type',
            field=models.CharField(blank=True, choices=[('national PEP', 'Національний публічний діяч'), ('foreign PEP', 'Іноземний публічний діяч'), ('PEP with political functions in international organization', 'Діяч, що виконує політичні функції у міжнародній організації'), ('associated person with PEP', "Пов'язана особа"), ('member of PEP`s family', "Член сім'ї")], max_length=60, null=True, verbose_name='тип публічного діяча'),
        ),
        migrations.AlterField(
            model_name='historicalpep',
            name='reason_of_termination',
            field=models.CharField(blank=True, choices=[('died', 'Помер'), ('resigned', 'Звільнився або закінчилися повноваження'), ('linked pep died', "Пов'язана особа або член сім'ї-публічний діяч помер"), ('linked pep resigned', "Пов'язана особа або член сім'ї-публічний діяч припинив ним бути"), ('legislation changed', 'Змінилося законодавство, що визначає статус публічного діяча'), ('company status changed', 'Змінилася форма власності компанії, посада в який надавала статус публічного діяча')], max_length=125, null=True, verbose_name='причина припинення статусу публічного діяча'),
        ),
        migrations.AlterField(
            model_name='pep',
            name='pep_type',
            field=models.CharField(blank=True, choices=[('national PEP', 'Національний публічний діяч'), ('foreign PEP', 'Іноземний публічний діяч'), ('PEP with political functions in international organization', 'Діяч, що виконує політичні функції у міжнародній організації'), ('associated person with PEP', "Пов'язана особа"), ('member of PEP`s family', "Член сім'ї")], max_length=60, null=True, verbose_name='тип публічного діяча'),
        ),
        migrations.AlterField(
            model_name='pep',
            name='reason_of_termination',
            field=models.CharField(blank=True, choices=[('died', 'Помер'), ('resigned', 'Звільнився або закінчилися повноваження'), ('linked pep died', "Пов'язана особа або член сім'ї-публічний діяч помер"), ('linked pep resigned', "Пов'язана особа або член сім'ї-публічний діяч припинив ним бути"), ('legislation changed', 'Змінилося законодавство, що визначає статус публічного діяча'), ('company status changed', 'Змінилася форма власності компанії, посада в який надавала статус публічного діяча')], max_length=125, null=True, verbose_name='причина припинення статусу публічного діяча'),
        ),
    ]
