# Generated by Django 3.0.7 on 2020-12-14 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_ocean', '0015_auto_20201117_1922'),
        ('business_register', '0050_auto_20201126_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fop',
            name='authority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_ocean.Authority', verbose_name='орган реєстрації'),
        ),
        migrations.AlterField(
            model_name='fop',
            name='contact_info',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='контакти'),
        ),
        migrations.AlterField(
            model_name='fop',
            name='estate_manager',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='fop',
            name='registration_date',
            field=models.DateField(blank=True, null=True, verbose_name='дата реєстрації'),
        ),
        migrations.AlterField(
            model_name='fop',
            name='registration_info',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='реєстраційні дані'),
        ),
        migrations.AlterField(
            model_name='fop',
            name='terminated_info',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='fop',
            name='termination_cancel_info',
            field=models.CharField(blank=True, max_length=275, null=True),
        ),
        migrations.AlterField(
            model_name='fop',
            name='termination_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fop',
            name='vp_dates',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='historicalfop',
            name='contact_info',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='контакти'),
        ),
        migrations.AlterField(
            model_name='historicalfop',
            name='estate_manager',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='historicalfop',
            name='registration_date',
            field=models.DateField(blank=True, null=True, verbose_name='дата реєстрації'),
        ),
        migrations.AlterField(
            model_name='historicalfop',
            name='registration_info',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='реєстраційні дані'),
        ),
        migrations.AlterField(
            model_name='historicalfop',
            name='terminated_info',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='historicalfop',
            name='termination_cancel_info',
            field=models.CharField(blank=True, max_length=275, null=True),
        ),
        migrations.AlterField(
            model_name='historicalfop',
            name='termination_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalfop',
            name='vp_dates',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
    ]
