# Generated by Django 3.0.7 on 2020-12-28 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_register', '0052_auto_20201222_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatedpersonslink',
            name='relationship_category',
            field=models.CharField(blank=True, choices=[('family', 'родина'), ('business', 'бізнес'), ('personal', "персональний зв'язок")], max_length=20, null=True, verbose_name="категорія зв'язку між особами"),
        ),
    ]
