# Generated by Django 3.0.7 on 2020-12-31 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_register', '0054_auto_20201229_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pep',
            name='code',
            field=models.CharField(db_index=True, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='pep',
            name='source_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='id from original ANTAC`s DB'),
        ),
    ]
