# Generated by Django 3.0.7 on 2021-01-12 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_register', '0051_historicalbancruptcyreadjustment_historicalcompanytokved_historicalcompanytopredecessor_historicalex'),
        ('business_register', '0055_auto_20201231_1347'),
    ]

    operations = [
    ]
