# Generated by Django 3.0.7 on 2021-01-22 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_register', '0057_auto_20210114_1208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'компанія/організація'},
        ),
        migrations.AlterIndexTogether(
            name='company',
            index_together={('edrpou', 'source')},
        ),
    ]
