# Generated by Django 3.0.7 on 2021-01-26 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_register', '0058_auto_20210122_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='founder',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='держава'),
        ),
        migrations.AddField(
            model_name='founder',
            name='info_additional',
            field=models.CharField(max_length=2015, null=True, verbose_name='додаткові наявні дані'),
        ),
        migrations.AddField(
            model_name='founder',
            name='info_beneficiary',
            field=models.CharField(max_length=2015, null=True, verbose_name='наявні дані бенефіціара'),
        ),
        migrations.AddField(
            model_name='historicalfounder',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='держава'),
        ),
        migrations.AddField(
            model_name='historicalfounder',
            name='info_additional',
            field=models.CharField(max_length=2015, null=True, verbose_name='додаткові наявні дані'),
        ),
        migrations.AddField(
            model_name='historicalfounder',
            name='info_beneficiary',
            field=models.CharField(max_length=2015, null=True, verbose_name='наявні дані бенефіціара'),
        ),
    ]
