# Generated by Django 3.0.7 on 2021-01-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_register', '0059_auto_20210126_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='source',
            field=models.CharField(blank=True, choices=[('ukr', 'Єдиний державний реєстр юридичних осіб, фізичних осіб – підприємців та громадських формувань України'), ('uk', 'Companies House'), ('antac', 'Центр протидії корупції')], default=None, max_length=5, null=True, verbose_name='джерело даних'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='source',
            field=models.CharField(blank=True, choices=[('ukr', 'Єдиний державний реєстр юридичних осіб, фізичних осіб – підприємців та громадських формувань України'), ('uk', 'Companies House'), ('antac', 'Центр протидії корупції')], default=None, max_length=5, null=True, verbose_name='джерело даних'),
        ),
    ]
