# Generated by Django 3.0.7 on 2021-02-15 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location_register', '0018_auto_20210215_1042'),
        ('data_ocean', '0018_auto_20210215_1042'),
        ('business_register', '0062_auto_20210211_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peprelatedcountry',
            name='pep',
        ),
        migrations.AlterModelOptions(
            name='assignee',
            options={'verbose_name': 'assignee'},
        ),
        migrations.AlterModelOptions(
            name='bancruptcyreadjustment',
            options={'verbose_name': 'bankruptcy readjustment'},
        ),
        migrations.AlterModelOptions(
            name='bylaw',
            options={'verbose_name': 'charter'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'company', 'verbose_name_plural': 'companies'},
        ),
        migrations.AlterModelOptions(
            name='companydetail',
            options={'verbose_name': 'additional info'},
        ),
        migrations.AlterModelOptions(
            name='companylinkwithpep',
            options={'ordering': ['id'], 'verbose_name': 'company connection with Pep', 'verbose_name_plural': 'company connections with Peps'},
        ),
        migrations.AlterModelOptions(
            name='companytokved',
            options={'verbose_name': 'NACE'},
        ),
        migrations.AlterModelOptions(
            name='companytype',
            options={'verbose_name': 'company type'},
        ),
        migrations.AlterModelOptions(
            name='exchangedatacompany',
            options={'verbose_name': 'registration info'},
        ),
        migrations.AlterModelOptions(
            name='exchangedatafop',
            options={'verbose_name': 'registration info'},
        ),
        migrations.AlterModelOptions(
            name='fop',
            options={'ordering': ['id'], 'verbose_name': 'entrepreneur', 'verbose_name_plural': 'entrepreneurs'},
        ),
        migrations.AlterModelOptions(
            name='foptokved',
            options={'verbose_name': 'NACE'},
        ),
        migrations.AlterModelOptions(
            name='founder',
            options={'verbose_name': 'owner'},
        ),
        migrations.AlterModelOptions(
            name='historicalassignee',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical assignee'},
        ),
        migrations.AlterModelOptions(
            name='historicalbancruptcyreadjustment',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical bankruptcy readjustment'},
        ),
        migrations.AlterModelOptions(
            name='historicalcompany',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical company'},
        ),
        migrations.AlterModelOptions(
            name='historicalcompanydetail',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical additional info'},
        ),
        migrations.AlterModelOptions(
            name='historicalcompanytokved',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical NACE'},
        ),
        migrations.AlterModelOptions(
            name='historicalexchangedatacompany',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical registration info'},
        ),
        migrations.AlterModelOptions(
            name='historicalfop',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical entrepreneur'},
        ),
        migrations.AlterModelOptions(
            name='historicalfounder',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical owner'},
        ),
        migrations.AlterModelOptions(
            name='historicalpep',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical politically exposed person'},
        ),
        migrations.AlterModelOptions(
            name='historicalsigner',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical signer'},
        ),
        migrations.AlterModelOptions(
            name='historicalterminationstarted',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical termination'},
        ),
        migrations.AlterModelOptions(
            name='kved',
            options={'verbose_name': 'NACE', 'verbose_name_plural': 'Classification of economic activities'},
        ),
        migrations.AlterModelOptions(
            name='kveddivision',
            options={'verbose_name': 'division'},
        ),
        migrations.AlterModelOptions(
            name='kvedgroup',
            options={'verbose_name': 'group'},
        ),
        migrations.AlterModelOptions(
            name='kvedsection',
            options={'verbose_name': 'section'},
        ),
        migrations.AlterModelOptions(
            name='pep',
            options={'ordering': ['id'], 'verbose_name': 'politically exposed person', 'verbose_name_plural': 'politically exposed persons'},
        ),
        migrations.AlterModelOptions(
            name='predecessor',
            options={'verbose_name': 'predecessor'},
        ),
        migrations.AlterModelOptions(
            name='relatedpersonslink',
            options={'ordering': ['id'], 'verbose_name': 'connection with another PEP', 'verbose_name_plural': 'connections with PEPs'},
        ),
        migrations.AlterModelOptions(
            name='signer',
            options={'verbose_name': 'signer'},
        ),
        migrations.AlterModelOptions(
            name='terminationstarted',
            options={'verbose_name': 'termination'},
        ),
        migrations.RemoveField(
            model_name='companylinkwithpep',
            name='company_name_eng',
        ),
        migrations.RemoveField(
            model_name='companylinkwithpep',
            name='company_short_name_eng',
        ),
        migrations.RemoveField(
            model_name='companylinkwithpep',
            name='relationship_type_eng',
        ),
        migrations.RemoveField(
            model_name='historicalpep',
            name='assets_info_eng',
        ),
        migrations.RemoveField(
            model_name='historicalpep',
            name='criminal_proceedings_eng',
        ),
        migrations.RemoveField(
            model_name='historicalpep',
            name='criminal_record_eng',
        ),
        migrations.RemoveField(
            model_name='historicalpep',
            name='fullname_eng',
        ),
        migrations.RemoveField(
            model_name='historicalpep',
            name='info_eng',
        ),
        migrations.RemoveField(
            model_name='historicalpep',
            name='last_employer_eng',
        ),
        migrations.RemoveField(
            model_name='historicalpep',
            name='last_job_title_eng',
        ),
        migrations.RemoveField(
            model_name='historicalpep',
            name='pep_type_eng',
        ),
        migrations.RemoveField(
            model_name='historicalpep',
            name='place_of_birth_eng',
        ),
        migrations.RemoveField(
            model_name='historicalpep',
            name='reason_of_termination_eng',
        ),
        migrations.RemoveField(
            model_name='historicalpep',
            name='sanctions_eng',
        ),
        migrations.RemoveField(
            model_name='historicalpep',
            name='wanted_eng',
        ),
        migrations.RemoveField(
            model_name='pep',
            name='assets_info_eng',
        ),
        migrations.RemoveField(
            model_name='pep',
            name='criminal_proceedings_eng',
        ),
        migrations.RemoveField(
            model_name='pep',
            name='criminal_record_eng',
        ),
        migrations.RemoveField(
            model_name='pep',
            name='fullname_eng',
        ),
        migrations.RemoveField(
            model_name='pep',
            name='info_eng',
        ),
        migrations.RemoveField(
            model_name='pep',
            name='last_employer_eng',
        ),
        migrations.RemoveField(
            model_name='pep',
            name='last_job_title_eng',
        ),
        migrations.RemoveField(
            model_name='pep',
            name='pep_type_eng',
        ),
        migrations.RemoveField(
            model_name='pep',
            name='place_of_birth_eng',
        ),
        migrations.RemoveField(
            model_name='pep',
            name='reason_of_termination_eng',
        ),
        migrations.RemoveField(
            model_name='pep',
            name='sanctions_eng',
        ),
        migrations.RemoveField(
            model_name='pep',
            name='wanted_eng',
        ),
        migrations.AlterField(
            model_name='assignee',
            name='edrpou',
            field=models.CharField(max_length=11, null=True, verbose_name='number'),
        ),
        migrations.AlterField(
            model_name='assignee',
            name='name',
            field=models.CharField(max_length=610, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='bancruptcyreadjustment',
            name='reason',
            field=models.TextField(null=True, verbose_name='reason'),
        ),
        migrations.AlterField(
            model_name='bylaw',
            name='name',
            field=models.CharField(max_length=320, null=True, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(max_length=1000, null=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='company',
            name='antac_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, default=None, null=True, unique=True, verbose_name='id from ANTACs DB'),
        ),
        migrations.AlterField(
            model_name='company',
            name='authority',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_ocean.Authority', verbose_name='registration authority'),
        ),
        migrations.AlterField(
            model_name='company',
            name='authorized_capital',
            field=models.FloatField(null=True, verbose_name='share capital'),
        ),
        migrations.AlterField(
            model_name='company',
            name='boss',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='CEO'),
        ),
        migrations.AlterField(
            model_name='company',
            name='bylaw',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='business_register.Bylaw', verbose_name='charter'),
        ),
        migrations.AlterField(
            model_name='company',
            name='code',
            field=models.CharField(db_index=True, max_length=510, verbose_name='our code'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='business_register.CompanyType', verbose_name='company type'),
        ),
        migrations.AlterField(
            model_name='company',
            name='contact_info',
            field=models.CharField(max_length=310, null=True, verbose_name='contacts'),
        ),
        migrations.AlterField(
            model_name='company',
            name='country',
            field=models.ForeignKey(max_length=60, null=True, on_delete=django.db.models.deletion.CASCADE, to='location_register.Country', verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='company',
            name='edrpou',
            field=models.CharField(db_index=True, max_length=260, null=True, verbose_name='number'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=500, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='business_register.Company', verbose_name='parent company'),
        ),
        migrations.AlterField(
            model_name='company',
            name='registration_date',
            field=models.DateField(null=True, verbose_name='registration date'),
        ),
        migrations.AlterField(
            model_name='company',
            name='registration_info',
            field=models.CharField(max_length=450, null=True, verbose_name='registration info'),
        ),
        migrations.AlterField(
            model_name='company',
            name='short_name',
            field=models.CharField(max_length=500, null=True, verbose_name='short name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='source',
            field=models.CharField(blank=True, choices=[('ukr', 'The United State Register of Legal Entities, Individual Entrepreneurs and Public Organizations of Ukraine'), ('gb', 'Company House (UK companies` register)'), ('antac', 'ANTAC')], db_index=True, default=None, max_length=5, null=True, verbose_name='source'),
        ),
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_ocean.Status', verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='companylinkwithpep',
            name='category',
            field=models.CharField(blank=True, choices=[('bank_customer', 'Bank client'), ('owner', 'Owner'), ('by_position', 'By position'), ('manager', 'Manager'), ('other', 'Other')], default=None, max_length=15, null=True, verbose_name='connection`s category'),
        ),
        migrations.AlterField(
            model_name='companylinkwithpep',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_with_peps', to='business_register.Company', verbose_name='associated with PEP company'),
        ),
        migrations.AlterField(
            model_name='companylinkwithpep',
            name='confirmation_date',
            field=models.CharField(max_length=12, null=True, verbose_name='connection`s confirmation date'),
        ),
        migrations.AlterField(
            model_name='companylinkwithpep',
            name='end_date',
            field=models.CharField(max_length=12, null=True, verbose_name='connection`s end date'),
        ),
        migrations.AlterField(
            model_name='companylinkwithpep',
            name='pep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_companies', to='business_register.Pep', verbose_name='associated with company PEP'),
        ),
        migrations.AlterField(
            model_name='companylinkwithpep',
            name='relationship_type',
            field=models.CharField(max_length=550, null=True, verbose_name='connection`s type'),
        ),
        migrations.AlterField(
            model_name='companylinkwithpep',
            name='start_date',
            field=models.CharField(max_length=12, null=True, verbose_name='connection`s start date'),
        ),
        migrations.AlterField(
            model_name='companytokved',
            name='kved',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_register.Kved', verbose_name='NACE'),
        ),
        migrations.AlterField(
            model_name='companytokved',
            name='primary_kved',
            field=models.BooleanField(default=False, verbose_name='declared as primary'),
        ),
        migrations.AlterField(
            model_name='companytopredecessor',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predecessors', to='business_register.Company'),
        ),
        migrations.AlterField(
            model_name='companytype',
            name='name',
            field=models.CharField(max_length=270, null=True, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='companytype',
            name='name_eng',
            field=models.CharField(max_length=270, null=True, unique=True, verbose_name='name in Company House (UK companies` register)'),
        ),
        migrations.AlterField(
            model_name='exchangedatacompany',
            name='authority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_ocean.Authority', verbose_name='registration authority'),
        ),
        migrations.AlterField(
            model_name='exchangedatafop',
            name='authority',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_ocean.Authority', verbose_name='registration authority'),
        ),
        migrations.AlterField(
            model_name='exchangedatafop',
            name='fop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_data', to='business_register.Fop', verbose_name='entrepreneur'),
        ),
        migrations.AlterField(
            model_name='exchangedatafop',
            name='taxpayer_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_ocean.TaxpayerType', verbose_name='taxpayer type'),
        ),
        migrations.AlterField(
            model_name='fop',
            name='address',
            field=models.CharField(max_length=500, null=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='fop',
            name='authority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_ocean.Authority', verbose_name='registration authority'),
        ),
        migrations.AlterField(
            model_name='fop',
            name='code',
            field=models.CharField(db_index=True, max_length=675, verbose_name='our code'),
        ),
        migrations.AlterField(
            model_name='fop',
            name='contact_info',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='contacts'),
        ),
        migrations.AlterField(
            model_name='fop',
            name='fullname',
            field=models.CharField(max_length=175, verbose_name='full name'),
        ),
        migrations.AlterField(
            model_name='fop',
            name='registration_date',
            field=models.DateField(blank=True, null=True, verbose_name='registration date'),
        ),
        migrations.AlterField(
            model_name='fop',
            name='registration_info',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='registration info'),
        ),
        migrations.AlterField(
            model_name='fop',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_ocean.Status', verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='fop',
            name='terminated_info',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='termination info'),
        ),
        migrations.AlterField(
            model_name='fop',
            name='termination_cancel_info',
            field=models.CharField(blank=True, max_length=275, null=True, verbose_name='termination cancellation info'),
        ),
        migrations.AlterField(
            model_name='fop',
            name='termination_date',
            field=models.DateField(blank=True, null=True, verbose_name='termination date'),
        ),
        migrations.AlterField(
            model_name='foptokved',
            name='fop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kveds', to='business_register.Fop', verbose_name='entrepreneur'),
        ),
        migrations.AlterField(
            model_name='foptokved',
            name='kved',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_register.Kved', verbose_name='NACE'),
        ),
        migrations.AlterField(
            model_name='foptokved',
            name='primary_kved',
            field=models.BooleanField(default=False, verbose_name='declared as primary'),
        ),
        migrations.AlterField(
            model_name='founder',
            name='address',
            field=models.CharField(blank=True, default='', max_length=2015, null=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='founder',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='founders', to='business_register.Company', verbose_name='owner'),
        ),
        migrations.AlterField(
            model_name='founder',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='founder',
            name='edrpou',
            field=models.CharField(blank=True, db_index=True, default='', max_length=9, null=True, verbose_name='number'),
        ),
        migrations.AlterField(
            model_name='founder',
            name='equity',
            field=models.FloatField(blank=True, null=True, verbose_name='equity'),
        ),
        migrations.AlterField(
            model_name='founder',
            name='info',
            field=models.CharField(max_length=2015, verbose_name='info'),
        ),
        migrations.AlterField(
            model_name='founder',
            name='info_additional',
            field=models.CharField(max_length=2015, null=True, verbose_name='additional info'),
        ),
        migrations.AlterField(
            model_name='founder',
            name='info_beneficiary',
            field=models.CharField(max_length=2015, null=True, verbose_name='beneficiary info'),
        ),
        migrations.AlterField(
            model_name='founder',
            name='is_beneficiary',
            field=models.BooleanField(blank=True, default=False, verbose_name='is beneficiary'),
        ),
        migrations.AlterField(
            model_name='founder',
            name='is_founder',
            field=models.BooleanField(blank=True, default=False, verbose_name='is owner'),
        ),
        migrations.AlterField(
            model_name='founder',
            name='name',
            field=models.TextField(db_index=True, verbose_name='name or full name'),
        ),
        migrations.AlterField(
            model_name='historicalassignee',
            name='edrpou',
            field=models.CharField(max_length=11, null=True, verbose_name='number'),
        ),
        migrations.AlterField(
            model_name='historicalassignee',
            name='name',
            field=models.CharField(max_length=610, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='historicalbancruptcyreadjustment',
            name='reason',
            field=models.TextField(null=True, verbose_name='reason'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='address',
            field=models.CharField(max_length=1000, null=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='antac_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, default=None, null=True, verbose_name='id from ANTACs DB'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='authority',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='data_ocean.Authority', verbose_name='registration authority'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='authorized_capital',
            field=models.FloatField(null=True, verbose_name='share capital'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='boss',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='CEO'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='bylaw',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='business_register.Bylaw', verbose_name='charter'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='code',
            field=models.CharField(db_index=True, max_length=510, verbose_name='our code'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='company_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='business_register.CompanyType', verbose_name='company type'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='contact_info',
            field=models.CharField(max_length=310, null=True, verbose_name='contacts'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='country',
            field=models.ForeignKey(blank=True, db_constraint=False, max_length=60, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='location_register.Country', verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='edrpou',
            field=models.CharField(db_index=True, max_length=260, null=True, verbose_name='number'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='name',
            field=models.CharField(max_length=500, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='parent',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='business_register.Company', verbose_name='parent company'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='registration_date',
            field=models.DateField(null=True, verbose_name='registration date'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='registration_info',
            field=models.CharField(max_length=450, null=True, verbose_name='registration info'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='short_name',
            field=models.CharField(max_length=500, null=True, verbose_name='short name'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='source',
            field=models.CharField(blank=True, choices=[('ukr', 'The United State Register of Legal Entities, Individual Entrepreneurs and Public Organizations of Ukraine'), ('gb', 'Company House (UK companies` register)'), ('antac', 'ANTAC')], db_index=True, default=None, max_length=5, null=True, verbose_name='source'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='status',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='data_ocean.Status', verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='historicalcompanytokved',
            name='kved',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='business_register.Kved', verbose_name='NACE'),
        ),
        migrations.AlterField(
            model_name='historicalcompanytokved',
            name='primary_kved',
            field=models.BooleanField(default=False, verbose_name='declared as primary'),
        ),
        migrations.AlterField(
            model_name='historicalcompanytopredecessor',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='business_register.Company'),
        ),
        migrations.AlterField(
            model_name='historicalexchangedatacompany',
            name='authority',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='data_ocean.Authority', verbose_name='registration authority'),
        ),
        migrations.AlterField(
            model_name='historicalfop',
            name='address',
            field=models.CharField(max_length=500, null=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='historicalfop',
            name='authority',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='data_ocean.Authority', verbose_name='registration authority'),
        ),
        migrations.AlterField(
            model_name='historicalfop',
            name='code',
            field=models.CharField(db_index=True, max_length=675, verbose_name='our code'),
        ),
        migrations.AlterField(
            model_name='historicalfop',
            name='contact_info',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='contacts'),
        ),
        migrations.AlterField(
            model_name='historicalfop',
            name='fullname',
            field=models.CharField(max_length=175, verbose_name='full name'),
        ),
        migrations.AlterField(
            model_name='historicalfop',
            name='registration_date',
            field=models.DateField(blank=True, null=True, verbose_name='registration date'),
        ),
        migrations.AlterField(
            model_name='historicalfop',
            name='registration_info',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='registration info'),
        ),
        migrations.AlterField(
            model_name='historicalfop',
            name='status',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='data_ocean.Status', verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='historicalfop',
            name='terminated_info',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='termination info'),
        ),
        migrations.AlterField(
            model_name='historicalfop',
            name='termination_cancel_info',
            field=models.CharField(blank=True, max_length=275, null=True, verbose_name='termination cancellation info'),
        ),
        migrations.AlterField(
            model_name='historicalfop',
            name='termination_date',
            field=models.DateField(blank=True, null=True, verbose_name='termination date'),
        ),
        migrations.AlterField(
            model_name='historicalfounder',
            name='address',
            field=models.CharField(blank=True, default='', max_length=2015, null=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='historicalfounder',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='business_register.Company', verbose_name='owner'),
        ),
        migrations.AlterField(
            model_name='historicalfounder',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='historicalfounder',
            name='edrpou',
            field=models.CharField(blank=True, db_index=True, default='', max_length=9, null=True, verbose_name='number'),
        ),
        migrations.AlterField(
            model_name='historicalfounder',
            name='equity',
            field=models.FloatField(blank=True, null=True, verbose_name='equity'),
        ),
        migrations.AlterField(
            model_name='historicalfounder',
            name='info',
            field=models.CharField(max_length=2015, verbose_name='info'),
        ),
        migrations.AlterField(
            model_name='historicalfounder',
            name='info_additional',
            field=models.CharField(max_length=2015, null=True, verbose_name='additional info'),
        ),
        migrations.AlterField(
            model_name='historicalfounder',
            name='info_beneficiary',
            field=models.CharField(max_length=2015, null=True, verbose_name='beneficiary info'),
        ),
        migrations.AlterField(
            model_name='historicalfounder',
            name='is_beneficiary',
            field=models.BooleanField(blank=True, default=False, verbose_name='is beneficiary'),
        ),
        migrations.AlterField(
            model_name='historicalfounder',
            name='is_founder',
            field=models.BooleanField(blank=True, default=False, verbose_name='is owner'),
        ),
        migrations.AlterField(
            model_name='historicalfounder',
            name='name',
            field=models.TextField(db_index=True, verbose_name='name or full name'),
        ),
        migrations.AlterField(
            model_name='historicalpep',
            name='assets_info',
            field=models.TextField(null=True, verbose_name='assets info'),
        ),
        migrations.AlterField(
            model_name='historicalpep',
            name='criminal_proceedings',
            field=models.TextField(null=True, verbose_name='known criminal proceedings against the person'),
        ),
        migrations.AlterField(
            model_name='historicalpep',
            name='criminal_record',
            field=models.TextField(null=True, verbose_name='known sentences against the person'),
        ),
        migrations.AlterField(
            model_name='historicalpep',
            name='date_of_birth',
            field=models.CharField(max_length=10, null=True, verbose_name='date of birth'),
        ),
        migrations.AlterField(
            model_name='historicalpep',
            name='first_name',
            field=models.CharField(max_length=20, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='historicalpep',
            name='fullname',
            field=models.CharField(db_index=True, max_length=75, verbose_name='full name'),
        ),
        migrations.AlterField(
            model_name='historicalpep',
            name='fullname_transcriptions_eng',
            field=models.TextField(verbose_name='options for writing the full name'),
        ),
        migrations.AlterField(
            model_name='historicalpep',
            name='info',
            field=models.TextField(null=True, verbose_name='additional info'),
        ),
        migrations.AlterField(
            model_name='historicalpep',
            name='is_dead',
            field=models.BooleanField(default=False, verbose_name='is_dead'),
        ),
        migrations.AlterField(
            model_name='historicalpep',
            name='is_pep',
            field=models.BooleanField(default=True, verbose_name='is pep'),
        ),
        migrations.AlterField(
            model_name='historicalpep',
            name='last_employer',
            field=models.CharField(max_length=512, null=True, verbose_name='last office'),
        ),
        migrations.AlterField(
            model_name='historicalpep',
            name='last_job_title',
            field=models.CharField(max_length=340, null=True, verbose_name='last position'),
        ),
        migrations.AlterField(
            model_name='historicalpep',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='surname'),
        ),
        migrations.AlterField(
            model_name='historicalpep',
            name='middle_name',
            field=models.CharField(max_length=25, verbose_name='middle name'),
        ),
        migrations.AlterField(
            model_name='historicalpep',
            name='pep_type',
            field=models.CharField(blank=True, choices=[('national PEP', 'National politically exposed person'), ('foreign PEP', 'Foreign politically exposed person'), ('PEP with political functions in international organization', 'Politically exposed person, having political functions in international organization'), ('associated person with PEP', 'Associated person'), ('member of PEP`s family', 'Family member')], max_length=60, null=True, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='historicalpep',
            name='place_of_birth',
            field=models.CharField(max_length=100, null=True, verbose_name='place of birth'),
        ),
        migrations.AlterField(
            model_name='historicalpep',
            name='reason_of_termination',
            field=models.CharField(blank=True, choices=[('died', 'Is dead'), ('resigned', 'Resigned or term ended'), ('linked pep died', 'Associated PEP is dead'), ('linked pep resigned', 'Associated person is no more PEP'), ('legislation changed', 'Legislation was changed'), ('company status changed', 'Company is no more state')], max_length=125, null=True, verbose_name='reason of termination'),
        ),
        migrations.AlterField(
            model_name='historicalpep',
            name='sanctions',
            field=models.TextField(null=True, verbose_name='known sanctions against the person'),
        ),
        migrations.AlterField(
            model_name='historicalpep',
            name='source_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='id from ANTACs DB'),
        ),
        migrations.AlterField(
            model_name='historicalpep',
            name='termination_date',
            field=models.CharField(max_length=10, null=True, verbose_name='PEP status termination date '),
        ),
        migrations.AlterField(
            model_name='historicalpep',
            name='wanted',
            field=models.TextField(null=True, verbose_name='wanted'),
        ),
        migrations.AlterField(
            model_name='historicalsigner',
            name='name',
            field=models.CharField(max_length=390, null=True, verbose_name='full name'),
        ),
        migrations.AlterField(
            model_name='historicalterminationstarted',
            name='reason',
            field=models.TextField(null=True, verbose_name='reason'),
        ),
        migrations.AlterField(
            model_name='kved',
            name='code',
            field=models.CharField(db_index=True, max_length=10, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='kved',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_register.KvedDivision', verbose_name='division'),
        ),
        migrations.AlterField(
            model_name='kved',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_register.KvedGroup', verbose_name='group'),
        ),
        migrations.AlterField(
            model_name='kved',
            name='is_valid',
            field=models.BooleanField(default=True, verbose_name='is valid'),
        ),
        migrations.AlterField(
            model_name='kved',
            name='name',
            field=models.CharField(max_length=500, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='kved',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_register.KvedSection', verbose_name='section'),
        ),
        migrations.AlterField(
            model_name='kveddivision',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='kveddivision',
            name='name',
            field=models.CharField(max_length=500, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='kveddivision',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_register.KvedSection', verbose_name='section'),
        ),
        migrations.AlterField(
            model_name='kvedgroup',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='kvedgroup',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_register.KvedDivision', verbose_name='division'),
        ),
        migrations.AlterField(
            model_name='kvedgroup',
            name='name',
            field=models.CharField(max_length=500, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='kvedgroup',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_register.KvedSection', verbose_name='section'),
        ),
        migrations.AlterField(
            model_name='kvedsection',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='kvedsection',
            name='name',
            field=models.CharField(max_length=500, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='pep',
            name='assets_info',
            field=models.TextField(null=True, verbose_name='assets info'),
        ),
        migrations.AlterField(
            model_name='pep',
            name='criminal_proceedings',
            field=models.TextField(null=True, verbose_name='known criminal proceedings against the person'),
        ),
        migrations.AlterField(
            model_name='pep',
            name='criminal_record',
            field=models.TextField(null=True, verbose_name='known sentences against the person'),
        ),
        migrations.AlterField(
            model_name='pep',
            name='date_of_birth',
            field=models.CharField(max_length=10, null=True, verbose_name='date of birth'),
        ),
        migrations.AlterField(
            model_name='pep',
            name='first_name',
            field=models.CharField(max_length=20, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='pep',
            name='fullname',
            field=models.CharField(db_index=True, max_length=75, verbose_name='full name'),
        ),
        migrations.AlterField(
            model_name='pep',
            name='fullname_transcriptions_eng',
            field=models.TextField(verbose_name='options for writing the full name'),
        ),
        migrations.AlterField(
            model_name='pep',
            name='info',
            field=models.TextField(null=True, verbose_name='additional info'),
        ),
        migrations.AlterField(
            model_name='pep',
            name='is_dead',
            field=models.BooleanField(default=False, verbose_name='is_dead'),
        ),
        migrations.AlterField(
            model_name='pep',
            name='is_pep',
            field=models.BooleanField(default=True, verbose_name='is pep'),
        ),
        migrations.AlterField(
            model_name='pep',
            name='last_employer',
            field=models.CharField(max_length=512, null=True, verbose_name='last office'),
        ),
        migrations.AlterField(
            model_name='pep',
            name='last_job_title',
            field=models.CharField(max_length=340, null=True, verbose_name='last position'),
        ),
        migrations.AlterField(
            model_name='pep',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='surname'),
        ),
        migrations.AlterField(
            model_name='pep',
            name='middle_name',
            field=models.CharField(max_length=25, verbose_name='middle name'),
        ),
        migrations.AlterField(
            model_name='pep',
            name='pep_type',
            field=models.CharField(blank=True, choices=[('national PEP', 'National politically exposed person'), ('foreign PEP', 'Foreign politically exposed person'), ('PEP with political functions in international organization', 'Politically exposed person, having political functions in international organization'), ('associated person with PEP', 'Associated person'), ('member of PEP`s family', 'Family member')], max_length=60, null=True, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='pep',
            name='place_of_birth',
            field=models.CharField(max_length=100, null=True, verbose_name='place of birth'),
        ),
        migrations.AlterField(
            model_name='pep',
            name='reason_of_termination',
            field=models.CharField(blank=True, choices=[('died', 'Is dead'), ('resigned', 'Resigned or term ended'), ('linked pep died', 'Associated PEP is dead'), ('linked pep resigned', 'Associated person is no more PEP'), ('legislation changed', 'Legislation was changed'), ('company status changed', 'Company is no more state')], max_length=125, null=True, verbose_name='reason of termination'),
        ),
        migrations.AlterField(
            model_name='pep',
            name='related_persons',
            field=models.ManyToManyField(related_name='_pep_related_persons_+', through='business_register.RelatedPersonsLink', to='business_register.Pep', verbose_name='associated persons'),
        ),
        migrations.AlterField(
            model_name='pep',
            name='sanctions',
            field=models.TextField(null=True, verbose_name='known sanctions against the person'),
        ),
        migrations.AlterField(
            model_name='pep',
            name='source_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='id from ANTACs DB'),
        ),
        migrations.AlterField(
            model_name='pep',
            name='termination_date',
            field=models.CharField(max_length=10, null=True, verbose_name='PEP status termination date '),
        ),
        migrations.AlterField(
            model_name='pep',
            name='wanted',
            field=models.TextField(null=True, verbose_name='wanted'),
        ),
        migrations.AlterField(
            model_name='predecessor',
            name='edrpou',
            field=models.CharField(max_length=405, null=True, verbose_name='number'),
        ),
        migrations.AlterField(
            model_name='predecessor',
            name='name',
            field=models.CharField(max_length=500, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='relatedpersonslink',
            name='category',
            field=models.CharField(blank=True, choices=[('family', 'Family'), ('business', 'Business'), ('personal', 'Personal')], max_length=20, null=True, verbose_name='connection`s category'),
        ),
        migrations.AlterField(
            model_name='relatedpersonslink',
            name='confirmation_date',
            field=models.CharField(max_length=12, null=True, verbose_name='connection`s confirmation date'),
        ),
        migrations.AlterField(
            model_name='relatedpersonslink',
            name='end_date',
            field=models.CharField(max_length=12, null=True, verbose_name='connection`s end date'),
        ),
        migrations.AlterField(
            model_name='relatedpersonslink',
            name='from_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_person_links', to='business_register.Pep', verbose_name='associated person'),
        ),
        migrations.AlterField(
            model_name='relatedpersonslink',
            name='from_person_relationship_type',
            field=models.CharField(max_length=90, null=True, verbose_name='connection`s type'),
        ),
        migrations.AlterField(
            model_name='relatedpersonslink',
            name='start_date',
            field=models.CharField(max_length=12, null=True, verbose_name='connection`s start date'),
        ),
        migrations.AlterField(
            model_name='relatedpersonslink',
            name='to_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_person_links', to='business_register.Pep', verbose_name='another associated person'),
        ),
        migrations.AlterField(
            model_name='relatedpersonslink',
            name='to_person_relationship_type',
            field=models.CharField(max_length=90, null=True, verbose_name='another person`s connection`s type'),
        ),
        migrations.AlterField(
            model_name='signer',
            name='name',
            field=models.CharField(max_length=390, null=True, verbose_name='full name'),
        ),
        migrations.AlterField(
            model_name='terminationstarted',
            name='reason',
            field=models.TextField(null=True, verbose_name='reason'),
        ),
        migrations.DeleteModel(
            name='PepDeclaration',
        ),
        migrations.DeleteModel(
            name='PepRelatedCountry',
        ),
    ]
