# Generated by Django 3.0.7 on 2021-02-24 15:10
from datetime import datetime

from django.db import migrations


def parse_date_of_birth(date_of_birth):
    if isinstance(date_of_birth, str):
        date_of_birth = date_of_birth.strip()
        if date_of_birth:
            try:
                date_of_birth = datetime.strptime(
                    date_of_birth.strip(), '%d.%m.%Y',
                ).strftime('%Y-%m-%d')
            except ValueError:
                pass
        else:
            date_of_birth = None
    else:
        date_of_birth = None
    return date_of_birth


def update_pep_fields(apps, schema):
    Pep = apps.get_model('business_register', 'Pep')
    for pep in Pep.objects.all():
        pep.date_of_birth = parse_date_of_birth(pep.date_of_birth)
        pep.fullname = f'{pep.last_name} {pep.first_name} {pep.middle_name}'
        pep.save(update_fields=['date_of_birth', 'fullname'])


class Migration(migrations.Migration):

    dependencies = [
        ('business_register', '0065_auto_20210224_1211'),
    ]

    operations = [
        migrations.RunPython(
            code=update_pep_fields,
            reverse_code=migrations.RunPython.noop,
        )
    ]
