# Generated by Django 3.0.7 on 2021-03-05 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_register', '0066_auto_20210224_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When the object was created. In YYYY-MM-DDTHH:mm:ss.SSSSSSZ format.'),
        ),
        migrations.AlterField(
            model_name='assignee',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When the object was update. In YYYY-MM-DDTHH:mm:ss.SSSSSSZ format.', null=True),
        ),
        migrations.AlterField(
            model_name='bancruptcyreadjustment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When the object was created. In YYYY-MM-DDTHH:mm:ss.SSSSSSZ format.'),
        ),
        migrations.AlterField(
            model_name='bancruptcyreadjustment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When the object was update. In YYYY-MM-DDTHH:mm:ss.SSSSSSZ format.', null=True),
        ),
        migrations.AlterField(
            model_name='bylaw',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When the object was created. In YYYY-MM-DDTHH:mm:ss.SSSSSSZ format.'),
        ),
        migrations.AlterField(
            model_name='bylaw',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When the object was update. In YYYY-MM-DDTHH:mm:ss.SSSSSSZ format.', null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When the object was created. In YYYY-MM-DDTHH:mm:ss.SSSSSSZ format.'),
        ),
        migrations.AlterField(
            model_name='company',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When the object was update. In YYYY-MM-DDTHH:mm:ss.SSSSSSZ format.', null=True),
        ),
        migrations.AlterField(
            model_name='companydetail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When the object was created. In YYYY-MM-DDTHH:mm:ss.SSSSSSZ format.'),
        ),
        migrations.AlterField(
            model_name='companydetail',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When the object was update. In YYYY-MM-DDTHH:mm:ss.SSSSSSZ format.', null=True),
        ),
        migrations.AlterField(
            model_name='companylinkwithpep',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When the object was created. In YYYY-MM-DDTHH:mm:ss.SSSSSSZ format.'),
        ),
        migrations.AlterField(
            model_name='companylinkwithpep',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When the object was update. In YYYY-MM-DDTHH:mm:ss.SSSSSSZ format.', null=True),
        ),
        migrations.AlterField(
            model_name='companytokved',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When the object was created. In YYYY-MM-DDTHH:mm:ss.SSSSSSZ format.'),
        ),
        migrations.AlterField(
            model_name='companytokved',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When the object was update. In YYYY-MM-DDTHH:mm:ss.SSSSSSZ format.', null=True),
        ),
        migrations.AlterField(
            model_name='companytopredecessor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When the object was created. In YYYY-MM-DDTHH:mm:ss.SSSSSSZ format.'),
        ),
        migrations.AlterField(
            model_name='companytopredecessor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When the object was update. In YYYY-MM-DDTHH:mm:ss.SSSSSSZ format.', null=True),
        ),
        migrations.AlterField(
            model_name='companytype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When the object was created. In YYYY-MM-DDTHH:mm:ss.SSSSSSZ format.'),
        ),
        migrations.AlterField(
            model_name='companytype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When the object was update. In YYYY-MM-DDTHH:mm:ss.SSSSSSZ format.', null=True),
        ),
        migrations.AlterField(
            model_name='exchangedatacompany',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When the object was created. In YYYY-MM-DDTHH:mm:ss.SSSSSSZ format.'),
        ),
        migrations.AlterField(
            model_name='exchangedatacompany',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When the object was update. In YYYY-MM-DDTHH:mm:ss.SSSSSSZ format.', null=True),
        ),
        migrations.AlterField(
            model_name='exchangedatafop',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When the object was created. In YYYY-MM-DDTHH:mm:ss.SSSSSSZ format.'),
        ),
        migrations.AlterField(
            model_name='exchangedatafop',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When the object was update. In YYYY-MM-DDTHH:mm:ss.SSSSSSZ format.', null=True),
        ),
        migrations.AlterField(
            model_name='fop',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When the object was created. In YYYY-MM-DDTHH:mm:ss.SSSSSSZ format.'),
        ),
        migrations.AlterField(
            model_name='fop',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When the object was update. In YYYY-MM-DDTHH:mm:ss.SSSSSSZ format.', null=True),
        ),
        migrations.AlterField(
            model_name='foptokved',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When the object was created. In YYYY-MM-DDTHH:mm:ss.SSSSSSZ format.'),
        ),
        migrations.AlterField(
            model_name='foptokved',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When the object was update. In YYYY-MM-DDTHH:mm:ss.SSSSSSZ format.', null=True),
        ),
        migrations.AlterField(
            model_name='founder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When the object was created. In YYYY-MM-DDTHH:mm:ss.SSSSSSZ format.'),
        ),
        migrations.AlterField(
            model_name='founder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When the object was update. In YYYY-MM-DDTHH:mm:ss.SSSSSSZ format.', null=True),
        ),
        migrations.AlterField(
            model_name='historicalassignee',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='When the object was created. In YYYY-MM-DDTHH:mm:ss.SSSSSSZ format.'),
        ),
        migrations.AlterField(
            model_name='historicalassignee',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='When the object was update. In YYYY-MM-DDTHH:mm:ss.SSSSSSZ format.', null=True),
        ),
        migrations.AlterField(
            model_name='historicalbancruptcyreadjustment',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='When the object was created. In YYYY-MM-DDTHH:mm:ss.SSSSSSZ format.'),
        ),
        migrations.AlterField(
            model_name='historicalbancruptcyreadjustment',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='When the object was update. In YYYY-MM-DDTHH:mm:ss.SSSSSSZ format.', null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='When the object was created. In YYYY-MM-DDTHH:mm:ss.SSSSSSZ format.'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='When the object was update. In YYYY-MM-DDTHH:mm:ss.SSSSSSZ format.', null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompanydetail',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='When the object was created. In YYYY-MM-DDTHH:mm:ss.SSSSSSZ format.'),
        ),
        migrations.AlterField(
            model_name='historicalcompanydetail',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='When the object was update. In YYYY-MM-DDTHH:mm:ss.SSSSSSZ format.', null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompanytokved',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='When the object was created. In YYYY-MM-DDTHH:mm:ss.SSSSSSZ format.'),
        ),
        migrations.AlterField(
            model_name='historicalcompanytokved',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='When the object was update. In YYYY-MM-DDTHH:mm:ss.SSSSSSZ format.', null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompanytopredecessor',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='When the object was created. In YYYY-MM-DDTHH:mm:ss.SSSSSSZ format.'),
        ),
        migrations.AlterField(
            model_name='historicalcompanytopredecessor',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='When the object was update. In YYYY-MM-DDTHH:mm:ss.SSSSSSZ format.', null=True),
        ),
        migrations.AlterField(
            model_name='historicalexchangedatacompany',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='When the object was created. In YYYY-MM-DDTHH:mm:ss.SSSSSSZ format.'),
        ),
        migrations.AlterField(
            model_name='historicalexchangedatacompany',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='When the object was update. In YYYY-MM-DDTHH:mm:ss.SSSSSSZ format.', null=True),
        ),
        migrations.AlterField(
            model_name='historicalfop',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='When the object was created. In YYYY-MM-DDTHH:mm:ss.SSSSSSZ format.'),
        ),
        migrations.AlterField(
            model_name='historicalfop',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='When the object was update. In YYYY-MM-DDTHH:mm:ss.SSSSSSZ format.', null=True),
        ),
        migrations.AlterField(
            model_name='historicalfounder',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='When the object was created. In YYYY-MM-DDTHH:mm:ss.SSSSSSZ format.'),
        ),
        migrations.AlterField(
            model_name='historicalfounder',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='When the object was update. In YYYY-MM-DDTHH:mm:ss.SSSSSSZ format.', null=True),
        ),
        migrations.AlterField(
            model_name='historicalpep',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='When the object was created. In YYYY-MM-DDTHH:mm:ss.SSSSSSZ format.'),
        ),
        migrations.AlterField(
            model_name='historicalpep',
            name='criminal_proceedings',
            field=models.TextField(null=True, verbose_name='known criminal proceedings against the person'),
        ),
        migrations.AlterField(
            model_name='historicalpep',
            name='fullname',
            field=models.CharField(db_index=True, help_text='Full name "last name first name middle name" in Ukrainian.', max_length=75, verbose_name='full name'),
        ),
        migrations.AlterField(
            model_name='historicalpep',
            name='pep_type',
            field=models.CharField(blank=True, choices=[('national PEP', 'National politically exposed person'), ('foreign PEP', 'Foreign politically exposed person'), ('PEP with political functions in international organization', 'Politically exposed person, having political functions in international organization'), ('associated person with PEP', 'Associated person'), ('member of PEP`s family', 'Family member')], db_index=True, help_text='Type of politically exposed person. Can be national politically exposed person, foreign politically exposed person,  politically exposed person, having political functions in international organization, associated person or family member.', max_length=60, null=True, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='historicalpep',
            name='termination_date',
            field=models.CharField(max_length=10, null=True, verbose_name='PEP status termination date '),
        ),
        migrations.AlterField(
            model_name='historicalpep',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='When the object was update. In YYYY-MM-DDTHH:mm:ss.SSSSSSZ format.', null=True),
        ),
        migrations.AlterField(
            model_name='historicalsigner',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='When the object was created. In YYYY-MM-DDTHH:mm:ss.SSSSSSZ format.'),
        ),
        migrations.AlterField(
            model_name='historicalsigner',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='When the object was update. In YYYY-MM-DDTHH:mm:ss.SSSSSSZ format.', null=True),
        ),
        migrations.AlterField(
            model_name='historicalterminationstarted',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='When the object was created. In YYYY-MM-DDTHH:mm:ss.SSSSSSZ format.'),
        ),
        migrations.AlterField(
            model_name='historicalterminationstarted',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='When the object was update. In YYYY-MM-DDTHH:mm:ss.SSSSSSZ format.', null=True),
        ),
        migrations.AlterField(
            model_name='kved',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When the object was created. In YYYY-MM-DDTHH:mm:ss.SSSSSSZ format.'),
        ),
        migrations.AlterField(
            model_name='kved',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When the object was update. In YYYY-MM-DDTHH:mm:ss.SSSSSSZ format.', null=True),
        ),
        migrations.AlterField(
            model_name='kveddivision',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When the object was created. In YYYY-MM-DDTHH:mm:ss.SSSSSSZ format.'),
        ),
        migrations.AlterField(
            model_name='kveddivision',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When the object was update. In YYYY-MM-DDTHH:mm:ss.SSSSSSZ format.', null=True),
        ),
        migrations.AlterField(
            model_name='kvedgroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When the object was created. In YYYY-MM-DDTHH:mm:ss.SSSSSSZ format.'),
        ),
        migrations.AlterField(
            model_name='kvedgroup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When the object was update. In YYYY-MM-DDTHH:mm:ss.SSSSSSZ format.', null=True),
        ),
        migrations.AlterField(
            model_name='kvedsection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When the object was created. In YYYY-MM-DDTHH:mm:ss.SSSSSSZ format.'),
        ),
        migrations.AlterField(
            model_name='kvedsection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When the object was update. In YYYY-MM-DDTHH:mm:ss.SSSSSSZ format.', null=True),
        ),
        migrations.AlterField(
            model_name='pep',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When the object was created. In YYYY-MM-DDTHH:mm:ss.SSSSSSZ format.'),
        ),
        migrations.AlterField(
            model_name='pep',
            name='criminal_proceedings',
            field=models.TextField(null=True, verbose_name='known criminal proceedings against the person'),
        ),
        migrations.AlterField(
            model_name='pep',
            name='fullname',
            field=models.CharField(db_index=True, help_text='Full name "last name first name middle name" in Ukrainian.', max_length=75, verbose_name='full name'),
        ),
        migrations.AlterField(
            model_name='pep',
            name='pep_type',
            field=models.CharField(blank=True, choices=[('national PEP', 'National politically exposed person'), ('foreign PEP', 'Foreign politically exposed person'), ('PEP with political functions in international organization', 'Politically exposed person, having political functions in international organization'), ('associated person with PEP', 'Associated person'), ('member of PEP`s family', 'Family member')], db_index=True, help_text='Type of politically exposed person. Can be national politically exposed person, foreign politically exposed person,  politically exposed person, having political functions in international organization, associated person or family member.', max_length=60, null=True, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='pep',
            name='termination_date',
            field=models.CharField(max_length=10, null=True, verbose_name='PEP status termination date '),
        ),
        migrations.AlterField(
            model_name='pep',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When the object was update. In YYYY-MM-DDTHH:mm:ss.SSSSSSZ format.', null=True),
        ),
        migrations.AlterField(
            model_name='predecessor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When the object was created. In YYYY-MM-DDTHH:mm:ss.SSSSSSZ format.'),
        ),
        migrations.AlterField(
            model_name='predecessor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When the object was update. In YYYY-MM-DDTHH:mm:ss.SSSSSSZ format.', null=True),
        ),
        migrations.AlterField(
            model_name='relatedpersonslink',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When the object was created. In YYYY-MM-DDTHH:mm:ss.SSSSSSZ format.'),
        ),
        migrations.AlterField(
            model_name='relatedpersonslink',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When the object was update. In YYYY-MM-DDTHH:mm:ss.SSSSSSZ format.', null=True),
        ),
        migrations.AlterField(
            model_name='signer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When the object was created. In YYYY-MM-DDTHH:mm:ss.SSSSSSZ format.'),
        ),
        migrations.AlterField(
            model_name='signer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When the object was update. In YYYY-MM-DDTHH:mm:ss.SSSSSSZ format.', null=True),
        ),
        migrations.AlterField(
            model_name='terminationstarted',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When the object was created. In YYYY-MM-DDTHH:mm:ss.SSSSSSZ format.'),
        ),
        migrations.AlterField(
            model_name='terminationstarted',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When the object was update. In YYYY-MM-DDTHH:mm:ss.SSSSSSZ format.', null=True),
        ),
    ]
