# Generated by Django 3.0.7 on 2021-03-12 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location_register', '0019_auto_20210305_1702'),
        ('data_ocean', '0023_auto_20210312_1130'),
        ('business_register', '0067_auto_20210305_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignee',
            name='company',
            field=models.ForeignKey(help_text='Company is the legal successor', on_delete=django.db.models.deletion.CASCADE, related_name='assignees', to='business_register.Company', verbose_name='є правонаступником'),
        ),
        migrations.AlterField(
            model_name='assignee',
            name='edrpou',
            field=models.CharField(help_text='EDRPOU number as string', max_length=11, null=True, verbose_name='number'),
        ),
        migrations.AlterField(
            model_name='assignee',
            name='name',
            field=models.CharField(help_text='Assignee name in Ukrainian', max_length=610, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='bancruptcyreadjustment',
            name='company',
            field=models.ForeignKey(help_text='Bankruptcy readjustment', on_delete=django.db.models.deletion.CASCADE, related_name='bancruptcy_readjustment', to='business_register.Company'),
        ),
        migrations.AlterField(
            model_name='bancruptcyreadjustment',
            name='head_name',
            field=models.CharField(help_text='Head name', max_length=515, null=True),
        ),
        migrations.AlterField(
            model_name='bancruptcyreadjustment',
            name='op_date',
            field=models.DateField(help_text='Date of bankruptcy readjustment as string in YYYY-MM-DD format', null=True),
        ),
        migrations.AlterField(
            model_name='bancruptcyreadjustment',
            name='reason',
            field=models.TextField(help_text='Reason of bankruptcy', null=True, verbose_name='reason'),
        ),
        migrations.AlterField(
            model_name='bancruptcyreadjustment',
            name='sbj_state',
            field=models.CharField(help_text='Subject state', max_length=345, null=True),
        ),
        migrations.AlterField(
            model_name='bylaw',
            name='name',
            field=models.CharField(help_text='Company name in Ukrainian', max_length=320, null=True, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(help_text='Registration address in Ukrainian', max_length=1000, null=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='company',
            name='antac_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, default=None, help_text='ID from ANTACs DB', null=True, unique=True, verbose_name='id from ANTACs DB'),
        ),
        migrations.AlterField(
            model_name='company',
            name='authority',
            field=models.ForeignKey(help_text='Authorized state agency which register the company', null=True, on_delete=django.db.models.deletion.CASCADE, to='data_ocean.Authority', verbose_name='registration authority'),
        ),
        migrations.AlterField(
            model_name='company',
            name='authorized_capital',
            field=models.FloatField(help_text='Authorized capital as number', null=True, verbose_name='share capital'),
        ),
        migrations.AlterField(
            model_name='company',
            name='boss',
            field=models.CharField(blank=True, default='', help_text='CEO of the company', max_length=100, null=True, verbose_name='CEO'),
        ),
        migrations.AlterField(
            model_name='company',
            name='bylaw',
            field=models.ForeignKey(help_text='By law', null=True, on_delete=django.db.models.deletion.CASCADE, to='business_register.Bylaw', verbose_name='charter'),
        ),
        migrations.AlterField(
            model_name='company',
            name='code',
            field=models.CharField(db_index=True, help_text='Our code', max_length=510, verbose_name='our code'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_type',
            field=models.ForeignKey(help_text='Type of the company', null=True, on_delete=django.db.models.deletion.CASCADE, to='business_register.CompanyType', verbose_name='company type'),
        ),
        migrations.AlterField(
            model_name='company',
            name='contact_info',
            field=models.CharField(help_text='Info about contacts', max_length=310, null=True, verbose_name='contacts'),
        ),
        migrations.AlterField(
            model_name='company',
            name='country',
            field=models.ForeignKey(help_text='Country of origin', max_length=60, null=True, on_delete=django.db.models.deletion.CASCADE, to='location_register.Country', verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='company',
            name='edrpou',
            field=models.CharField(db_index=True, help_text='EDRPOU number as string', max_length=260, null=True, verbose_name='number'),
        ),
        migrations.AlterField(
            model_name='company',
            name='from_antac_only',
            field=models.BooleanField(help_text='If this field has "true" - Data provided by the Anti-Corruption Action Center.', null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(help_text='Company name in Ukrainian', max_length=500, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='parent',
            field=models.ForeignKey(help_text='Company that has a controlling interest in the company', null=True, on_delete=django.db.models.deletion.CASCADE, to='business_register.Company', verbose_name='parent company'),
        ),
        migrations.AlterField(
            model_name='company',
            name='registration_date',
            field=models.DateField(help_text='Registration date as string in YYYY-MM-DD format', null=True, verbose_name='registration date'),
        ),
        migrations.AlterField(
            model_name='company',
            name='registration_info',
            field=models.CharField(help_text='Registration info of the company', max_length=450, null=True, verbose_name='registration info'),
        ),
        migrations.AlterField(
            model_name='company',
            name='short_name',
            field=models.CharField(help_text='Short name of the company in Ukrainian', max_length=500, null=True, verbose_name='short name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='source',
            field=models.CharField(blank=True, choices=[('ukr', 'The United State Register of Legal Entities, Individual Entrepreneurs and Public Organizations of Ukraine'), ('gb', 'Company House (UK companies` register)'), ('antac', 'ANTAC')], db_index=True, default=None, help_text='Source', max_length=5, null=True, verbose_name='source'),
        ),
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.ForeignKey(help_text='Company legal status', null=True, on_delete=django.db.models.deletion.CASCADE, to='data_ocean.Status', verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='companydetail',
            name='company',
            field=models.ForeignKey(help_text='Company name', on_delete=django.db.models.deletion.CASCADE, related_name='company_detail', to='business_register.Company'),
        ),
        migrations.AlterField(
            model_name='companydetail',
            name='executive_power',
            field=models.CharField(help_text='Executive power of the company', max_length=390, null=True),
        ),
        migrations.AlterField(
            model_name='companydetail',
            name='founding_document_number',
            field=models.CharField(help_text='Founding document number as string', max_length=375, null=True),
        ),
        migrations.AlterField(
            model_name='companydetail',
            name='managing_paper',
            field=models.CharField(help_text='Managing paper of the company', max_length=360, null=True),
        ),
        migrations.AlterField(
            model_name='companydetail',
            name='superior_management',
            field=models.CharField(help_text='Superior management of the company', max_length=620, null=True),
        ),
        migrations.AlterField(
            model_name='companydetail',
            name='terminated_info',
            field=models.CharField(help_text='Info about termination', max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='companydetail',
            name='termination_cancel_info',
            field=models.CharField(help_text='Info about termination cancellation', max_length=570, null=True),
        ),
        migrations.AlterField(
            model_name='companydetail',
            name='vp_dates',
            field=models.TextField(help_text='Array of dates as string in YYYY-MM-DD format', null=True),
        ),
        migrations.AlterField(
            model_name='companylinkwithpep',
            name='category',
            field=models.CharField(blank=True, choices=[('bank_customer', 'Bank client'), ('owner', 'Owner'), ('by_position', 'By position'), ('manager', 'Manager'), ('other', 'Other')], default=None, help_text='Type of connection between the person and this company Can be: bank_customer, owner, manager, by_position, other.', max_length=15, null=True, verbose_name='connection`s category'),
        ),
        migrations.AlterField(
            model_name='companylinkwithpep',
            name='company',
            field=models.ForeignKey(help_text='The company associated with this person.', on_delete=django.db.models.deletion.CASCADE, related_name='relationships_with_peps', to='business_register.Company', verbose_name='associated with PEP company'),
        ),
        migrations.AlterField(
            model_name='companylinkwithpep',
            name='confirmation_date',
            field=models.CharField(help_text='Date of confirmation of connection in the "Anti-Corruption Action Center" database.', max_length=12, null=True, verbose_name='connection`s confirmation date'),
        ),
        migrations.AlterField(
            model_name='companylinkwithpep',
            name='end_date',
            field=models.CharField(help_text='Date of termination of connection between the person and  this company', max_length=12, null=True, verbose_name='connection`s end date'),
        ),
        migrations.AlterField(
            model_name='companylinkwithpep',
            name='is_state_company',
            field=models.BooleanField(help_text='Boolean type. If its true - the company is state-owned,if its false - the company is private.', null=True),
        ),
        migrations.AlterField(
            model_name='companylinkwithpep',
            name='relationship_type',
            field=models.CharField(help_text='Type of connection between the person and this company', max_length=550, null=True, verbose_name='connection`s type'),
        ),
        migrations.AlterField(
            model_name='companylinkwithpep',
            name='start_date',
            field=models.CharField(help_text="Date of the beginning of the person's connection with the company.", max_length=12, null=True, verbose_name='connection`s start date'),
        ),
        migrations.AlterField(
            model_name='companytokved',
            name='company',
            field=models.ForeignKey(help_text='Company name', on_delete=django.db.models.deletion.CASCADE, related_name='kveds', to='business_register.Company'),
        ),
        migrations.AlterField(
            model_name='companytokved',
            name='kved',
            field=models.ForeignKey(help_text='NACE as string', on_delete=django.db.models.deletion.CASCADE, to='business_register.Kved', verbose_name='NACE'),
        ),
        migrations.AlterField(
            model_name='companytokved',
            name='primary_kved',
            field=models.BooleanField(default=False, help_text='Primary NACE as string', verbose_name='declared as primary'),
        ),
        migrations.AlterField(
            model_name='companytopredecessor',
            name='company',
            field=models.ForeignKey(help_text='Company name', on_delete=django.db.models.deletion.CASCADE, related_name='predecessors', to='business_register.Company'),
        ),
        migrations.AlterField(
            model_name='companytopredecessor',
            name='predecessor',
            field=models.ForeignKey(help_text='Predecessor name in Ukrainian', on_delete=django.db.models.deletion.CASCADE, to='business_register.Predecessor'),
        ),
        migrations.AlterField(
            model_name='companytype',
            name='name',
            field=models.CharField(help_text='Company name in Ukrainian', max_length=270, null=True, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='companytype',
            name='name_eng',
            field=models.CharField(help_text='Company name in Company House (UK companies` register)', max_length=270, null=True, unique=True, verbose_name='name in Company House (UK companies` register)'),
        ),
        migrations.AlterField(
            model_name='exchangedatacompany',
            name='authority',
            field=models.ForeignKey(help_text='Authorized state agency which register the company', on_delete=django.db.models.deletion.CASCADE, to='data_ocean.Authority', verbose_name='registration authority'),
        ),
        migrations.AlterField(
            model_name='exchangedatacompany',
            name='company',
            field=models.ForeignKey(help_text='Company name', on_delete=django.db.models.deletion.CASCADE, related_name='exchange_data', to='business_register.Company'),
        ),
        migrations.AlterField(
            model_name='exchangedatacompany',
            name='end_date',
            field=models.DateField(help_text='End date as string in YYYY-MM-DD format', null=True),
        ),
        migrations.AlterField(
            model_name='exchangedatacompany',
            name='end_number',
            field=models.CharField(help_text='End number', max_length=555, null=True),
        ),
        migrations.AlterField(
            model_name='exchangedatacompany',
            name='start_date',
            field=models.DateField(help_text='Start date as string in YYYY-MM-DD format', null=True),
        ),
        migrations.AlterField(
            model_name='exchangedatacompany',
            name='start_number',
            field=models.CharField(help_text='Start number', max_length=555, null=True),
        ),
        migrations.AlterField(
            model_name='exchangedatacompany',
            name='taxpayer_type',
            field=models.ForeignKey(help_text='Taxpayer type of the company', null=True, on_delete=django.db.models.deletion.CASCADE, to='data_ocean.TaxpayerType'),
        ),
        migrations.AlterField(
            model_name='founder',
            name='address',
            field=models.CharField(blank=True, default='', help_text='Founder address in Ukrainian', max_length=2015, null=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='founder',
            name='company',
            field=models.ForeignKey(help_text='Company name', on_delete=django.db.models.deletion.CASCADE, related_name='founders', to='business_register.Company', verbose_name='owner'),
        ),
        migrations.AlterField(
            model_name='founder',
            name='country',
            field=models.CharField(blank=True, default='', help_text='Country of origin', max_length=100, null=True, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='founder',
            name='edrpou',
            field=models.CharField(blank=True, db_index=True, default='', help_text='EDRPOU number as string', max_length=9, null=True, verbose_name='number'),
        ),
        migrations.AlterField(
            model_name='founder',
            name='equity',
            field=models.FloatField(blank=True, help_text='Equity', null=True, verbose_name='equity'),
        ),
        migrations.AlterField(
            model_name='founder',
            name='info',
            field=models.CharField(help_text='Info', max_length=2015, verbose_name='info'),
        ),
        migrations.AlterField(
            model_name='founder',
            name='info_additional',
            field=models.CharField(help_text='Additional info', max_length=2015, null=True, verbose_name='additional info'),
        ),
        migrations.AlterField(
            model_name='founder',
            name='info_beneficiary',
            field=models.CharField(help_text='Beneficiary Info', max_length=2015, null=True, verbose_name='beneficiary info'),
        ),
        migrations.AlterField(
            model_name='founder',
            name='is_beneficiary',
            field=models.BooleanField(blank=True, default=False, help_text='Is beneficiary of the company', verbose_name='is beneficiary'),
        ),
        migrations.AlterField(
            model_name='founder',
            name='is_founder',
            field=models.BooleanField(blank=True, default=False, help_text='Is founder of the company', verbose_name='is owner'),
        ),
        migrations.AlterField(
            model_name='founder',
            name='name',
            field=models.TextField(db_index=True, help_text='Founder name in Ukrainian', verbose_name='name or full name'),
        ),
        migrations.AlterField(
            model_name='historicalassignee',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Company is the legal successor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='business_register.Company', verbose_name='є правонаступником'),
        ),
        migrations.AlterField(
            model_name='historicalassignee',
            name='edrpou',
            field=models.CharField(help_text='EDRPOU number as string', max_length=11, null=True, verbose_name='number'),
        ),
        migrations.AlterField(
            model_name='historicalassignee',
            name='name',
            field=models.CharField(help_text='Assignee name in Ukrainian', max_length=610, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='historicalbancruptcyreadjustment',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Bankruptcy readjustment', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='business_register.Company'),
        ),
        migrations.AlterField(
            model_name='historicalbancruptcyreadjustment',
            name='head_name',
            field=models.CharField(help_text='Head name', max_length=515, null=True),
        ),
        migrations.AlterField(
            model_name='historicalbancruptcyreadjustment',
            name='op_date',
            field=models.DateField(help_text='Date of bankruptcy readjustment as string in YYYY-MM-DD format', null=True),
        ),
        migrations.AlterField(
            model_name='historicalbancruptcyreadjustment',
            name='reason',
            field=models.TextField(help_text='Reason of bankruptcy', null=True, verbose_name='reason'),
        ),
        migrations.AlterField(
            model_name='historicalbancruptcyreadjustment',
            name='sbj_state',
            field=models.CharField(help_text='Subject state', max_length=345, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='address',
            field=models.CharField(help_text='Registration address in Ukrainian', max_length=1000, null=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='antac_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, default=None, help_text='ID from ANTACs DB', null=True, verbose_name='id from ANTACs DB'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='authority',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Authorized state agency which register the company', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='data_ocean.Authority', verbose_name='registration authority'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='authorized_capital',
            field=models.FloatField(help_text='Authorized capital as number', null=True, verbose_name='share capital'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='boss',
            field=models.CharField(blank=True, default='', help_text='CEO of the company', max_length=100, null=True, verbose_name='CEO'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='bylaw',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='By law', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='business_register.Bylaw', verbose_name='charter'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='code',
            field=models.CharField(db_index=True, help_text='Our code', max_length=510, verbose_name='our code'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='company_type',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Type of the company', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='business_register.CompanyType', verbose_name='company type'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='contact_info',
            field=models.CharField(help_text='Info about contacts', max_length=310, null=True, verbose_name='contacts'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='country',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Country of origin', max_length=60, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='location_register.Country', verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='edrpou',
            field=models.CharField(db_index=True, help_text='EDRPOU number as string', max_length=260, null=True, verbose_name='number'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='from_antac_only',
            field=models.BooleanField(help_text='If this field has "true" - Data provided by the Anti-Corruption Action Center.', null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='name',
            field=models.CharField(help_text='Company name in Ukrainian', max_length=500, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='parent',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Company that has a controlling interest in the company', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='business_register.Company', verbose_name='parent company'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='registration_date',
            field=models.DateField(help_text='Registration date as string in YYYY-MM-DD format', null=True, verbose_name='registration date'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='registration_info',
            field=models.CharField(help_text='Registration info of the company', max_length=450, null=True, verbose_name='registration info'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='short_name',
            field=models.CharField(help_text='Short name of the company in Ukrainian', max_length=500, null=True, verbose_name='short name'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='source',
            field=models.CharField(blank=True, choices=[('ukr', 'The United State Register of Legal Entities, Individual Entrepreneurs and Public Organizations of Ukraine'), ('gb', 'Company House (UK companies` register)'), ('antac', 'ANTAC')], db_index=True, default=None, help_text='Source', max_length=5, null=True, verbose_name='source'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='status',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Company legal status', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='data_ocean.Status', verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='historicalcompanydetail',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Company name', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='business_register.Company'),
        ),
        migrations.AlterField(
            model_name='historicalcompanydetail',
            name='executive_power',
            field=models.CharField(help_text='Executive power of the company', max_length=390, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompanydetail',
            name='founding_document_number',
            field=models.CharField(help_text='Founding document number as string', max_length=375, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompanydetail',
            name='managing_paper',
            field=models.CharField(help_text='Managing paper of the company', max_length=360, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompanydetail',
            name='superior_management',
            field=models.CharField(help_text='Superior management of the company', max_length=620, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompanydetail',
            name='terminated_info',
            field=models.CharField(help_text='Info about termination', max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompanydetail',
            name='termination_cancel_info',
            field=models.CharField(help_text='Info about termination cancellation', max_length=570, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompanydetail',
            name='vp_dates',
            field=models.TextField(help_text='Array of dates as string in YYYY-MM-DD format', null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompanytokved',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Company name', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='business_register.Company'),
        ),
        migrations.AlterField(
            model_name='historicalcompanytokved',
            name='kved',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='NACE as string', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='business_register.Kved', verbose_name='NACE'),
        ),
        migrations.AlterField(
            model_name='historicalcompanytokved',
            name='primary_kved',
            field=models.BooleanField(default=False, help_text='Primary NACE as string', verbose_name='declared as primary'),
        ),
        migrations.AlterField(
            model_name='historicalcompanytopredecessor',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Company name', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='business_register.Company'),
        ),
        migrations.AlterField(
            model_name='historicalcompanytopredecessor',
            name='predecessor',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Predecessor name in Ukrainian', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='business_register.Predecessor'),
        ),
        migrations.AlterField(
            model_name='historicalexchangedatacompany',
            name='authority',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Authorized state agency which register the company', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='data_ocean.Authority', verbose_name='registration authority'),
        ),
        migrations.AlterField(
            model_name='historicalexchangedatacompany',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Company name', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='business_register.Company'),
        ),
        migrations.AlterField(
            model_name='historicalexchangedatacompany',
            name='end_date',
            field=models.DateField(help_text='End date as string in YYYY-MM-DD format', null=True),
        ),
        migrations.AlterField(
            model_name='historicalexchangedatacompany',
            name='end_number',
            field=models.CharField(help_text='End number', max_length=555, null=True),
        ),
        migrations.AlterField(
            model_name='historicalexchangedatacompany',
            name='start_date',
            field=models.DateField(help_text='Start date as string in YYYY-MM-DD format', null=True),
        ),
        migrations.AlterField(
            model_name='historicalexchangedatacompany',
            name='start_number',
            field=models.CharField(help_text='Start number', max_length=555, null=True),
        ),
        migrations.AlterField(
            model_name='historicalexchangedatacompany',
            name='taxpayer_type',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Taxpayer type of the company', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='data_ocean.TaxpayerType'),
        ),
        migrations.AlterField(
            model_name='historicalfounder',
            name='address',
            field=models.CharField(blank=True, default='', help_text='Founder address in Ukrainian', max_length=2015, null=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='historicalfounder',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Company name', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='business_register.Company', verbose_name='owner'),
        ),
        migrations.AlterField(
            model_name='historicalfounder',
            name='country',
            field=models.CharField(blank=True, default='', help_text='Country of origin', max_length=100, null=True, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='historicalfounder',
            name='edrpou',
            field=models.CharField(blank=True, db_index=True, default='', help_text='EDRPOU number as string', max_length=9, null=True, verbose_name='number'),
        ),
        migrations.AlterField(
            model_name='historicalfounder',
            name='equity',
            field=models.FloatField(blank=True, help_text='Equity', null=True, verbose_name='equity'),
        ),
        migrations.AlterField(
            model_name='historicalfounder',
            name='info',
            field=models.CharField(help_text='Info', max_length=2015, verbose_name='info'),
        ),
        migrations.AlterField(
            model_name='historicalfounder',
            name='info_additional',
            field=models.CharField(help_text='Additional info', max_length=2015, null=True, verbose_name='additional info'),
        ),
        migrations.AlterField(
            model_name='historicalfounder',
            name='info_beneficiary',
            field=models.CharField(help_text='Beneficiary Info', max_length=2015, null=True, verbose_name='beneficiary info'),
        ),
        migrations.AlterField(
            model_name='historicalfounder',
            name='is_beneficiary',
            field=models.BooleanField(blank=True, default=False, help_text='Is beneficiary of the company', verbose_name='is beneficiary'),
        ),
        migrations.AlterField(
            model_name='historicalfounder',
            name='is_founder',
            field=models.BooleanField(blank=True, default=False, help_text='Is founder of the company', verbose_name='is owner'),
        ),
        migrations.AlterField(
            model_name='historicalfounder',
            name='name',
            field=models.TextField(db_index=True, help_text='Founder name in Ukrainian', verbose_name='name or full name'),
        ),
        migrations.AlterField(
            model_name='historicalpep',
            name='criminal_proceedings',
            field=models.TextField(help_text='Known criminal proceedings against the person. If its is null, the person has no criminal proceedings against him.', null=True, verbose_name='known criminal proceedings against the person'),
        ),
        migrations.AlterField(
            model_name='historicalpep',
            name='reason_of_termination',
            field=models.CharField(blank=True, choices=[('died', 'Is dead'), ('resigned', 'Resigned or term ended'), ('linked pep died', 'Associated PEP is dead'), ('linked pep resigned', 'Associated person is no more PEP'), ('legislation changed', 'Legislation was changed'), ('company status changed', 'Company is no more state')], help_text='PEP status reason of termination. Can be "Is dead", "Resigned or term ended", "Associated PEP is dead", "Legislation was changed", "Company is no more state" or null.', max_length=125, null=True, verbose_name='reason of termination'),
        ),
        migrations.AlterField(
            model_name='historicalpep',
            name='termination_date',
            field=models.CharField(help_text='PEP status termination date in YYYY-MM-DD format.', max_length=10, null=True, verbose_name='PEP status termination date '),
        ),
        migrations.AlterField(
            model_name='historicalsigner',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Company name', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='business_register.Company'),
        ),
        migrations.AlterField(
            model_name='historicalsigner',
            name='name',
            field=models.CharField(help_text='Signer name in Ukrainian', max_length=390, null=True, verbose_name='full name'),
        ),
        migrations.AlterField(
            model_name='historicalterminationstarted',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Company name', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='business_register.Company'),
        ),
        migrations.AlterField(
            model_name='historicalterminationstarted',
            name='creditor_reg_end_date',
            field=models.DateField(help_text='Creditor registration end date as string in YYYY-MM-DD format', null=True),
        ),
        migrations.AlterField(
            model_name='historicalterminationstarted',
            name='op_date',
            field=models.DateField(help_text='Date as string in YYYY-MM-DD format', null=True),
        ),
        migrations.AlterField(
            model_name='historicalterminationstarted',
            name='reason',
            field=models.TextField(help_text='Reason of termination', null=True, verbose_name='reason'),
        ),
        migrations.AlterField(
            model_name='historicalterminationstarted',
            name='sbj_state',
            field=models.CharField(help_text='State of the company', max_length=530, null=True),
        ),
        migrations.AlterField(
            model_name='historicalterminationstarted',
            name='signer_name',
            field=models.CharField(help_text='Signer name in Ukrainian', max_length=480, null=True),
        ),
        migrations.AlterField(
            model_name='kved',
            name='code',
            field=models.CharField(db_index=True, help_text='Code in the classification of economic activities.', max_length=10, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='kved',
            name='division',
            field=models.ForeignKey(help_text='Division title in the classification of economic activities.', on_delete=django.db.models.deletion.CASCADE, to='business_register.KvedDivision', verbose_name='division'),
        ),
        migrations.AlterField(
            model_name='kved',
            name='group',
            field=models.ForeignKey(help_text='Group title in the classification of economic activities.', on_delete=django.db.models.deletion.CASCADE, to='business_register.KvedGroup', verbose_name='group'),
        ),
        migrations.AlterField(
            model_name='kved',
            name='name',
            field=models.CharField(help_text='Name of the type of economic activity.', max_length=500, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='kved',
            name='section',
            field=models.ForeignKey(help_text='Section title in the classification of economic activities.', on_delete=django.db.models.deletion.CASCADE, to='business_register.KvedSection', verbose_name='section'),
        ),
        migrations.AlterField(
            model_name='pep',
            name='criminal_proceedings',
            field=models.TextField(help_text='Known criminal proceedings against the person. If its is null, the person has no criminal proceedings against him.', null=True, verbose_name='known criminal proceedings against the person'),
        ),
        migrations.AlterField(
            model_name='pep',
            name='reason_of_termination',
            field=models.CharField(blank=True, choices=[('died', 'Is dead'), ('resigned', 'Resigned or term ended'), ('linked pep died', 'Associated PEP is dead'), ('linked pep resigned', 'Associated person is no more PEP'), ('legislation changed', 'Legislation was changed'), ('company status changed', 'Company is no more state')], help_text='PEP status reason of termination. Can be "Is dead", "Resigned or term ended", "Associated PEP is dead", "Legislation was changed", "Company is no more state" or null.', max_length=125, null=True, verbose_name='reason of termination'),
        ),
        migrations.AlterField(
            model_name='pep',
            name='termination_date',
            field=models.CharField(help_text='PEP status termination date in YYYY-MM-DD format.', max_length=10, null=True, verbose_name='PEP status termination date '),
        ),
        migrations.AlterField(
            model_name='predecessor',
            name='edrpou',
            field=models.CharField(help_text='EDRPOU number as string', max_length=405, null=True, verbose_name='number'),
        ),
        migrations.AlterField(
            model_name='predecessor',
            name='name',
            field=models.CharField(help_text='Predecessor name in Ukrainian', max_length=500, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='relatedpersonslink',
            name='category',
            field=models.CharField(blank=True, choices=[('family', 'Family'), ('business', 'Business'), ('personal', 'Personal')], help_text='The category of the relationship with the related person. Can be: family, business, personal.', max_length=20, null=True, verbose_name='connection`s category'),
        ),
        migrations.AlterField(
            model_name='relatedpersonslink',
            name='confirmation_date',
            field=models.CharField(help_text='Date of confirmation of connection in the "Anti-Corruption Action Center" database.', max_length=12, null=True, verbose_name='connection`s confirmation date'),
        ),
        migrations.AlterField(
            model_name='relatedpersonslink',
            name='end_date',
            field=models.CharField(help_text='The date the relationship ends.', max_length=12, null=True, verbose_name='connection`s end date'),
        ),
        migrations.AlterField(
            model_name='relatedpersonslink',
            name='from_person',
            field=models.ForeignKey(help_text='From which person the connection is established.', on_delete=django.db.models.deletion.CASCADE, related_name='from_person_links', to='business_register.Pep', verbose_name='associated person'),
        ),
        migrations.AlterField(
            model_name='relatedpersonslink',
            name='from_person_relationship_type',
            field=models.CharField(help_text='The type of relationship with a related person.', max_length=90, null=True, verbose_name='connection`s type'),
        ),
        migrations.AlterField(
            model_name='relatedpersonslink',
            name='start_date',
            field=models.CharField(help_text='Date of the beginning of the relationship.', max_length=12, null=True, verbose_name='connection`s start date'),
        ),
        migrations.AlterField(
            model_name='relatedpersonslink',
            name='to_person',
            field=models.ForeignKey(help_text='With what person the connection is established.', on_delete=django.db.models.deletion.CASCADE, related_name='to_person_links', to='business_register.Pep', verbose_name='another associated person'),
        ),
        migrations.AlterField(
            model_name='relatedpersonslink',
            name='to_person_relationship_type',
            field=models.CharField(help_text='The type of relationship with a related person.', max_length=90, null=True, verbose_name='another person`s connection`s type'),
        ),
        migrations.AlterField(
            model_name='signer',
            name='company',
            field=models.ForeignKey(help_text='Company name', on_delete=django.db.models.deletion.CASCADE, related_name='signers', to='business_register.Company'),
        ),
        migrations.AlterField(
            model_name='signer',
            name='name',
            field=models.CharField(help_text='Signer name in Ukrainian', max_length=390, null=True, verbose_name='full name'),
        ),
        migrations.AlterField(
            model_name='terminationstarted',
            name='company',
            field=models.ForeignKey(help_text='Company name', on_delete=django.db.models.deletion.CASCADE, related_name='termination_started', to='business_register.Company'),
        ),
        migrations.AlterField(
            model_name='terminationstarted',
            name='creditor_reg_end_date',
            field=models.DateField(help_text='Creditor registration end date as string in YYYY-MM-DD format', null=True),
        ),
        migrations.AlterField(
            model_name='terminationstarted',
            name='op_date',
            field=models.DateField(help_text='Date as string in YYYY-MM-DD format', null=True),
        ),
        migrations.AlterField(
            model_name='terminationstarted',
            name='reason',
            field=models.TextField(help_text='Reason of termination', null=True, verbose_name='reason'),
        ),
        migrations.AlterField(
            model_name='terminationstarted',
            name='sbj_state',
            field=models.CharField(help_text='State of the company', max_length=530, null=True),
        ),
        migrations.AlterField(
            model_name='terminationstarted',
            name='signer_name',
            field=models.CharField(help_text='Signer name in Ukrainian', max_length=480, null=True),
        ),
    ]
