# Generated by Django 3.0.7 on 2021-03-18 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_register', '0069_auto_20210316_1540'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='companylinkwithpep',
            unique_together={('company', 'pep')},
        ),
    ]
