# Generated by Django 3.0.7 on 2021-03-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_register', '0070_auto_20210318_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='companylinkwithpep',
            name='source_id',
            field=models.IntegerField(default=None, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='companylinkwithpep',
            unique_together=set(),
        ),
    ]
