# Generated by Django 3.0.7 on 2021-03-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_register', '0071_auto_20210318_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatedpersonslink',
            name='source_id',
            field=models.PositiveIntegerField(default=None, null=True, unique=True, verbose_name='id from ANTACs DB'),
        ),
        migrations.AlterField(
            model_name='companylinkwithpep',
            name='source_id',
            field=models.PositiveIntegerField(default=None, null=True, unique=True, verbose_name='id from ANTACs DB'),
        ),
    ]
