# Generated by Django 3.0.7 on 2021-03-23 15:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('business_register', '0072_auto_20210322_1008'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            UPDATE business_register_assignee SET name='' where name is null;
            UPDATE business_register_assignee SET edrpou='' where edrpou is null;   
            """,
            reverse_sql="""
            UPDATE business_register_assignee SET name=null where name = '';
            UPDATE business_register_assignee SET edrpou=null where edrpou = '';   
            """,
        ),
    ]
