# Generated by Django 3.0.7 on 2021-03-24 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_register', '0075_auto_20210324_1008'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='pep',
            name='business_re_fullnam_0639b9_idx',
        ),
        migrations.AlterField(
            model_name='historicalpep',
            name='date_of_birth',
            field=models.CharField(db_index=True, help_text='Person`s date of birth in YYYY-MM-DD format.', max_length=10, null=True, verbose_name='date of birth'),
        ),
        migrations.AlterField(
            model_name='historicalpep',
            name='first_name',
            field=models.CharField(db_index=True, help_text='First name of PEP in Ukrainian', max_length=20, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='historicalpep',
            name='last_name',
            field=models.CharField(db_index=True, help_text='Last name of PEP in Ukrainian', max_length=30, verbose_name='surname'),
        ),
        migrations.AlterField(
            model_name='historicalpep',
            name='middle_name',
            field=models.CharField(db_index=True, help_text='Middle name of PEP in Ukrainian', max_length=25, verbose_name='middle name'),
        ),
        migrations.AlterField(
            model_name='pep',
            name='date_of_birth',
            field=models.CharField(db_index=True, help_text='Person`s date of birth in YYYY-MM-DD format.', max_length=10, null=True, verbose_name='date of birth'),
        ),
        migrations.AlterField(
            model_name='pep',
            name='first_name',
            field=models.CharField(db_index=True, help_text='First name of PEP in Ukrainian', max_length=20, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='pep',
            name='last_name',
            field=models.CharField(db_index=True, help_text='Last name of PEP in Ukrainian', max_length=30, verbose_name='surname'),
        ),
        migrations.AlterField(
            model_name='pep',
            name='middle_name',
            field=models.CharField(db_index=True, help_text='Middle name of PEP in Ukrainian', max_length=25, verbose_name='middle name'),
        ),
    ]
