# Generated by Django 3.1.7 on 2021-03-30 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_ocean', '0024_auto_20210319_1045'),
        ('business_register', '0076_auto_20210324_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.ForeignKey(help_text='Company legal status. Can be: "зареєстровано", "в стані припинення", "припинено", "EMP", "порушено справу про банкрутство", "порушено справу про банкрутство (санація)", "зареєстровано, свідоцтво про державну реєстрацію недійсне", "скасовано", "active", "active - proposal to strike off", "liquidation", "administration order", "voluntary arrangement", "in administration/administrative receiver", "in administration", "live but receiver manager on at least one charge", "in administration/receiver manager", "receivership", "receiver manager / administrative receiver", "administrative receiver", voluntary arrangement / administrative receiver", "voluntary arrangement / receiver manager".', null=True, on_delete=django.db.models.deletion.CASCADE, to='data_ocean.status', verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='status',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Company legal status. Can be: "зареєстровано", "в стані припинення", "припинено", "EMP", "порушено справу про банкрутство", "порушено справу про банкрутство (санація)", "зареєстровано, свідоцтво про державну реєстрацію недійсне", "скасовано", "active", "active - proposal to strike off", "liquidation", "administration order", "voluntary arrangement", "in administration/administrative receiver", "in administration", "live but receiver manager on at least one charge", "in administration/receiver manager", "receivership", "receiver manager / administrative receiver", "administrative receiver", voluntary arrangement / administrative receiver", "voluntary arrangement / receiver manager".', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='data_ocean.status', verbose_name='status'),
        ),
    ]
