# Generated by Django 3.0.7 on 2021-04-03 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location_register', '0021_auto_20210330_1650'),
        ('business_register', '0078_auto_20210330_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='SanctionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the object was created. In YYYY-MM-DDTHH:mm:ss.SSSSSSZ format.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the object was update. In YYYY-MM-DDTHH:mm:ss.SSSSSSZ format.', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('name', models.CharField(help_text='name of the type of sanctions applied', max_length=500, verbose_name='name')),
                ('law', models.CharField(blank=True, default=None, help_text='law used to impose sanctions', max_length=80, null=True, verbose_name='law used')),
            ],
            options={
                'verbose_name': 'Sanction type',
                'verbose_name_plural': 'Sanction types',
            },
        ),
        migrations.CreateModel(
            name='Sanction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the object was created. In YYYY-MM-DDTHH:mm:ss.SSSSSSZ format.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the object was update. In YYYY-MM-DDTHH:mm:ss.SSSSSSZ format.', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('object_type', models.CharField(choices=[('p', 'Person'), ('c', 'Company'), ('s', 'State')], help_text='type of the object under sanctions', max_length=1, verbose_name='type of object')),
                ('is_foreign', models.BooleanField(db_index=True, help_text='is foreign or Ukrainian', verbose_name='is foreign')),
                ('object_name', models.CharField(db_index=True, help_text='name of of the object under sanctions', max_length=100, verbose_name='object name')),
                ('object_origin_name', models.CharField(blank=True, db_index=True, default=None, help_text='name of the object under sanctions in the language of the country of origin', max_length=100, null=True, verbose_name='object origin name')),
                ('date_of_birth', models.DateField(blank=True, default=None, help_text='date of birth', null=True, verbose_name='date of birth')),
                ('place_of_birth', models.CharField(blank=True, default=None, help_text='place of birth of the person under sanctions', max_length=100, null=True, verbose_name='place of birth')),
                ('address', models.CharField(blank=True, default=None, help_text='place of registration or residence of the person or company under sanctions', max_length=100, null=True, verbose_name='address')),
                ('registration_date', models.DateField(blank=True, default=None, help_text='date of registration of the company under sanctions', null=True, verbose_name='registration date')),
                ('registration_number', models.CharField(blank=True, default=None, help_text='number of registration of the company under sanctions', max_length=15, null=True, verbose_name='registration number')),
                ('position', models.CharField(blank=True, default=None, help_text='position or professional activity of the person under sanctions', max_length=500, null=True, verbose_name='position')),
                ('id_card', models.CharField(blank=True, default=None, help_text='id card the person under sanctions', max_length=100, null=True, verbose_name='id card info')),
                ('taxpayer_number', models.CharField(blank=True, db_index=True, default=None, help_text='taxpayer number of the person or company under sanctions', max_length=15, null=True, verbose_name='taxpayer number')),
                ('imposed_by', models.CharField(help_text='institution that imposed sanctions', max_length=50, verbose_name='imposed by')),
                ('start_date', models.DateField(help_text='date of imposing sanctions', verbose_name='start date')),
                ('end_date', models.DateField(help_text='end date of sanctions', verbose_name='end date')),
                ('reasoning', models.CharField(blank=True, default=None, help_text='reasoning of imposing sanctions', max_length=500, null=True, verbose_name='reasoning')),
                ('country', models.ForeignKey(help_text='Country of citizenship/registration of the person or company under sanctions', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='residents_under_sanctions', to='location_register.Country', verbose_name='country')),
                ('type_of_sanctions', models.ForeignKey(help_text='type of sanctions', on_delete=django.db.models.deletion.CASCADE, related_name='objects_of_sanction', to='business_register.SanctionType', verbose_name='type of sanctions')),
            ],
            options={
                'verbose_name': 'Sanction',
                'verbose_name_plural': 'Sanctions',
                'ordering': ['start_date'],
            },
        ),
    ]
