# Generated by Django 3.0.7 on 2021-04-05 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location_register', '0021_auto_20210330_1650'),
        ('business_register', '0079_sanction_sanctiontype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sanction',
            name='type_of_sanctions',
        ),
        migrations.AddField(
            model_name='sanction',
            name='types_of_sanctions',
            field=models.ManyToManyField(help_text='types of sanctions applied', related_name='objects_of_sanction', to='business_register.SanctionType', verbose_name='types of sanctions'),
        ),
        migrations.AlterField(
            model_name='sanction',
            name='country',
            field=models.ForeignKey(help_text='country of citizenship/registration of the person or company under sanctions', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='residents_under_sanctions', to='location_register.Country', verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='sanction',
            name='id_card',
            field=models.CharField(blank=True, default=None, help_text='id cards info of the person under sanctions', max_length=180, null=True, verbose_name='id cards info'),
        ),
    ]
