# Generated by Django 3.0.7 on 2021-04-14 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location_register', '0021_auto_20210330_1650'),
        ('business_register', '0081_auto_20210406_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySanction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the object was created. In YYYY-MM-DDTHH:mm:ss.SSSSSSZ format.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the object was update. In YYYY-MM-DDTHH:mm:ss.SSSSSSZ format.', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('start_date', models.DateField(help_text='date of imposing sanctions', verbose_name='start date')),
                ('end_date', models.DateField(help_text='end date of sanctions', verbose_name='end date')),
                ('reasoning', models.CharField(blank=True, default='', help_text='reasoning of imposing sanctions', max_length=500, verbose_name='reasoning')),
                ('is_foreign', models.BooleanField(blank=True, db_index=True, default=True, help_text='is foreign or Ukrainian', verbose_name='is foreign')),
                ('name', models.CharField(db_index=True, help_text='name of the company under sanctions', max_length=100, verbose_name='company name')),
                ('name_original_transcription', models.CharField(blank=True, db_index=True, default='', help_text='original transcription of the company name in the language of the country of registration', max_length=100, verbose_name='original transcription of the name')),
                ('address', models.CharField(blank=True, default='', help_text='address of registration or the main office of the company under sanctions', max_length=100, verbose_name='address')),
                ('registration_date', models.DateField(blank=True, default=None, help_text='date of registration of the company under sanctions', null=True, verbose_name='registration date')),
                ('registration_number', models.CharField(blank=True, default='', help_text='number of registration of the company under sanctions', max_length=15, verbose_name='registration number')),
                ('taxpayer_number', models.CharField(blank=True, db_index=True, default='', help_text='taxpayer number of the company under sanctions', max_length=8, verbose_name='company taxpayer number')),
                ('company', models.ForeignKey(blank=True, default=None, help_text='company or organisation under this sanction', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='official_sanctions', to='business_register.Company', verbose_name='company')),
                ('country_of_registration', models.ForeignKey(help_text='country of registration of the company under sanctions', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sanctions_against_companies', to='location_register.Country', verbose_name='country of registration')),
            ],
            options={
                'verbose_name': 'Sanction against company',
                'verbose_name_plural': 'Sanctions against companies',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='CountrySanction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the object was created. In YYYY-MM-DDTHH:mm:ss.SSSSSSZ format.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the object was update. In YYYY-MM-DDTHH:mm:ss.SSSSSSZ format.', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('start_date', models.DateField(help_text='date of imposing sanctions', verbose_name='start date')),
                ('end_date', models.DateField(help_text='end date of sanctions', verbose_name='end date')),
                ('reasoning', models.CharField(blank=True, default='', help_text='reasoning of imposing sanctions', max_length=500, verbose_name='reasoning')),
                ('country', models.ForeignKey(help_text='country under this sanction', on_delete=django.db.models.deletion.CASCADE, related_name='official_sanctions', to='location_register.Country', verbose_name='country')),
            ],
            options={
                'verbose_name': 'Sanction against country',
                'verbose_name_plural': 'Sanctions against countries',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='PersonSanction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the object was created. In YYYY-MM-DDTHH:mm:ss.SSSSSSZ format.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the object was update. In YYYY-MM-DDTHH:mm:ss.SSSSSSZ format.', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('start_date', models.DateField(help_text='date of imposing sanctions', verbose_name='start date')),
                ('end_date', models.DateField(help_text='end date of sanctions', verbose_name='end date')),
                ('reasoning', models.CharField(blank=True, default='', help_text='reasoning of imposing sanctions', max_length=500, verbose_name='reasoning')),
                ('is_foreign', models.BooleanField(blank=True, db_index=True, default=True, help_text='is foreign or Ukrainian', verbose_name='is foreign')),
                ('first_name', models.CharField(help_text='first name of the person under sanctions', max_length=20, verbose_name='first name')),
                ('middle_name', models.CharField(blank=True, default='', help_text='middle name of the person under sanctions', max_length=25, verbose_name='middle name')),
                ('last_name', models.CharField(help_text='last name of the person under sanctions', max_length=30, verbose_name='surname')),
                ('full_name', models.CharField(help_text='full name of the person under sanctions', max_length=75, verbose_name='full name')),
                ('full_name_original_transcription', models.CharField(blank=True, default='', help_text='full name of the person under sanctions in the language of the country of origin', max_length=75, verbose_name='full name original transcription')),
                ('date_of_birth', models.DateField(blank=True, default=None, help_text='date of birth of the person under sanctions', null=True, verbose_name='date of birth')),
                ('place_of_birth', models.CharField(blank=True, default='', help_text='place of birth of the person under sanctions', max_length=100, verbose_name='place of birth')),
                ('address', models.CharField(blank=True, default='', help_text='place of registration or residence of the person under sanctions', max_length=100, verbose_name='address')),
                ('occupation', models.CharField(blank=True, default='', help_text='occupation or professional activity of the person under sanctions', max_length=500, verbose_name='occupation')),
                ('id_card', models.CharField(blank=True, default='', help_text='id cards info of the person under sanctions', max_length=180, verbose_name='id cards info')),
                ('taxpayer_number', models.CharField(blank=True, db_index=True, default='', help_text='taxpayer number of the person under sanctions', max_length=15, verbose_name='taxpayer number')),
                ('countries_of_citizenship', models.ManyToManyField(help_text='country of citizenship of the person under sanctions', related_name='sanctions_against_citizens', to='location_register.Country', verbose_name='country of citizenship')),
                ('pep', models.ForeignKey(blank=True, default=None, help_text='politically exposed person under this sanction', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='official_sanctions', to='business_register.Pep', verbose_name='PEP')),
            ],
            options={
                'verbose_name': 'Sanction against person',
                'verbose_name_plural': 'Sanctions against persons',
                'ordering': ['start_date'],
            },
        ),
        migrations.AlterField(
            model_name='sanctiontype',
            name='law',
            field=models.CharField(blank=True, default='', help_text='law used to impose sanctions', max_length=80, verbose_name='law used'),
        ),
        migrations.DeleteModel(
            name='Sanction',
        ),
        migrations.AddField(
            model_name='personsanction',
            name='types_of_sanctions',
            field=models.ManyToManyField(help_text='types of sanctions applied', related_name='persons_under_sanction', to='business_register.SanctionType', verbose_name='types of sanctions'),
        ),
        migrations.AddField(
            model_name='countrysanction',
            name='types_of_sanctions',
            field=models.ManyToManyField(help_text='types of sanctions applied', related_name='countries_under_sanction', to='business_register.SanctionType', verbose_name='types of sanctions'),
        ),
        migrations.AddField(
            model_name='companysanction',
            name='types_of_sanctions',
            field=models.ManyToManyField(help_text='types of sanctions applied', related_name='companies_under_sanction', to='business_register.SanctionType', verbose_name='types of sanctions'),
        ),
    ]
