# Generated by Django 3.0.7 on 2021-04-15 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_register', '0083_auto_20210415_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysanction',
            name='cancellation_condition',
            field=models.TextField(blank=True, default='', help_text='condition of the cancellation of sanctions', verbose_name='cancellation condition'),
        ),
        migrations.AddField(
            model_name='countrysanction',
            name='cancellation_condition',
            field=models.TextField(blank=True, default='', help_text='condition of the cancellation of sanctions', verbose_name='cancellation condition'),
        ),
        migrations.AddField(
            model_name='personsanction',
            name='cancellation_condition',
            field=models.TextField(blank=True, default='', help_text='condition of the cancellation of sanctions', verbose_name='cancellation condition'),
        ),
        migrations.AlterField(
            model_name='companysanction',
            name='end_date',
            field=models.DateField(blank=True, default=None, help_text='end date of sanctions', null=True, verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='countrysanction',
            name='end_date',
            field=models.DateField(blank=True, default=None, help_text='end date of sanctions', null=True, verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='personsanction',
            name='end_date',
            field=models.DateField(blank=True, default=None, help_text='end date of sanctions', null=True, verbose_name='end date'),
        ),
    ]
