# Generated by Django 3.0.7 on 2021-04-16 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_register', '0084_auto_20210415_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysanction',
            name='taxpayer_number',
            field=models.CharField(blank=True, db_index=True, default='', help_text='taxpayer number of the company under sanctions', max_length=15, verbose_name='company taxpayer number'),
        ),
    ]
