# Generated by Django 3.0.7 on 2021-04-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_register', '0085_auto_20210416_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysanction',
            name='name',
            field=models.TextField(db_index=True, help_text='name of the company under sanctions', verbose_name='company name'),
        ),
        migrations.AlterField(
            model_name='companysanction',
            name='name_original_transcription',
            field=models.TextField(blank=True, db_index=True, default='', help_text='original transcription of the company name in the language of the country of registration', verbose_name='original transcription of the name'),
        ),
    ]
