# Generated by Django 3.0.7 on 2021-04-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_register', '0086_auto_20210416_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanctiontype',
            name='name',
            field=models.TextField(help_text='name of the type of sanctions applied', unique=True, verbose_name='name'),
        ),
    ]
