# Generated by Django 3.0.7 on 2021-04-19 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_register', '0087_auto_20210416_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysanction',
            name='address',
            field=models.TextField(blank=True, default='', help_text='address of registration or the main office of the company under sanctions', verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='personsanction',
            name='address',
            field=models.TextField(blank=True, default='', help_text='place of registration or residence of the person under sanctions', verbose_name='address'),
        ),
    ]
