# Generated by Django 3.0.7 on 2021-04-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_register', '0088_auto_20210419_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysanction',
            name='reasoning',
            field=models.TextField(blank=True, default='', help_text='reasoning of imposing sanctions', verbose_name='reasoning'),
        ),
        migrations.AlterField(
            model_name='countrysanction',
            name='reasoning',
            field=models.TextField(blank=True, default='', help_text='reasoning of imposing sanctions', verbose_name='reasoning'),
        ),
        migrations.AlterField(
            model_name='personsanction',
            name='reasoning',
            field=models.TextField(blank=True, default='', help_text='reasoning of imposing sanctions', verbose_name='reasoning'),
        ),
    ]
