# Generated by Django 3.0.7 on 2021-04-23 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_register', '0089_auto_20210419_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companysanction',
            name='is_foreign',
        ),
        migrations.RemoveField(
            model_name='personsanction',
            name='is_foreign',
        ),
    ]
