# Generated by Django 3.0.7 on 2021-04-26 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_register', '0090_auto_20210423_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpep',
            name='nacp_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='id from the National agency on corruption prevention', null=True, verbose_name='id from NACP'),
        ),
        migrations.AddField(
            model_name='pep',
            name='nacp_id',
            field=models.PositiveIntegerField(blank=True, help_text='id from the National agency on corruption prevention', null=True, unique=True, verbose_name='id from NACP'),
        ),
    ]
