# Generated by Django 3.0.7 on 2021-04-27 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_register', '0091_auto_20210426_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysanction',
            name='additional_info',
            field=models.TextField(blank=True, default='', help_text='additional info about the company under sanctions', verbose_name='additional info'),
        ),
        migrations.AddField(
            model_name='personsanction',
            name='additional_info',
            field=models.TextField(blank=True, default='', help_text='additional info about the person under sanctions', verbose_name='additional info'),
        ),
    ]
