# Generated by Django 3.1.8 on 2021-04-28 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_register', '0092_auto_20210427_0936'),
        ('business_register', '0092_auto_20210427_1509'),
    ]

    operations = [
    ]
