# Generated by Django 3.0.7 on 2021-05-07 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_register', '0095_auto_20210507_0947'),
        ('business_register', '0095_auto_20210506_0758'),
    ]

    operations = [
    ]
