# Generated by Django 3.0.7 on 2021-05-11 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location_register', '0022_auto_20210415_0936'),
        ('business_register', '0095_auto_20210506_0758'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the object was created. In YYYY-MM-DDTHH:mm:ss.SSSSSSZ format.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the object was update. In YYYY-MM-DDTHH:mm:ss.SSSSSSZ format.', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Car'), (2, 'Truck')], help_text='type of the vehicle', verbose_name='type')),
                ('is_luxury', models.BooleanField(blank=True, default=None, help_text='is luxury', null=True, verbose_name='is luxury')),
                ('brand', models.CharField(blank=True, default='', help_text='brand', max_length=40, verbose_name='brand')),
                ('model', models.CharField(blank=True, default='', help_text='model', max_length=20, verbose_name='model')),
                ('year', models.PositiveSmallIntegerField(blank=True, help_text='year of manufacture', null=True, verbose_name='year of manufacture')),
                ('valuation', models.PositiveIntegerField(blank=True, help_text='valuation', null=True, verbose_name='valuation')),
                ('declaration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='business_register.Declaration', verbose_name='declaration')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VehicleRight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the object was created. In YYYY-MM-DDTHH:mm:ss.SSSSSSZ format.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the object was update. In YYYY-MM-DDTHH:mm:ss.SSSSSSZ format.', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Ownership'), (2, 'Joint ownership'), (3, 'Rent'), (4, 'Usage')], help_text='type of the right', verbose_name='type')),
                ('acquisition_date', models.DateField(blank=True, help_text='date of acquisition of the right', null=True, verbose_name='acquisition date')),
                ('share', models.PositiveIntegerField(blank=True, help_text='share of the right', null=True, verbose_name='share of the right')),
                ('full_name', models.CharField(blank=True, default='', help_text='full name of the person that owns the right', max_length=75, verbose_name='full name')),
                ('car', models.ForeignKey(help_text='right to the vehicle', on_delete=django.db.models.deletion.PROTECT, related_name='rights', to='business_register.Vehicle', verbose_name='vehicle_right')),
                ('company', models.ForeignKey(blank=True, default=None, help_text='company or organisation that owns the right', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='business_register_vehicleright_rights', to='business_register.Company', verbose_name='company')),
                ('country_of_citizenship', models.ForeignKey(blank=True, default=None, help_text='country of citizenship of the owner of the the right', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='business_register_vehicleright_rights', to='location_register.Country', verbose_name='country of citizenship')),
                ('pep', models.ForeignKey(blank=True, default=None, help_text='politically exposed person that owns the right', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='business_register_vehicleright_rights', to='business_register.Pep', verbose_name='PEP that owns the right')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='carright',
            name='car',
        ),
        migrations.RemoveField(
            model_name='carright',
            name='company',
        ),
        migrations.RemoveField(
            model_name='carright',
            name='country_of_citizenship',
        ),
        migrations.RemoveField(
            model_name='carright',
            name='pep',
        ),
        migrations.RemoveField(
            model_name='securities',
            name='amount',
        ),
        migrations.AddField(
            model_name='securities',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, help_text='quantity of securities', null=True, verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='property',
            name='area',
            field=models.FloatField(blank=True, help_text='square meters of the property', null=True, verbose_name='square'),
        ),
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'House'), (2, 'Summer house'), (3, 'Apartment'), (4, 'Room'), (5, 'Garage'), (6, 'Unfinished construction'), (7, 'Land'), (8, 'Office'), (9, 'Other')], help_text='type of the property', verbose_name='type'),
        ),
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='CarRight',
        ),
    ]
