# Generated by Django 3.0.7 on 2021-05-11 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_register', '0096_auto_20210511_1204'),
        ('business_register', '0097_auto_20210507_1208'),
    ]

    operations = [
    ]
