# Generated by Django 3.1.8 on 2021-05-12 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_register', '0098_merge_20210511_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personsanction',
            name='occupation',
            field=models.TextField(blank=True, default='', help_text='occupation or professional activity of the person under sanctions', verbose_name='occupation'),
        ),
    ]
