# Generated by Django 3.0.7 on 2021-05-12 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_register', '0099_auto_20210512_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fop',
            name='contact_info',
            field=models.TextField(blank=True, null=True, verbose_name='contacts'),
        ),
        migrations.AlterField(
            model_name='historicalfop',
            name='contact_info',
            field=models.TextField(blank=True, null=True, verbose_name='contacts'),
        ),
    ]
