# Generated by Django 3.1.8 on 2021-05-14 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_register', '0097_auto_20210513_0741'),
        ('business_register', '0100_auto_20210512_1150'),
        ('business_register', '0100_auto_20210513_1411'),
    ]

    operations = [
    ]
