# Generated by Django 3.1.8 on 2021-05-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_register', '0101_merge_20210514_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fop',
            name='registration_number',
            field=models.CharField(blank=True, max_length=19, null=True, verbose_name='registration number'),
        ),
        migrations.AlterField(
            model_name='historicalfop',
            name='registration_number',
            field=models.CharField(blank=True, max_length=19, null=True, verbose_name='registration number'),
        ),
    ]
