# Generated by Django 3.1.8 on 2021-05-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_register', '0102_auto_20210514_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='name_en',
            field=models.CharField(help_text='Company name in English', max_length=500, null=True, verbose_name='english name'),
        ),
        migrations.AddField(
            model_name='historicalcompany',
            name='name_en',
            field=models.CharField(help_text='Company name in English', max_length=500, null=True, verbose_name='english name'),
        ),
    ]