# Generated by Django 3.1.8 on 2021-05-20 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_register', '0104_auto_20210519_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpep',
            name='pep_org_ua_link',
            field=models.URLField(blank=True, db_index=True, help_text="URL address of PEP's profile in pep.org.ua", max_length=35, null=True, verbose_name='link to pep.org.ua profile'),
        ),
        migrations.AddField(
            model_name='pep',
            name='pep_org_ua_link',
            field=models.URLField(blank=True, help_text="URL address of PEP's profile in pep.org.ua", max_length=35, null=True, unique=True, verbose_name='link to pep.org.ua profile'),
        ),
    ]
