# Generated by Django 3.1.8 on 2021-05-20 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_register', '0104_auto_20210519_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='additional_info',
            field=models.TextField(blank=True, default='', help_text='additional info about the vehicle', verbose_name='additional info'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(blank=True, default='', help_text='model', max_length=75, verbose_name='model'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Car'), (2, 'Truck'), (4, 'Boat'), (5, 'Agricultural machinery'), (10, 'Other')], help_text='type of the vehicle', verbose_name='type'),
        ),
    ]
