# Generated by Django 3.1.8 on 2021-05-28 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_register', '0106_merge_20210528_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='companylinkwithpep',
            name='relationship_type_en',
            field=models.CharField(help_text='Type of connection between the person and this company in English', max_length=550, null=True, verbose_name='connection`s type in English'),
        ),
    ]
