# Generated by Django 3.1.8 on 2021-05-26 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_register', '0107_auto_20210526_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securities',
            name='valuation',
        ),
        migrations.AddField(
            model_name='securities',
            name='additional_info',
            field=models.TextField(blank=True, default='', help_text='additional info about securities', verbose_name='additional info'),
        ),
        migrations.AddField(
            model_name='securities',
            name='issuer_address',
            field=models.TextField(blank=True, default='', help_text='address of the issuer of securities', verbose_name='address of the issuer'),
        ),
        migrations.AddField(
            model_name='securities',
            name='issuer_from_info',
            field=models.CharField(blank=True, default='', help_text='info about ukrainian registration of the issuer of securities', max_length=55, verbose_name='info about ukrainian registration'),
        ),
        migrations.AddField(
            model_name='securities',
            name='issuer_name',
            field=models.TextField(blank=True, default='', help_text='name of the issuer of securities', max_length=75, verbose_name='name of the issuer'),
        ),
        migrations.AddField(
            model_name='securities',
            name='issuer_name_eng',
            field=models.TextField(blank=True, default='', help_text='name in English of the issuer of securities', max_length=75, verbose_name='name of the issuer in English'),
        ),
        migrations.AddField(
            model_name='securities',
            name='issuer_registration_number',
            field=models.CharField(blank=True, default='', help_text='number of registration of the issuer of securities', max_length=15, verbose_name='registration number of the issuer'),
        ),
        migrations.AddField(
            model_name='securities',
            name='trustee_address',
            field=models.TextField(blank=True, default='', help_text='address of the trustee of securities', verbose_name='address of the trustee'),
        ),
        migrations.AddField(
            model_name='securities',
            name='trustee_from_info',
            field=models.CharField(blank=True, default='', help_text='info about ukrainian registration of the trustee of securities', max_length=55, verbose_name='info about ukrainian registration'),
        ),
        migrations.AddField(
            model_name='securities',
            name='trustee_name',
            field=models.TextField(blank=True, default='', help_text='name of the trustee of securities', max_length=75, verbose_name='name of the trustee'),
        ),
        migrations.AddField(
            model_name='securities',
            name='trustee_name_eng',
            field=models.TextField(blank=True, default='', help_text='name in English of the trustee of securities', max_length=75, verbose_name='name of the trustee in English'),
        ),
        migrations.AddField(
            model_name='securities',
            name='trustee_registration_number',
            field=models.CharField(blank=True, default='', help_text='number of registration of the trustee of securities', max_length=15, verbose_name='registration number of the trustee'),
        ),
        migrations.AlterField(
            model_name='income',
            name='from_info',
            field=models.CharField(blank=True, default='', help_text='info about ukrainian citizenship or registration of the person or company that paid', max_length=55, verbose_name='info about ukrainian citizenship or registration'),
        ),
        migrations.AlterField(
            model_name='securities',
            name='nominal_value',
            field=models.FloatField(blank=True, help_text='nominal value of securities', null=True, verbose_name='nominal value'),
        ),
        migrations.AlterField(
            model_name='securities',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Share'), (2, 'Corporate right'), (3, 'Mortgage securities'), (4, 'Commodity securities'), (5, 'Derivatives'), (6, 'Debt securities'), (7, 'Privatization securities (vouchers, etc)'), (8, 'Investment certificates)'), (9, 'Check'), (10, 'Other')], help_text='type of securities', verbose_name='type'),
        ),
    ]
