# Generated by Django 3.1.8 on 2021-05-31 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_register', '0108_auto_20210526_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='money',
            name='non_pep_borrower',
        ),
        migrations.RemoveField(
            model_name='money',
            name='pep_borrower',
        ),
        migrations.AddField(
            model_name='money',
            name='additional_info',
            field=models.TextField(blank=True, default='', help_text='additional info about the money', verbose_name='additional info'),
        ),
        migrations.AddField(
            model_name='money',
            name='bank_address',
            field=models.TextField(blank=True, default='', help_text='address of the bank', verbose_name='address of the bank'),
        ),
        migrations.AddField(
            model_name='money',
            name='bank_from_info',
            field=models.CharField(blank=True, default='', help_text='info about ukrainian registration of the bank', max_length=55, verbose_name='info about ukrainian registration'),
        ),
        migrations.AddField(
            model_name='money',
            name='bank_name',
            field=models.TextField(blank=True, default='', help_text='name of the bank', max_length=75, verbose_name='name of the bank'),
        ),
        migrations.AddField(
            model_name='money',
            name='bank_name_eng',
            field=models.TextField(blank=True, default='', help_text='name of the bank in English ', max_length=75, verbose_name='name of the bank in English'),
        ),
        migrations.AddField(
            model_name='money',
            name='bank_registration_number',
            field=models.CharField(blank=True, default='', help_text='number of registration of the bank', max_length=25, verbose_name='registration number of the bank'),
        ),
        migrations.AlterField(
            model_name='luxuryitemright',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Ownership'), (2, 'Beneficial ownership'), (3, 'Joint ownership'), (4, 'Common property'), (5, 'Rent'), (6, 'Usage'), (10, 'Other right of usage'), (7, 'Owner is another person'), (20, 'Family member did not provide the information')], help_text='type of the right', verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='money',
            name='amount',
            field=models.FloatField(blank=True, help_text='amount of money', null=True, verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='money',
            name='currency',
            field=models.CharField(blank=True, default='', help_text='currency', max_length=33, verbose_name='currency'),
        ),
        migrations.AlterField(
            model_name='money',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Bank account'), (2, 'Hard cash'), (3, 'Contribution to the credit union or investment fund'), (4, 'Money lent to another person'), (5, 'Precious metals'), (10, 'Other')], help_text='type', verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='propertyright',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Ownership'), (2, 'Beneficial ownership'), (3, 'Joint ownership'), (4, 'Common property'), (5, 'Rent'), (6, 'Usage'), (10, 'Other right of usage'), (7, 'Owner is another person'), (20, 'Family member did not provide the information')], help_text='type of the right', verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='securitiesright',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Ownership'), (2, 'Beneficial ownership'), (3, 'Joint ownership'), (4, 'Common property'), (5, 'Rent'), (6, 'Usage'), (10, 'Other right of usage'), (7, 'Owner is another person'), (20, 'Family member did not provide the information')], help_text='type of the right', verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='vehicleright',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Ownership'), (2, 'Beneficial ownership'), (3, 'Joint ownership'), (4, 'Common property'), (5, 'Rent'), (6, 'Usage'), (10, 'Other right of usage'), (7, 'Owner is another person'), (20, 'Family member did not provide the information')], help_text='type of the right', verbose_name='type'),
        ),
    ]
