# Generated by Django 3.1.8 on 2021-06-01 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_register', '0108_auto_20210526_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysanction',
            name='reasoning_date',
            field=models.DateField(default=None, help_text='date of reasoning of imposing sanctions', null=True, verbose_name='reasoning date'),
        ),
        migrations.AddField(
            model_name='countrysanction',
            name='reasoning_date',
            field=models.DateField(default=None, help_text='date of reasoning of imposing sanctions', null=True, verbose_name='reasoning date'),
        ),
        migrations.AddField(
            model_name='personsanction',
            name='reasoning_date',
            field=models.DateField(default=None, help_text='date of reasoning of imposing sanctions', null=True, verbose_name='reasoning date'),
        ),
        migrations.AlterField(
            model_name='companysanction',
            name='reasoning',
            field=models.TextField(default='', help_text='reasoning of imposing sanctions', verbose_name='reasoning'),
        ),
        migrations.AlterField(
            model_name='countrysanction',
            name='reasoning',
            field=models.TextField(default='', help_text='reasoning of imposing sanctions', verbose_name='reasoning'),
        ),
        migrations.AlterField(
            model_name='personsanction',
            name='reasoning',
            field=models.TextField(default='', help_text='reasoning of imposing sanctions', verbose_name='reasoning'),
        ),
    ]
