# Generated by Django 3.1.8 on 2021-06-01 08:04
from datetime import date

from django.db import migrations
import re


months = {
    'січня': 1,
    'лютого': 2,
    'березня': 3,
    'квітня': 4,
    'травня': 5,
    'червня': 6,
    'липня': 7,
    'серпня': 8,
    'вересня': 9,
    'жовтня': 10,
    'листопада': 11,
    'грудня': 12,
}

date_regex = re.compile(r'від (\d{1,2} ' + f'({"|".join(months.keys())})' + r' \d{4})')


def extract_date(reasoning):
    dob = date_regex.findall(reasoning)
    dob = dob[0][0]
    day, month, year = dob.split(' ')
    month = months[month]
    return date(int(year), month, int(day))


def set_reasoning_date(apps, schema):
    CompanySanction = apps.get_model('business_register', 'CompanySanction')
    PersonSanction = apps.get_model('business_register', 'PersonSanction')
    CountrySanction = apps.get_model('business_register', 'CountrySanction')

    def process_for_model(model):
        for s in model.objects.all():
            s.reasoning_date = extract_date(s.reasoning)
            s.save(update_fields=['reasoning_date'])

    process_for_model(CompanySanction)
    process_for_model(PersonSanction)
    process_for_model(CountrySanction)


class Migration(migrations.Migration):

    dependencies = [
        ('business_register', '0109_auto_20210601_0835'),
    ]

    operations = [
        migrations.RunPython(
            code=set_reasoning_date,
            reverse_code=migrations.RunPython.noop,
        )
    ]
