# Generated by Django 3.1.8 on 2021-06-01 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_register', '0109_auto_20210531_1103'),
        ('business_register', '0110_auto_20210601_0835'),
    ]

    operations = [
    ]
