# Generated by Django 3.1.8 on 2021-06-01 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_register', '0103_auto_20210520_1447'),
        ('business_register', '0111_merge_20210601_0851'),
    ]

    operations = [
    ]
