# Generated by Django 3.1.8 on 2021-06-02 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_register', '0112_merge_20210601_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatedpersonslink',
            name='from_person_relationship_type_en',
            field=models.CharField(help_text='The type of relationship with a related person in English.', max_length=90, null=True, verbose_name='connection`s type in English'),
        ),
        migrations.AddField(
            model_name='relatedpersonslink',
            name='to_person_relationship_type_en',
            field=models.CharField(help_text='The type of relationship with a related person in English.', max_length=90, null=True, verbose_name='another person`s connection`s type in English'),
        ),
    ]
