# Generated by Django 3.1.8 on 2021-06-03 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_register', '0106_companylinkwithpep_relationship_type_en'),
        ('business_register', '0113_auto_20210602_0420'),
        ('business_register', '0113_auto_20210602_0817'),
    ]

    operations = [
    ]
