# Generated by Django 3.1.8 on 2021-06-04 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_register', '0113_auto_20210602_0420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='luxuryitem',
            name='trademark',
            field=models.CharField(blank=True, default='', help_text='trademark of the item', max_length=100, verbose_name='trademark'),
        ),
        migrations.AlterField(
            model_name='property',
            name='valuation',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='valuation of the property', max_digits=12, null=True, verbose_name='valuation'),
        ),
    ]
