# Generated by Django 3.1.8 on 2021-06-03 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_register', '0114_merge_20210603_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpep',
            name='fullname_en',
            field=models.CharField(default='', help_text='Full name "last name first name middle name" in English.', max_length=75, verbose_name='full name in English'),
        ),
        migrations.AddField(
            model_name='pep',
            name='fullname_en',
            field=models.CharField(default='', help_text='Full name "last name first name middle name" in English.', max_length=75, verbose_name='full name in English'),
        ),
    ]
