# Generated by Django 3.1.8 on 2021-06-07 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_register', '0114_auto_20210604_0720'),
        ('business_register', '0115_auto_20210603_0950'),
    ]

    operations = [
    ]
