# Generated by Django 3.1.8 on 2021-06-08 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_register', '0116_merge_20210607_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='amount',
            field=models.PositiveIntegerField(blank=True, help_text='amount of income', null=True, verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='income',
            name='paid_by_person',
            field=models.CharField(blank=True, default='', help_text='full name of the person that paid', max_length=100, verbose_name='paid by person'),
        ),
        migrations.AlterField(
            model_name='income',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Salary'), (2, 'Interest'), (3, 'Dividends'), (4, 'From sale of property'), (5, 'From sale of securities or corporate rights'), (6, 'Business'), (7, 'Gift in cash'), (8, 'Gift'), (9, 'Fees and other payments'), (10, 'Other'), (11, 'Income from renting property'), (12, 'Pension'), (13, 'Insurance payments'), (14, 'Sale of securities and corporate rights'), (15, 'Prize'), (16, 'Charity'), (17, 'Sale of property'), (18, 'Legacy'), (19, 'Salary from part-time job'), (20, 'Sale of luxuries'), (21, 'Self-employment'), (22, 'Royalty')], help_text='type of income', verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='securities',
            name='issuer_registration_number',
            field=models.CharField(blank=True, default='', help_text='number of registration of the issuer of securities', max_length=20, verbose_name='registration number of the issuer'),
        ),
        migrations.AlterField(
            model_name='securities',
            name='trustee_registration_number',
            field=models.CharField(blank=True, default='', help_text='number of registration of the trustee of securities', max_length=20, verbose_name='registration number of the trustee'),
        ),
    ]
