# Generated by Django 3.1.8 on 2021-06-08 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_register', '0116_merge_20210607_0552'),
    ]

    operations = [
        migrations.AddField(
            model_name='kvedsection',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='name_en'),
        ),
    ]
