# Generated by Django 3.1.8 on 2021-06-14 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_register', '0117_auto_20210608_0434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetail',
            name='managing_paper',
            field=models.CharField(help_text='Managing paper of the company', max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcompanydetail',
            name='managing_paper',
            field=models.CharField(help_text='Managing paper of the company', max_length=700, null=True),
        ),
    ]
