# Generated by Django 3.1.8 on 2021-06-14 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_register', '0118_auto_20210614_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='kvedsection',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='name_en'),
        ),
    ]
