# Generated by Django 3.1.8 on 2021-06-15 11:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_register', '0119_kvedsection_name_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpep',
            name='nacp_id1',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveBigIntegerField(unique=True, verbose_name='id from NACP'), blank=True,
                default=list, help_text='id from the National agency on corruption prevention', size=None),
        ),
        migrations.AddField(
            model_name='pep',
            name='nacp_id1',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveBigIntegerField(unique=True, verbose_name='id from NACP'), blank=True,
                default=list, help_text='id from the National agency on corruption prevention', size=None),
        ),
        migrations.RunSQL(
            sql=f'''
                    UPDATE business_register_pep
                    SET nacp_id1 = ARRAY[nacp_id]
                    WHERE nacp_id IS NOT NULL;
                ''',
            reverse_sql=f'''
                    UPDATE business_register_pep
                    SET nacp_id =
                      (SELECT nacp_id1[1]
                       FROM business_register_pep AS pep2
                       WHERE business_register_pep.id=pep2.id)
                    WHERE business_register_pep.nacp_id1 IS NOT NULL;
            '''
        ),
        migrations.RunSQL(
            sql=f'''
                    UPDATE business_register_historicalpep
                    SET nacp_id1 = ARRAY[nacp_id]
                    WHERE nacp_id IS NOT NULL;
                    ''',
            reverse_sql=f'''
                    UPDATE business_register_historicalpep
                    SET nacp_id =
                      (SELECT nacp_id1[1]
                       FROM business_register_pep AS pep2
                       WHERE business_register_historicalpep.id=pep2.id)
                    WHERE business_register_historicalpep.nacp_id1 IS NOT NULL;
                    '''
        ),
        migrations.RemoveField(
            model_name='historicalpep',
            name='nacp_id',
        ),
        migrations.RemoveField(
            model_name='pep',
            name='nacp_id',
        ),
        migrations.RenameField(
            model_name='historicalpep',
            old_name='nacp_id1',
            new_name='nacp_id',
        ),
        migrations.RenameField(
            model_name='pep',
            old_name='nacp_id1',
            new_name='nacp_id',
        )
    ]
