# Generated by Django 3.1.8 on 2021-06-21 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business_register', '0121_ngoparticipation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartTimeJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the object was created. In YYYY-MM-DDTHH:mm:ss.SSSSSSZ format.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the object was update. In YYYY-MM-DDTHH:mm:ss.SSSSSSZ format.', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('is_paid', models.BooleanField(blank=True, default=None, help_text='is the job paid', null=True, verbose_name='is_paid')),
                ('description', models.TextField(blank=True, default='', help_text='description of the PEP`s part-time job', verbose_name='description')),
                ('employer_from_info', models.CharField(blank=True, default='', help_text='info about ukrainian registration of the employer', max_length=55, verbose_name='info about ukrainian registration')),
                ('employer_name', models.TextField(blank=True, default='', help_text='name of the employer', max_length=75, verbose_name='name of the employer')),
                ('employer_name_eng', models.TextField(blank=True, default='', help_text='name of the employer in English ', max_length=75, verbose_name='name of the employer in English')),
                ('employer_address', models.TextField(blank=True, default='', help_text='address of the employer', verbose_name='address of the employer')),
                ('employer_registration_number', models.CharField(blank=True, default='', help_text='number of registration of the employer', max_length=25, verbose_name='registration number of the employer')),
                ('employer_full_name', models.CharField(blank=True, default='', help_text='full name of the person that gave PEP part-time job', max_length=75, verbose_name='employer full name')),
                ('declaration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='part_time_jobs', to='business_register.declaration', verbose_name='declaration')),
                ('employer', models.ForeignKey(blank=True, default=None, help_text='employer of the PEP for part-time job', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='peps_employees', to='business_register.company', verbose_name='employer')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
    ]
