# Generated by Django 3.1.8 on 2021-06-22 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location_register', '0024_auto_20210526_0845'),
        ('business_register', '0122_parttimejob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='liability',
            old_name='bank_creditor',
            new_name='bank',
        ),
        migrations.RemoveField(
            model_name='liability',
            name='non_pep_creditor',
        ),
        migrations.RemoveField(
            model_name='liability',
            name='pep_creditor',
        ),
        migrations.AddField(
            model_name='liability',
            name='additional_info',
            field=models.TextField(blank=True, default='', help_text='additional info about the liability', verbose_name='additional info'),
        ),
        migrations.AddField(
            model_name='liability',
            name='bank_address',
            field=models.TextField(blank=True, default='', help_text='address of the bank', verbose_name='address of the bank'),
        ),
        migrations.AddField(
            model_name='liability',
            name='bank_from_info',
            field=models.CharField(blank=True, default='', help_text='info about ukrainian registration of the bank', max_length=55, verbose_name='info about ukrainian registration'),
        ),
        migrations.AddField(
            model_name='liability',
            name='bank_name',
            field=models.TextField(blank=True, default='', help_text='name of the bank', max_length=75, verbose_name='name of the bank'),
        ),
        migrations.AddField(
            model_name='liability',
            name='bank_name_eng',
            field=models.TextField(blank=True, default='', help_text='name of the bank in English ', max_length=75, verbose_name='name of the bank in English'),
        ),
        migrations.AddField(
            model_name='liability',
            name='bank_registration_number',
            field=models.CharField(blank=True, default='', help_text='number of registration of the bank', max_length=25, verbose_name='registration number of the bank'),
        ),
        migrations.AddField(
            model_name='liability',
            name='creditor_from_info',
            field=models.CharField(blank=True, default='', help_text='info about ukrainian registration of the person to whom money is owed', max_length=55, verbose_name='info about ukrainian registration'),
        ),
        migrations.AddField(
            model_name='liability',
            name='creditor_full_name',
            field=models.CharField(blank=True, default='', help_text='fullname of the person to whom money is owed', max_length=75, verbose_name='creditor'),
        ),
        migrations.AddField(
            model_name='liability',
            name='creditor_full_name_eng',
            field=models.CharField(blank=True, default='', help_text='fullname of the person to whom money is owed in English', max_length=75, verbose_name='creditor fullname in English'),
        ),
        migrations.AddField(
            model_name='liability',
            name='date',
            field=models.DateField(blank=True, help_text='liability date', null=True, verbose_name='date'),
        ),
        migrations.AddField(
            model_name='liability',
            name='guarantee',
            field=models.CharField(blank=True, default='', help_text='loan guarantee', max_length=65, verbose_name='loan guarantee'),
        ),
        migrations.AddField(
            model_name='liability',
            name='guarantee_amount',
            field=models.FloatField(blank=True, help_text='amount of the loan guarantee', null=True, verbose_name='amount'),
        ),
        migrations.AddField(
            model_name='liability',
            name='guarantee_registration',
            field=models.ForeignKey(blank=True, default=None, help_text='city of registration of the loan guarantee', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loans_guarantees', to='location_register.ratucity', verbose_name='loan guarantee registration'),
        ),
        migrations.AddField(
            model_name='liability',
            name='interest_paid',
            field=models.FloatField(blank=True, help_text='amount of the interest of the loan that was paid during declaration`s period', null=True, verbose_name='interest paid'),
        ),
        migrations.AddField(
            model_name='liability',
            name='loan_paid',
            field=models.FloatField(blank=True, help_text='amount of the body of the loan that was paid during declaration`s period', null=True, verbose_name='loan paid'),
        ),
        migrations.AddField(
            model_name='liability',
            name='loan_rest',
            field=models.FloatField(blank=True, help_text='amount of the rest of the loan', null=True, verbose_name='loan rest'),
        ),
        migrations.AlterField(
            model_name='liability',
            name='amount',
            field=models.FloatField(help_text='amount of the liability', verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='liability',
            name='currency',
            field=models.CharField(blank=True, default='', help_text='currency', max_length=33, verbose_name='currency'),
        ),
        migrations.AlterField(
            model_name='liability',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Loan'), (2, 'Money borrowed by another person'), (3, 'Tax debt'), (4, 'Liabilities under pension insurance contract'), (5, 'Liabilities under insurance contract'), (6, 'Liabilities under leasing contract'), (7, 'loan payments'), (8, 'interest payments on the loan'), (10, 'Other')], help_text='type of the liability', verbose_name='type'),
        ),
    ]
