# Generated by Django 3.1.12 on 2021-06-28 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_register', '0123_auto_20210622_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='brand',
            field=models.CharField(blank=True, default='', help_text='brand', max_length=80, verbose_name='brand'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(blank=True, default='', help_text='model', max_length=140, verbose_name='model'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Car'), (2, 'Truck'), (4, 'Boat'), (5, 'Agricultural machinery'), (6, 'Air_means'), (10, 'Other')], help_text='type of the vehicle', verbose_name='type'),
        ),
    ]
