# Generated by Django 3.1.12 on 2021-06-22 14:23

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_register', '0123_auto_20210622_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='personsanction',
            name='passports',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(regex='^(\\w| )+$')]), blank=True, default=list, size=None, verbose_name='passports'),
        ),
    ]
