# Generated by Django 3.1.8 on 2021-06-23 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location_register', '0024_auto_20210526_0845'),
        ('business_register', '0123_auto_20210622_1059'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateRights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the object was created. In YYYY-MM-DDTHH:mm:ss.SSSSSSZ format.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the object was update. In YYYY-MM-DDTHH:mm:ss.SSSSSSZ format.', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('company_name', models.TextField(blank=True, default='', help_text='name of the company', max_length=75, verbose_name='name of the company')),
                ('company_name_eng', models.TextField(blank=True, default='', help_text='name in English of the company', max_length=75, verbose_name='name of the company in English')),
                ('company_type_name', models.CharField(blank=True, default='', help_text='name of type of the company', max_length=65, verbose_name='name of type of the company')),
                ('company_registration_number', models.CharField(blank=True, default='', help_text='number of registration of the company', max_length=20, verbose_name='registration number of the company')),
                ('value', models.FloatField(blank=True, help_text='value of rights', null=True, verbose_name='value')),
                ('share', models.FloatField(blank=True, help_text='company share', null=True, verbose_name='share')),
                ('is_transferred', models.BooleanField(blank=True, default=None, help_text='is corporate rights transferred to another person or company', null=True, verbose_name='is transferred')),
                ('company', models.ForeignKey(blank=True, default=None, help_text='company', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corporate_rights_from_declarations', to='business_register.company', verbose_name='company')),
                ('country', models.ForeignKey(blank=True, default=None, help_text='country where the company is registered', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='declared_pep_corporate_rights', to='location_register.country', verbose_name='country')),
                ('declaration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corporate_rights', to='business_register.declaration', verbose_name='declaration')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
    ]
