# Generated by Django 3.1.8 on 2021-06-24 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_register', '0124_corporaterights'),
        ('business_register', '0124_personsanction_passports'),
    ]

    operations = [
    ]
