# Generated by Django 3.1.8 on 2021-06-28 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location_register', '0024_auto_20210526_0845'),
        ('business_register', '0126_auto_20210624_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parttimejob',
            name='employer_full_name',
            field=models.TextField(blank=True, default='', help_text='full name of the person that gave PEP part-time job', verbose_name='employer full name'),
        ),
        migrations.AlterField(
            model_name='parttimejob',
            name='employer_name',
            field=models.TextField(blank=True, default='', help_text='name of the employer', verbose_name='name of the employer'),
        ),
        migrations.AlterField(
            model_name='parttimejob',
            name='employer_name_eng',
            field=models.TextField(blank=True, default='', help_text='name of the employer in English ', verbose_name='name of the employer in English'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the object was created. In YYYY-MM-DDTHH:mm:ss.SSSSSSZ format.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the object was update. In YYYY-MM-DDTHH:mm:ss.SSSSSSZ format.', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('is_money_spent', models.BooleanField(blank=True, default=None, help_text='whether the money spent during the transaction', null=True, verbose_name='is_money_spent')),
                ('amount', models.FloatField(blank=True, help_text='amount of the liability', null=True, verbose_name='amount')),
                ('transaction_object_type', models.TextField(blank=True, default='', help_text='type of the object of the transaction', verbose_name='transaction object`s type')),
                ('transaction_object', models.TextField(blank=True, default='', help_text='object of the transaction', verbose_name='transaction`s object')),
                ('transaction_result', models.TextField(blank=True, default='', help_text='result of the transaction', verbose_name='transaction result')),
                ('date', models.DateField(blank=True, help_text='date of the transaction', null=True, verbose_name='date')),
                ('country', models.ForeignKey(blank=True, default=None, help_text='country where the transaction is registered', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='declared_pep_transactions', to='location_register.country', verbose_name='country')),
                ('declaration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='business_register.declaration', verbose_name='declaration')),
                ('participant', models.ForeignKey(blank=True, default=None, help_text='politically exposed person that executes the transaction', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='business_register.pep', verbose_name='PEP that executes the transaction')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
    ]
