# Generated by Django 3.1.8 on 2021-06-28 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_register', '0126_auto_20210624_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='luxuryitemright',
            name='country_of_citizenship',
        ),
        migrations.RemoveField(
            model_name='propertyright',
            name='country_of_citizenship',
        ),
        migrations.RemoveField(
            model_name='securitiesright',
            name='country_of_citizenship',
        ),
        migrations.RemoveField(
            model_name='vehicleright',
            name='country_of_citizenship',
        ),
        migrations.AddField(
            model_name='luxuryitemright',
            name='owner_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Declarant'), (2, 'Family member'), (3, 'Ukraine citizen'), (4, 'Foreign citizen'), (5, 'Legal entity registered in Ukraine'), (6, 'Legal entity registered abroad')], help_text='type of the owner', null=True, verbose_name='owner type'),
        ),
        migrations.AddField(
            model_name='propertyright',
            name='owner_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Declarant'), (2, 'Family member'), (3, 'Ukraine citizen'), (4, 'Foreign citizen'), (5, 'Legal entity registered in Ukraine'), (6, 'Legal entity registered abroad')], help_text='type of the owner', null=True, verbose_name='owner type'),
        ),
        migrations.AddField(
            model_name='securitiesright',
            name='owner_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Declarant'), (2, 'Family member'), (3, 'Ukraine citizen'), (4, 'Foreign citizen'), (5, 'Legal entity registered in Ukraine'), (6, 'Legal entity registered abroad')], help_text='type of the owner', null=True, verbose_name='owner type'),
        ),
        migrations.AddField(
            model_name='vehicleright',
            name='owner_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Declarant'), (2, 'Family member'), (3, 'Ukraine citizen'), (4, 'Foreign citizen'), (5, 'Legal entity registered in Ukraine'), (6, 'Legal entity registered abroad')], help_text='type of the owner', null=True, verbose_name='owner type'),
        ),
        migrations.AlterField(
            model_name='luxuryitemright',
            name='full_name',
            field=models.CharField(blank=True, default='', help_text='full name of the person that owns the right', max_length=150, verbose_name='full name'),
        ),
        migrations.AlterField(
            model_name='propertyright',
            name='full_name',
            field=models.CharField(blank=True, default='', help_text='full name of the person that owns the right', max_length=150, verbose_name='full name'),
        ),
        migrations.AlterField(
            model_name='securitiesright',
            name='full_name',
            field=models.CharField(blank=True, default='', help_text='full name of the person that owns the right', max_length=150, verbose_name='full name'),
        ),
        migrations.AlterField(
            model_name='vehicleright',
            name='full_name',
            field=models.CharField(blank=True, default='', help_text='full name of the person that owns the right', max_length=150, verbose_name='full name'),
        ),
    ]
