# Generated by Django 3.1.12 on 2021-06-29 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_register', '0127_auto_20210628_0906'),
        ('business_register', '0127_auto_20210628_1447'),
        ('business_register', '0124_auto_20210628_0857'),
    ]

    operations = [
    ]
