# Generated by Django 3.1.12 on 2021-06-29 11:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_register', '0128_merge_20210629_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='personsanction',
            name='year_of_birth',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2021)], verbose_name='year of birth'),
        ),
        migrations.RunSQL("""
            UPDATE business_register_personsanction
            SET year_of_birth = date_part('year', date_of_birth);
        """, reverse_sql='')
    ]
