# Generated by Django 3.1.8 on 2021-06-30 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business_register', '0130_auto_20210629_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporaterights',
            name='share',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='company share', max_digits=12, null=True, verbose_name='share'),
        ),
        migrations.AlterField(
            model_name='corporaterights',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='value of rights', max_digits=12, null=True, verbose_name='value'),
        ),
        migrations.AlterField(
            model_name='income',
            name='declaration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incomes', to='business_register.declaration', verbose_name='declaration'),
        ),
        migrations.AlterField(
            model_name='income',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Salary'), (2, 'Interest'), (3, 'Dividends'), (5, 'From sale of securities or corporate rights'), (6, 'Business'), (7, 'Gift in cash'), (8, 'Gift'), (9, 'Fees and other payments'), (10, 'Other'), (11, 'Income from renting property'), (12, 'Pension'), (13, 'Insurance payments'), (14, 'Sale of securities and corporate rights'), (15, 'Prize'), (16, 'Charity'), (17, 'Sale of property'), (18, 'Legacy'), (19, 'Salary from part-time job'), (20, 'Sale of luxuries'), (21, 'Self-employment'), (22, 'Royalty')], help_text='type of income', verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='liability',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='amount of the liability', max_digits=12, verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='liability',
            name='guarantee_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='amount of the loan guarantee', max_digits=12, null=True, verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='liability',
            name='interest_paid',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='amount of the interest of the loan that was paid during declaration`s period', max_digits=12, null=True, verbose_name='interest paid'),
        ),
        migrations.AlterField(
            model_name='liability',
            name='loan_paid',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='amount of the body of the loan that was paid during declaration`s period', max_digits=12, null=True, verbose_name='loan paid'),
        ),
        migrations.AlterField(
            model_name='liability',
            name='loan_rest',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='amount of the rest of the loan', max_digits=12, null=True, verbose_name='loan rest'),
        ),
        migrations.AlterField(
            model_name='luxuryitemright',
            name='share',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='share of the right', max_digits=12, null=True, verbose_name='share of the right'),
        ),
        migrations.AlterField(
            model_name='money',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='amount of money', max_digits=12, null=True, verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='propertyright',
            name='share',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='share of the right', max_digits=12, null=True, verbose_name='share of the right'),
        ),
        migrations.AlterField(
            model_name='securities',
            name='nominal_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='nominal value of securities', max_digits=12, null=True, verbose_name='nominal value'),
        ),
        migrations.AlterField(
            model_name='securitiesright',
            name='share',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='share of the right', max_digits=12, null=True, verbose_name='share of the right'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='amount of the liability', max_digits=12, null=True, verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='vehicleright',
            name='share',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='share of the right', max_digits=12, null=True, verbose_name='share of the right'),
        ),
    ]
