# Generated by Django 3.1.12 on 2021-06-30 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business_register', '0130_auto_20210629_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='PepScoring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the object was created. In YYYY-MM-DDTHH:mm:ss.SSSSSSZ format.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the object was update. In YYYY-MM-DDTHH:mm:ss.SSSSSSZ format.', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('rule_id', models.CharField(choices=[('PEP01', 'PEP01'), ('PEP02', 'PEP02'), ('PEP03_home', 'PEP03_home'), ('PEP03_land', 'PEP03_land'), ('PEP03_car', 'PEP03_car'), ('PEP04_adr', 'PEP04_adr'), ('PEP04_reg', 'PEP04_reg'), ('PEP05', 'PEP05'), ('PEP07', 'PEP07'), ('PEP09', 'PEP09'), ('PEP10', 'PEP10'), ('PEP11', 'PEP11'), ('PEP13', 'PEP13'), ('PEP15', 'PEP15'), ('PEP16', 'PEP16'), ('PEP17', 'PEP17'), ('PEP18', 'PEP18'), ('PEP19', 'PEP19'), ('PEP20', 'PEP20'), ('PEP21', 'PEP21'), ('PEP22', 'PEP22'), ('PEP23', 'PEP23'), ('PEP24', 'PEP24'), ('PEP25', 'PEP25'), ('PEP26', 'PEP26'), ('PEP27', 'PEP27')], max_length=10)),
                ('calculation_date', models.DateField()),
                ('score', models.FloatField()),
                ('data', models.JSONField()),
                ('declaration', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='scoring', to='business_register.declaration')),
                ('pep', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scoring', to='business_register.pep')),
            ],
            options={
                'verbose_name': 'оцінка ризику обгрунтованості активів',
            },
        ),
    ]
