# Generated by Django 3.1.8 on 2021-07-01 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_register', '0131_pepscoring'),
        ('business_register', '0131_auto_20210630_1048'),
    ]

    operations = [
    ]
