# Generated by Django 3.1.8 on 2021-07-01 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business_register', '0132_merge_20210630_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficary',
            name='beneficiary',
            field=models.ForeignKey(blank=True, default=None, help_text='politically exposed person that is beneficiary of the company', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='beneficiary_info', to='business_register.pep', verbose_name='PEP that is beneficiary'),
        ),
        migrations.CreateModel(
            name='CorporateRightsRight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the object was created. In YYYY-MM-DDTHH:mm:ss.SSSSSSZ format.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the object was update. In YYYY-MM-DDTHH:mm:ss.SSSSSSZ format.', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Ownership'), (2, 'Beneficial ownership'), (3, 'Joint ownership'), (4, 'Common property'), (5, 'Rent'), (6, 'Usage'), (10, 'Other right of usage'), (7, 'Owner is another person'), (20, 'Family member did not provide the information')], help_text='type of the right', verbose_name='type')),
                ('owner_type', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Declarant'), (2, 'Family member'), (3, 'Ukraine citizen'), (4, 'Foreign citizen'), (5, 'Legal entity registered in Ukraine'), (6, 'Legal entity registered abroad')], help_text='type of the owner', null=True, verbose_name='owner type')),
                ('additional_info', models.TextField(blank=True, default='', help_text='additional info about the right', verbose_name='additional info')),
                ('acquisition_date', models.DateField(blank=True, help_text='date of acquisition of the right', null=True, verbose_name='acquisition date')),
                ('share', models.DecimalField(blank=True, decimal_places=2, help_text='share of the right', max_digits=12, null=True, verbose_name='share of the right')),
                ('full_name', models.CharField(blank=True, default='', help_text='full name of the person that owns the right', max_length=75, verbose_name='full name')),
                ('company_name', models.CharField(blank=True, help_text='name of the company that owns the right', max_length=200, verbose_name='company name')),
                ('company', models.ForeignKey(blank=True, default=None, help_text='company or organisation that owns the right', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='business_register_corporaterightsright_rights', to='business_register.company', verbose_name='company')),
                ('corporate_rights', models.ForeignKey(help_text='right to corporate rights', on_delete=django.db.models.deletion.PROTECT, related_name='rights', to='business_register.corporaterights', verbose_name='corporate rights right')),
                ('pep', models.ForeignKey(blank=True, default=None, help_text='politically exposed person that owns the right', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='business_register_corporaterightsright_rights', to='business_register.pep', verbose_name='PEP that owns the right')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
