# Generated by Django 3.1.8 on 2021-07-02 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_register', '0133_auto_20210701_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporaterightsright',
            name='type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Ownership'), (2, 'Beneficial ownership'), (3, 'Joint ownership'), (4, 'Common property'), (5, 'Rent'), (6, 'Usage'), (10, 'Other right of usage'), (7, 'Owner is another person'), (20, 'Family member did not provide the information')], help_text='type of the right', null=True, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='luxuryitemright',
            name='type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Ownership'), (2, 'Beneficial ownership'), (3, 'Joint ownership'), (4, 'Common property'), (5, 'Rent'), (6, 'Usage'), (10, 'Other right of usage'), (7, 'Owner is another person'), (20, 'Family member did not provide the information')], help_text='type of the right', null=True, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='propertyright',
            name='type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Ownership'), (2, 'Beneficial ownership'), (3, 'Joint ownership'), (4, 'Common property'), (5, 'Rent'), (6, 'Usage'), (10, 'Other right of usage'), (7, 'Owner is another person'), (20, 'Family member did not provide the information')], help_text='type of the right', null=True, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='securitiesright',
            name='type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Ownership'), (2, 'Beneficial ownership'), (3, 'Joint ownership'), (4, 'Common property'), (5, 'Rent'), (6, 'Usage'), (10, 'Other right of usage'), (7, 'Owner is another person'), (20, 'Family member did not provide the information')], help_text='type of the right', null=True, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='vehicleright',
            name='type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Ownership'), (2, 'Beneficial ownership'), (3, 'Joint ownership'), (4, 'Common property'), (5, 'Rent'), (6, 'Usage'), (10, 'Other right of usage'), (7, 'Owner is another person'), (20, 'Family member did not provide the information')], help_text='type of the right', null=True, verbose_name='type'),
        ),
    ]
