# Generated by Django 3.1.8 on 2021-07-02 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_register', '0024_auto_20210526_0845'),
        ('business_register', '0134_auto_20210702_0902'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Beneficary',
            new_name='Beneficiary',
        ),
        migrations.AlterField(
            model_name='liability',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='amount of the liability', max_digits=12, null=True, verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='amount of the transaction', max_digits=12, null=True, verbose_name='amount'),
        ),
    ]
