# Generated by Django 3.1.12 on 2021-07-03 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_register', '0135_auto_20210702_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securities',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='quantity of securities', max_digits=12, null=True, verbose_name='quantity'),
        ),
    ]
