# Generated by Django 3.1.12 on 2021-07-03 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_register', '0135_auto_20210702_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='LuxuryCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the object was created. In YYYY-MM-DDTHH:mm:ss.SSSSSSZ format.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the object was update. In YYYY-MM-DDTHH:mm:ss.SSSSSSZ format.', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('brand', models.CharField(blank=True, default='', help_text='brand', max_length=80, verbose_name='brand')),
                ('model', models.CharField(blank=True, default='', help_text='model', max_length=140, verbose_name='model')),
                ('from_year', models.PositiveSmallIntegerField(help_text='to year of manufacture', verbose_name='from year')),
                ('to_year', models.PositiveSmallIntegerField(help_text='from year of manufacture', verbose_name='to year')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={},
        ),
    ]
