# Generated by Django 3.1.8 on 2021-07-04 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_register', '0136_auto_20210703_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='company_email',
            field=models.TextField(blank=True, default='', help_text='email of the company', verbose_name='email of the company'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='company_fax',
            field=models.TextField(blank=True, default='', help_text='fax number of the company', verbose_name='fax number of the company'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='company_phone',
            field=models.TextField(blank=True, default='', help_text='phone number of the company', verbose_name='phone number of the company'),
        ),
    ]
