# Generated by Django 3.1.12 on 2021-07-03 14:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('business_register', '0136_auto_20210703_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporaterightsright',
            name='company_name',
            field=models.TextField(blank=True, help_text='name of the company that owns the right', verbose_name='company name'),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='nacp_declaration_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='NACP id of the declaration', unique=True, verbose_name='NACP id'),
        ),
        migrations.AlterField(
            model_name='luxuryitemright',
            name='company_name',
            field=models.TextField(blank=True, help_text='name of the company that owns the right', verbose_name='company name'),
        ),
        migrations.AlterField(
            model_name='propertyright',
            name='company_name',
            field=models.TextField(blank=True, help_text='name of the company that owns the right', verbose_name='company name'),
        ),
        migrations.AlterField(
            model_name='securitiesright',
            name='company_name',
            field=models.TextField(blank=True, help_text='name of the company that owns the right', verbose_name='company name'),
        ),
        migrations.AlterField(
            model_name='vehicleright',
            name='company_name',
            field=models.TextField(blank=True, help_text='name of the company that owns the right', verbose_name='company name'),
        ),
    ]
