# Generated by Django 3.1.12 on 2021-07-05 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_register', '0137_auto_20210704_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pepscoring',
            name='calculation_date',
            field=models.DateTimeField(),
        ),
        migrations.RenameField(
            model_name='pepscoring',
            old_name='calculation_date',
            new_name='calculation_datetime',
        ),
    ]
