# Generated by Django 3.1.8 on 2021-07-05 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_register', '0138_auto_20210705_1016'),
        ('business_register', '0138_auto_20210705_0924'),
    ]

    operations = [
    ]
