# Generated by Django 3.1.8 on 2021-07-05 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_register', '0139_merge_20210705_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporaterightsright',
            name='company_name',
            field=models.TextField(blank=True, default='', help_text='name of the company that owns the right', verbose_name='company name'),
        ),
        migrations.AlterField(
            model_name='luxuryitemright',
            name='company_name',
            field=models.TextField(blank=True, default='', help_text='name of the company that owns the right', verbose_name='company name'),
        ),
        migrations.AlterField(
            model_name='propertyright',
            name='company_name',
            field=models.TextField(blank=True, default='', help_text='name of the company that owns the right', verbose_name='company name'),
        ),
        migrations.AlterField(
            model_name='securitiesright',
            name='company_name',
            field=models.TextField(blank=True, default='', help_text='name of the company that owns the right', verbose_name='company name'),
        ),
        migrations.AlterField(
            model_name='vehicleright',
            name='company_name',
            field=models.TextField(blank=True, default='', help_text='name of the company that owns the right', verbose_name='company name'),
        ),
    ]
