# Generated by Django 3.1.12 on 2021-07-05 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_register', '0137_auto_20210703_1421'),
        ('business_register', '0140_auto_20210705_1146'),
    ]

    operations = [
    ]
