# Generated by Django 3.1.8 on 2021-07-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_register', '0142_auto_20210705_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Salary'), (2, 'Interest'), (3, 'Dividends'), (5, 'From sale of securities or corporate rights'), (6, 'Business'), (7, 'Gift in cash'), (8, 'Gift'), (9, 'Fees and other payments'), (10, 'Other'), (11, 'Income from renting property'), (12, 'Pension'), (13, 'Insurance payments'), (14, 'Sale of securities and corporate rights'), (15, 'Prize'), (16, 'Charity'), (17, 'Sale of property'), (18, 'Legacy'), (19, 'Salary from part-time job'), (20, 'Sale of luxuries'), (21, 'Self-employment'), (22, 'Royalty')], help_text='type of income', null=True, verbose_name='type'),
        ),
    ]
