# Generated by Django 3.1.12 on 2021-07-06 13:36

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_register', '0144_auto_20210705_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pepscoring',
            name='data',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
