# Generated by Django 3.1.12 on 2021-07-08 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_register', '0146_auto_20210706_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='company_registration_number',
            field=models.CharField(blank=True, default='', help_text='number of registration of the company', max_length=100, verbose_name='registration number of the company'),
        ),
        migrations.AlterField(
            model_name='corporaterights',
            name='company_registration_number',
            field=models.CharField(blank=True, default='', help_text='number of registration of the company', max_length=100, verbose_name='registration number of the company'),
        ),
        migrations.AlterField(
            model_name='liability',
            name='bank_registration_number',
            field=models.CharField(blank=True, default='', help_text='number of registration of the bank', max_length=100, verbose_name='registration number of the bank'),
        ),
        migrations.AlterField(
            model_name='money',
            name='bank_registration_number',
            field=models.CharField(blank=True, default='', help_text='number of registration of the bank', max_length=100, verbose_name='registration number of the bank'),
        ),
        migrations.AlterField(
            model_name='ngoparticipation',
            name='ngo_registration_number',
            field=models.CharField(blank=True, default='', help_text='number of registration of the NGO', max_length=100, verbose_name='NGO registration number'),
        ),
        migrations.AlterField(
            model_name='parttimejob',
            name='employer_registration_number',
            field=models.CharField(blank=True, default='', help_text='number of registration of the employer', max_length=100, verbose_name='registration number of the employer'),
        ),
        migrations.AlterField(
            model_name='securities',
            name='issuer_registration_number',
            field=models.CharField(blank=True, default='', help_text='number of registration of the issuer of securities', max_length=100, verbose_name='registration number of the issuer'),
        ),
        migrations.AlterField(
            model_name='securities',
            name='trustee_registration_number',
            field=models.CharField(blank=True, default='', help_text='number of registration of the trustee of securities', max_length=100, verbose_name='registration number of the trustee'),
        ),
    ]
