# Generated by Django 3.1.12 on 2021-07-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_register', '0147_auto_20210708_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='LuxuryCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the object was created. In YYYY-MM-DDTHH:mm:ss.SSSSSSZ format.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the object was update. In YYYY-MM-DDTHH:mm:ss.SSSSSSZ format.', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('brand', models.CharField(help_text='brand', max_length=80, verbose_name='brand')),
                ('model', models.CharField(help_text='model', max_length=140, verbose_name='model')),
                ('after_year', models.PositiveSmallIntegerField(help_text='year of manufacture of the car after which the car is considered luxury', verbose_name='after year')),
                ('document_year', models.PositiveSmallIntegerField(help_text='year of the document in which the car is indicated', verbose_name='document year')),
                ('volume', models.DecimalField(blank=True, decimal_places=1, help_text='engine cylinder volume', max_digits=2, null=True, verbose_name='volume')),
                ('fuel', models.SmallIntegerField(blank=True, choices=[(1, 'Petrol'), (2, 'Diesel'), (3, 'Electric'), (4, 'Hybrid (Petrol + Electric)')], help_text='fuel type', null=True, verbose_name='fuel')),
            ],
            options={
                'unique_together': {('brand', 'model', 'after_year')},
            },
        ),
    ]
