# Generated by Django 3.1.12 on 2021-07-10 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_register', '0147_auto_20210708_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='LuxuryCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the object was created. In YYYY-MM-DDTHH:mm:ss.SSSSSSZ format.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the object was update. In YYYY-MM-DDTHH:mm:ss.SSSSSSZ format.', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('brand', models.CharField(max_length=80)),
                ('model', models.CharField(max_length=140)),
                ('after_year', models.PositiveSmallIntegerField(help_text='year of manufacture of the car after which the car is considered luxury')),
                ('document_year', models.PositiveSmallIntegerField(help_text='year of the document in which the car is indicated')),
                ('volume', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('fuel', models.SmallIntegerField(blank=True, choices=[(1, 'Petrol'), (2, 'Diesel'), (3, 'Electric'), (4, 'Hybrid'), (5, 'Diesel + electric'), (6, 'Petrol + electric')], null=True)),
            ],
            options={
                'unique_together': {('brand', 'model', 'document_year')},
            },
        ),
    ]
