# Generated by Django 3.0.7 on 2020-07-28 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiusagetracking',
            name='referer',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='відправник'),
        ),
        migrations.AlterField(
            model_name='apiusagetracking',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='мітка часу'),
        ),
    ]
