# Generated by Django 2.0.9 on 2020-06-08 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('location_register', '0002_auto_20200602_1449'), ('location_register', '0003_auto_20200603_1458'), ('location_register', '0004_auto_20200605_0853'), ('location_register', '0005_auto_20200605_0908'), ('location_register', '0006_auto_20200605_0910'), ('location_register', '0007_drvbuilding_code'), ('location_register', '0008_auto_20200605_1200'), ('location_register', '0009_auto_20200605_1221'), ('location_register', '0010_auto_20200605_1305')]

    dependencies = [
        ('location_register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrvAto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.IntegerField(max_length=9, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DrvBuilding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('number', models.CharField(max_length=4)),
                ('ato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_register.DrvAto')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DrvCouncil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DrvDistrict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DrvRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('code', models.IntegerField(max_length=3, unique=True)),
                ('number', models.IntegerField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('short_name', models.CharField(max_length=5, unique=True)),
                ('capital', models.CharField(max_length=15, null=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DrvStreet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=100)),
                ('previous_name', models.CharField(max_length=100, null=True)),
                ('number_of_buildings', models.PositiveIntegerField(null=True)),
                ('ato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_register.DrvAto')),
                ('council', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_register.DrvCouncil')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_register.DrvDistrict')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_register.DrvRegion')),
                ('code', models.CharField(default=0, max_length=15, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ZipCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('code', models.CharField(max_length=6, unique=True)),
                ('ato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_register.DrvAto')),
                ('council', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_register.DrvCouncil')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_register.DrvDistrict')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_register.DrvRegion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='drvdistrict',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_register.DrvRegion'),
        ),
        migrations.AddField(
            model_name='drvcouncil',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_register.DrvRegion'),
        ),
        migrations.AddField(
            model_name='drvbuilding',
            name='council',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_register.DrvCouncil'),
        ),
        migrations.AddField(
            model_name='drvbuilding',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_register.DrvDistrict'),
        ),
        migrations.AddField(
            model_name='drvbuilding',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_register.DrvRegion'),
        ),
        migrations.AddField(
            model_name='drvbuilding',
            name='street',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_register.DrvStreet'),
        ),
        migrations.AddField(
            model_name='drvbuilding',
            name='zip_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_register.ZipCode'),
        ),
        migrations.AddField(
            model_name='drvato',
            name='council',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_register.DrvCouncil'),
        ),
        migrations.AddField(
            model_name='drvato',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_register.DrvDistrict'),
        ),
        migrations.AddField(
            model_name='drvato',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_register.DrvRegion'),
        ),
        migrations.AlterField(
            model_name='drvato',
            name='code',
            field=models.CharField(max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='drvbuilding',
            name='number',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='drvregion',
            name='capital',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='drvregion',
            name='code',
            field=models.CharField(max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='drvregion',
            name='number',
            field=models.CharField(max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='drvbuilding',
            name='number',
            field=models.CharField(max_length=10),
        ),
        migrations.AddField(
            model_name='drvbuilding',
            name='code',
            field=models.CharField(default=0, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
