# Generated by Django 2.0.9 on 2020-06-03 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_register', '0002_auto_20200602_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drvato',
            name='code',
            field=models.CharField(max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='drvbuilding',
            name='number',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='drvregion',
            name='capital',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='drvregion',
            name='code',
            field=models.CharField(max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='drvregion',
            name='number',
            field=models.CharField(max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='drvstreet',
            name='number_of_buildings',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='zipcode',
            name='code',
            field=models.IntegerField(),
        ),
    ]
