# Generated by Django 2.0.9 on 2020-06-05 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_register', '0003_auto_20200603_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='drvstreet',
            name='code',
            field=models.CharField(default=0, max_length=15, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='drvbuilding',
            name='number',
            field=models.CharField(max_length=10),
        ),
    ]
