# Generated by Django 3.0.7 on 2020-06-30 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location_register', '0003_auto_20200609_1155'),
    ]

    atomic = False

    operations = [
        migrations.RenameModel(
            'citydistrict',
            'CityDistrict1',
        ),
        migrations.RenameModel(
            'CityDistrict1',
            'CityDistrict',
        ),
    ]
