# Generated by Django 2.0.9 on 2020-06-05 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_register', '0004_auto_20200605_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drvstreet',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='drvstreet',
            name='number_of_buildings',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='drvstreet',
            name='previous_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
