# Generated by Django 3.0.7 on 2020-07-22 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location_register', '0005_auto_20200721_1622'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drvato',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='drvbuilding',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='drvcouncil',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='drvdistrict',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='drvregion',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='drvstreet',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='koatuucategory',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='koatuucity',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='koatuucitydistrict',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='koatuudistrict',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='koatuuregion',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='ratucity',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='ratucitydistrict',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='ratudistrict',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='raturegion',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='ratustreet',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='zipcode',
            options={'ordering': ['id']},
        ),
    ]
