# Generated by Django 2.0.9 on 2020-06-05 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_register', '0006_auto_20200605_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='drvbuilding',
            name='code',
            field=models.CharField(default=0, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
