# Generated by Django 3.0.7 on 2020-07-24 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location_register', '0006_auto_20200722_1314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drvato',
            options={'verbose_name': 'адміністративно-територіальна одиниця'},
        ),
        migrations.AlterModelOptions(
            name='drvbuilding',
            options={'verbose_name': 'будинок'},
        ),
        migrations.AlterModelOptions(
            name='drvcouncil',
            options={'verbose_name': 'рада'},
        ),
        migrations.AlterModelOptions(
            name='drvdistrict',
            options={'verbose_name': 'район'},
        ),
        migrations.AlterModelOptions(
            name='drvregion',
            options={'verbose_name': 'регіон'},
        ),
        migrations.AlterModelOptions(
            name='drvstreet',
            options={'verbose_name': 'вулиця'},
        ),
        migrations.AlterModelOptions(
            name='koatuucitydistrict',
            options={'verbose_name': 'район у місті'},
        ),
        migrations.AlterModelOptions(
            name='koatuudistrict',
            options={'verbose_name': 'район'},
        ),
        migrations.AlterModelOptions(
            name='koatuuregion',
            options={'verbose_name': 'регіон'},
        ),
        migrations.AlterModelOptions(
            name='ratucitydistrict',
            options={'verbose_name': 'район у місті'},
        ),
        migrations.AlterModelOptions(
            name='ratudistrict',
            options={'verbose_name': 'район'},
        ),
        migrations.AlterModelOptions(
            name='raturegion',
            options={'verbose_name': 'регіон'},
        ),
        migrations.AlterModelOptions(
            name='zipcode',
            options={'verbose_name': 'поштовий індекс'},
        ),
        migrations.AlterField(
            model_name='drvato',
            name='code',
            field=models.CharField(max_length=7, unique=True, verbose_name='код'),
        ),
        migrations.AlterField(
            model_name='drvato',
            name='council',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_register.DrvCouncil', verbose_name='рада'),
        ),
        migrations.AlterField(
            model_name='drvato',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_register.DrvDistrict', verbose_name='район'),
        ),
        migrations.AlterField(
            model_name='drvato',
            name='name',
            field=models.CharField(max_length=100, verbose_name='назва'),
        ),
        migrations.AlterField(
            model_name='drvato',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_register.DrvRegion', verbose_name='регіон'),
        ),
        migrations.AlterField(
            model_name='drvbuilding',
            name='ato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_register.DrvAto', verbose_name='адміністративно-територіальна одиниця'),
        ),
        migrations.AlterField(
            model_name='drvbuilding',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='код'),
        ),
        migrations.AlterField(
            model_name='drvbuilding',
            name='council',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_register.DrvCouncil', verbose_name='рада'),
        ),
        migrations.AlterField(
            model_name='drvbuilding',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_register.DrvDistrict', verbose_name='район'),
        ),
        migrations.AlterField(
            model_name='drvbuilding',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_register.DrvRegion', verbose_name='регіон'),
        ),
        migrations.AlterField(
            model_name='drvbuilding',
            name='street',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_register.DrvStreet', verbose_name='вулиця'),
        ),
        migrations.AlterField(
            model_name='drvbuilding',
            name='zip_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_register.ZipCode', verbose_name='поштовий індекс'),
        ),
        migrations.AlterField(
            model_name='drvcouncil',
            name='name',
            field=models.CharField(max_length=100, verbose_name='назва'),
        ),
        migrations.AlterField(
            model_name='drvcouncil',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_register.DrvRegion', verbose_name='регіон'),
        ),
        migrations.AlterField(
            model_name='drvdistrict',
            name='name',
            field=models.CharField(max_length=100, verbose_name='назва'),
        ),
        migrations.AlterField(
            model_name='drvdistrict',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_register.DrvRegion', verbose_name='регіон'),
        ),
        migrations.AlterField(
            model_name='drvregion',
            name='capital',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='центр'),
        ),
        migrations.AlterField(
            model_name='drvregion',
            name='code',
            field=models.CharField(max_length=3, unique=True, verbose_name='код'),
        ),
        migrations.AlterField(
            model_name='drvregion',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='назва'),
        ),
        migrations.AlterField(
            model_name='drvregion',
            name='number',
            field=models.CharField(max_length=3, unique=True, verbose_name='номер'),
        ),
        migrations.AlterField(
            model_name='drvregion',
            name='short_name',
            field=models.CharField(max_length=5, unique=True, verbose_name='коротка назва'),
        ),
        migrations.AlterField(
            model_name='drvstreet',
            name='code',
            field=models.CharField(max_length=15, unique=True, verbose_name='код'),
        ),
        migrations.AlterField(
            model_name='drvstreet',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_register.DrvDistrict', verbose_name='район'),
        ),
        migrations.AlterField(
            model_name='drvstreet',
            name='name',
            field=models.CharField(max_length=100, verbose_name='назва'),
        ),
        migrations.AlterField(
            model_name='drvstreet',
            name='number_of_buildings',
            field=models.PositiveIntegerField(null=True, verbose_name='кількість будинків'),
        ),
        migrations.AlterField(
            model_name='drvstreet',
            name='previous_name',
            field=models.CharField(max_length=100, null=True, verbose_name='попередня назва'),
        ),
        migrations.AlterField(
            model_name='drvstreet',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_register.DrvRegion', verbose_name='регіон'),
        ),
        migrations.AlterField(
            model_name='koatuucity',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location_register.KoatuuCategory', verbose_name='категорія населеного пункта'),
        ),
        migrations.AlterField(
            model_name='koatuucity',
            name='code',
            field=models.CharField(max_length=10, null=True, unique=True, verbose_name='код'),
        ),
        migrations.AlterField(
            model_name='koatuucity',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location_register.KoatuuDistrict', verbose_name='район'),
        ),
        migrations.AlterField(
            model_name='koatuucity',
            name='name',
            field=models.CharField(max_length=100, verbose_name='назва'),
        ),
        migrations.AlterField(
            model_name='koatuucity',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_register.KoatuuRegion', verbose_name='регіон'),
        ),
        migrations.AlterField(
            model_name='koatuucitydistrict',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location_register.KoatuuCategory', verbose_name='категорія населеного пункта'),
        ),
        migrations.AlterField(
            model_name='koatuucitydistrict',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_register.KoatuuCity', verbose_name='населений пункт'),
        ),
        migrations.AlterField(
            model_name='koatuucitydistrict',
            name='code',
            field=models.CharField(max_length=10, null=True, unique=True, verbose_name='код'),
        ),
        migrations.AlterField(
            model_name='koatuucitydistrict',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location_register.KoatuuDistrict', verbose_name='район'),
        ),
        migrations.AlterField(
            model_name='koatuucitydistrict',
            name='name',
            field=models.CharField(max_length=100, verbose_name='назва'),
        ),
        migrations.AlterField(
            model_name='koatuucitydistrict',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_register.KoatuuRegion', verbose_name='регіон'),
        ),
        migrations.AlterField(
            model_name='koatuudistrict',
            name='code',
            field=models.CharField(max_length=10, null=True, unique=True, verbose_name='код'),
        ),
        migrations.AlterField(
            model_name='koatuudistrict',
            name='name',
            field=models.CharField(max_length=100, verbose_name='назва'),
        ),
        migrations.AlterField(
            model_name='koatuudistrict',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_register.KoatuuRegion', verbose_name='регіон'),
        ),
        migrations.AlterField(
            model_name='koatuuregion',
            name='code',
            field=models.CharField(max_length=10, null=True, unique=True, verbose_name='код'),
        ),
        migrations.AlterField(
            model_name='koatuuregion',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='назва'),
        ),
        migrations.AlterField(
            model_name='ratucity',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location_register.KoatuuCategory', verbose_name='категорія населеного пункта'),
        ),
        migrations.AlterField(
            model_name='ratucity',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_register.RatuDistrict', verbose_name='район'),
        ),
        migrations.AlterField(
            model_name='ratucity',
            name='koatuu',
            field=models.CharField(max_length=10, null=True, unique=True, verbose_name='код КОАТУУ'),
        ),
        migrations.AlterField(
            model_name='ratucity',
            name='name',
            field=models.CharField(max_length=100, verbose_name='назва'),
        ),
        migrations.AlterField(
            model_name='ratucity',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_register.RatuRegion', verbose_name='регіон'),
        ),
        migrations.AlterField(
            model_name='ratucitydistrict',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location_register.KoatuuCategory', verbose_name='категорія населеного пункта'),
        ),
        migrations.AlterField(
            model_name='ratucitydistrict',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_register.RatuCity', verbose_name='населений пункт'),
        ),
        migrations.AlterField(
            model_name='ratucitydistrict',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_register.RatuDistrict', verbose_name='район'),
        ),
        migrations.AlterField(
            model_name='ratucitydistrict',
            name='koatuu',
            field=models.CharField(max_length=10, null=True, unique=True, verbose_name='код КОАТУУ'),
        ),
        migrations.AlterField(
            model_name='ratucitydistrict',
            name='name',
            field=models.CharField(max_length=100, verbose_name='назва'),
        ),
        migrations.AlterField(
            model_name='ratucitydistrict',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_register.RatuRegion', verbose_name='регіон'),
        ),
        migrations.AlterField(
            model_name='ratudistrict',
            name='koatuu',
            field=models.CharField(max_length=10, null=True, unique=True, verbose_name='код КОАТУУ'),
        ),
        migrations.AlterField(
            model_name='ratudistrict',
            name='name',
            field=models.CharField(max_length=100, verbose_name='назва'),
        ),
        migrations.AlterField(
            model_name='ratudistrict',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_register.RatuRegion', verbose_name='регіон'),
        ),
        migrations.AlterField(
            model_name='raturegion',
            name='koatuu',
            field=models.CharField(max_length=10, null=True, unique=True, verbose_name='код КОАТУУ'),
        ),
        migrations.AlterField(
            model_name='raturegion',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='назва'),
        ),
        migrations.AlterField(
            model_name='ratustreet',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_register.RatuCity', verbose_name='населений пункт'),
        ),
        migrations.AlterField(
            model_name='ratustreet',
            name='citydistrict',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_register.RatuCityDistrict', verbose_name='район у місті'),
        ),
        migrations.AlterField(
            model_name='ratustreet',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_register.RatuDistrict', verbose_name='район'),
        ),
        migrations.AlterField(
            model_name='ratustreet',
            name='name',
            field=models.CharField(max_length=100, verbose_name='назва'),
        ),
        migrations.AlterField(
            model_name='ratustreet',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_register.RatuRegion', verbose_name='регіон'),
        ),
        migrations.AlterField(
            model_name='zipcode',
            name='ato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_register.DrvAto', verbose_name='адміністративно-територіальна одиниця'),
        ),
        migrations.AlterField(
            model_name='zipcode',
            name='code',
            field=models.CharField(max_length=6, unique=True, verbose_name='індекс'),
        ),
        migrations.AlterField(
            model_name='zipcode',
            name='council',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_register.DrvCouncil', verbose_name='рада'),
        ),
        migrations.AlterField(
            model_name='zipcode',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_register.DrvDistrict', verbose_name='район'),
        ),
        migrations.AlterField(
            model_name='zipcode',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_register.DrvRegion', verbose_name='регіон'),
        ),
    ]
