# Generated by Django 3.0.7 on 2020-08-11 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location_register', '0007_auto_20200724_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='KoatuuFirstLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='назва')),
                ('code', models.CharField(max_length=10, null=True, unique=True, verbose_name='код')),
            ],
            options={
                'verbose_name': 'перший рівень підпорядкованості (область або місто зі спеціальним статусом)',
            },
        ),
        migrations.CreateModel(
            name='KoatuuFourthLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=100, verbose_name='назва')),
                ('code', models.CharField(max_length=10, null=True, unique=True, verbose_name='код')),
            ],
            options={
                'verbose_name': 'четвертий рівень підпорядкованості (села та селища)',
            },
        ),
        migrations.CreateModel(
            name='KoatuuSecondLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=100, verbose_name='назва')),
                ('code', models.CharField(max_length=10, null=True, unique=True, verbose_name='код')),
            ],
            options={
                'verbose_name': 'другий рівень підпорядкованості (місто, район області або район міста зі спеціальним статусом)',
            },
        ),
        migrations.CreateModel(
            name='KoatuuThirdLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=100, verbose_name='назва')),
                ('code', models.CharField(max_length=10, null=True, unique=True, verbose_name='код')),
            ],
            options={
                'verbose_name': 'третій рівень підпорядкованості (район міста обласного значення, міста районного значення, селища міського типу, села)',
            },
        ),
        migrations.RemoveField(
            model_name='koatuucitydistrict',
            name='category',
        ),
        migrations.RemoveField(
            model_name='koatuucitydistrict',
            name='city',
        ),
        migrations.RemoveField(
            model_name='koatuucitydistrict',
            name='district',
        ),
        migrations.RemoveField(
            model_name='koatuucitydistrict',
            name='region',
        ),
        migrations.RemoveField(
            model_name='koatuudistrict',
            name='region',
        ),
        migrations.AddField(
            model_name='koatuucategory',
            name='code',
            field=models.CharField(max_length=1, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='koatuucategory',
            name='name',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='KoatuuCity',
        ),
        migrations.DeleteModel(
            name='KoatuuCityDistrict',
        ),
        migrations.DeleteModel(
            name='KoatuuDistrict',
        ),
        migrations.DeleteModel(
            name='KoatuuRegion',
        ),
        migrations.AddField(
            model_name='koatuuthirdlevel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location_register.KoatuuCategory', verbose_name='категорія населеного пункта'),
        ),
        migrations.AddField(
            model_name='koatuuthirdlevel',
            name='first_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_register.KoatuuFirstLevel', verbose_name='перший рівень підпорядкованості'),
        ),
        migrations.AddField(
            model_name='koatuuthirdlevel',
            name='second_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location_register.KoatuuSecondLevel', verbose_name='другий рівень підпорядкованості'),
        ),
        migrations.AddField(
            model_name='koatuusecondlevel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location_register.KoatuuCategory', verbose_name='категорія населеного пункта'),
        ),
        migrations.AddField(
            model_name='koatuusecondlevel',
            name='first_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_register.KoatuuFirstLevel', verbose_name='перший рівень підпорядкованості'),
        ),
        migrations.AddField(
            model_name='koatuufourthlevel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location_register.KoatuuCategory', verbose_name='категорія населеного пункта'),
        ),
        migrations.AddField(
            model_name='koatuufourthlevel',
            name='first_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_register.KoatuuFirstLevel', verbose_name='перший рівень підпорядкованості'),
        ),
        migrations.AddField(
            model_name='koatuufourthlevel',
            name='second_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location_register.KoatuuSecondLevel', verbose_name='другий рівень підпорядкованості'),
        ),
        migrations.AddField(
            model_name='koatuufourthlevel',
            name='third_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_register.KoatuuThirdLevel', verbose_name='третій рівень підпорядкованості'),
        ),
    ]
