# Generated by Django 2.0.9 on 2020-06-05 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_register', '0007_drvbuilding_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zipcode',
            name='code',
            field=models.IntegerField(unique=True),
        ),
    ]
