# Generated by Django 3.0.7 on 2020-08-13 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location_register', '0008_auto_20200811_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='koatuufourthlevel',
            name='third_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fourth_level_places', to='location_register.KoatuuThirdLevel', verbose_name='третій рівень підпорядкованості'),
        ),
        migrations.AlterField(
            model_name='koatuusecondlevel',
            name='first_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_level_places', to='location_register.KoatuuFirstLevel', verbose_name='перший рівень підпорядкованості'),
        ),
        migrations.AlterField(
            model_name='koatuuthirdlevel',
            name='second_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='third_level_places', to='location_register.KoatuuSecondLevel', verbose_name='другий рівень підпорядкованості'),
        ),
    ]
