# Generated by Django 2.0.9 on 2020-06-05 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_register', '0008_auto_20200605_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zipcode',
            name='code',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
