# Generated by Django 2.0.9 on 2020-06-05 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_register', '0009_auto_20200605_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drvstreet',
            name='number_of_buildings',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
