# Generated by Django 3.0.7 on 2020-08-31 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_register', '0010_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drvbuilding',
            name='number',
            field=models.CharField(max_length=18),
        ),
    ]
