# Generated by Django 3.0.7 on 2020-08-31 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_register', '0011_auto_20200831_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drvbuilding',
            name='number',
            field=models.CharField(max_length=58),
        ),
    ]
