# Generated by Django 3.0.7 on 2020-09-01 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_register', '0013_auto_20200831_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drvstreet',
            name='previous_name',
            field=models.TextField(null=True, verbose_name='попередня назва'),
        ),
    ]
