# Generated by Django 3.0.7 on 2020-09-22 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location_register', '0014_auto_20200901_0748'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratucity',
            options={'verbose_name': 'населенний пункт'},
        ),
        migrations.AlterModelOptions(
            name='ratustreet',
            options={'verbose_name': 'вулиця'},
        ),
        migrations.AddField(
            model_name='ratucity',
            name='code',
            field=models.CharField(default='111', max_length=200, verbose_name='код'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ratucitydistrict',
            name='code',
            field=models.CharField(default='111', max_length=200, verbose_name=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ratudistrict',
            name='code',
            field=models.CharField(default='111', max_length=200, verbose_name='код'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ratustreet',
            name='code',
            field=models.CharField(default='111', max_length=200, verbose_name='код'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ratucity',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location_register.RatuDistrict', verbose_name='район'),
        ),
        migrations.AlterField(
            model_name='ratucitydistrict',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location_register.RatuDistrict', verbose_name='район'),
        ),
        migrations.AlterField(
            model_name='ratustreet',
            name='citydistrict',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location_register.RatuCityDistrict', verbose_name='район у місті'),
        ),
        migrations.AlterField(
            model_name='ratustreet',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location_register.RatuDistrict', verbose_name='район'),
        ),
    ]
