# Generated by Django 3.0.7 on 2021-02-15 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location_register', '0017_auto_20210211_0935'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'country'},
        ),
        migrations.AlterModelOptions(
            name='drvato',
            options={'verbose_name': 'administrative-territorial unit'},
        ),
        migrations.AlterModelOptions(
            name='drvbuilding',
            options={'verbose_name': 'building', 'verbose_name_plural': 'buildings'},
        ),
        migrations.AlterModelOptions(
            name='drvcouncil',
            options={'verbose_name': 'council'},
        ),
        migrations.AlterModelOptions(
            name='drvdistrict',
            options={'verbose_name': 'district'},
        ),
        migrations.AlterModelOptions(
            name='drvregion',
            options={'verbose_name': 'region'},
        ),
        migrations.AlterModelOptions(
            name='drvstreet',
            options={'verbose_name': 'street'},
        ),
        migrations.AlterModelOptions(
            name='koatuucategory',
            options={'verbose_name': 'category'},
        ),
        migrations.AlterModelOptions(
            name='koatuufirstlevel',
            options={'verbose_name': 'first level (region or city with special status)', 'verbose_name_plural': 'first level (regions or cities with special status)'},
        ),
        migrations.AlterModelOptions(
            name='koatuufourthlevel',
            options={'verbose_name': 'fourth level of subordination (village or settlement)', 'verbose_name_plural': 'fourth level of subordination (villages and settlements)'},
        ),
        migrations.AlterModelOptions(
            name='koatuusecondlevel',
            options={'verbose_name': 'second level (city, district of the region)', 'verbose_name_plural': 'second level (cities, districts of the region)'},
        ),
        migrations.AlterModelOptions(
            name='koatuuthirdlevel',
            options={'verbose_name': 'third level (district of the city of regional significance, city of district significance, urban-type settlement, village)', 'verbose_name_plural': 'third level (districts of the cities of regional significance, cities of district significance, urban-type settlements, villages)'},
        ),
        migrations.AlterModelOptions(
            name='ratucity',
            options={'verbose_name': 'city'},
        ),
        migrations.AlterModelOptions(
            name='ratucitydistrict',
            options={'verbose_name': 'district of the city'},
        ),
        migrations.AlterModelOptions(
            name='ratudistrict',
            options={'verbose_name': 'district'},
        ),
        migrations.AlterModelOptions(
            name='raturegion',
            options={'verbose_name': 'region'},
        ),
        migrations.AlterModelOptions(
            name='ratustreet',
            options={'verbose_name': 'street', 'verbose_name_plural': 'streets'},
        ),
        migrations.AlterModelOptions(
            name='zipcode',
            options={'verbose_name': 'ZIP code'},
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=60, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='drvato',
            name='code',
            field=models.CharField(max_length=7, unique=True, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='drvato',
            name='council',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_register.DrvCouncil', verbose_name='council'),
        ),
        migrations.AlterField(
            model_name='drvato',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_register.DrvDistrict', verbose_name='district'),
        ),
        migrations.AlterField(
            model_name='drvato',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='drvato',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_register.DrvRegion', verbose_name='region'),
        ),
        migrations.AlterField(
            model_name='drvbuilding',
            name='ato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_register.DrvAto', verbose_name='administrative-territorial unit'),
        ),
        migrations.AlterField(
            model_name='drvbuilding',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='drvbuilding',
            name='council',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_register.DrvCouncil', verbose_name='council'),
        ),
        migrations.AlterField(
            model_name='drvbuilding',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_register.DrvDistrict', verbose_name='district'),
        ),
        migrations.AlterField(
            model_name='drvbuilding',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_register.DrvRegion', verbose_name='region'),
        ),
        migrations.AlterField(
            model_name='drvbuilding',
            name='street',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_register.DrvStreet', verbose_name='street'),
        ),
        migrations.AlterField(
            model_name='drvbuilding',
            name='zip_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_register.ZipCode', verbose_name='ZIP code'),
        ),
        migrations.AlterField(
            model_name='drvcouncil',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='drvcouncil',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_register.DrvRegion', verbose_name='region'),
        ),
        migrations.AlterField(
            model_name='drvdistrict',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='drvdistrict',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_register.DrvRegion', verbose_name='region'),
        ),
        migrations.AlterField(
            model_name='drvregion',
            name='capital',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='capital'),
        ),
        migrations.AlterField(
            model_name='drvregion',
            name='code',
            field=models.CharField(max_length=3, unique=True, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='drvregion',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='drvregion',
            name='number',
            field=models.CharField(max_length=3, unique=True, verbose_name='number'),
        ),
        migrations.AlterField(
            model_name='drvregion',
            name='short_name',
            field=models.CharField(max_length=5, unique=True, verbose_name='short_name'),
        ),
        migrations.AlterField(
            model_name='drvstreet',
            name='code',
            field=models.CharField(max_length=15, unique=True, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='drvstreet',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_register.DrvDistrict', verbose_name='district'),
        ),
        migrations.AlterField(
            model_name='drvstreet',
            name='name',
            field=models.CharField(max_length=155, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='drvstreet',
            name='number_of_buildings',
            field=models.PositiveIntegerField(null=True, verbose_name='number of buildings'),
        ),
        migrations.AlterField(
            model_name='drvstreet',
            name='previous_name',
            field=models.TextField(null=True, verbose_name='previous name'),
        ),
        migrations.AlterField(
            model_name='drvstreet',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_register.DrvRegion', verbose_name='region'),
        ),
        migrations.AlterField(
            model_name='koatuufirstlevel',
            name='code',
            field=models.CharField(max_length=10, null=True, unique=True, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='koatuufirstlevel',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='koatuufourthlevel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location_register.KoatuuCategory', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='koatuufourthlevel',
            name='code',
            field=models.CharField(max_length=10, null=True, unique=True, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='koatuufourthlevel',
            name='first_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_register.KoatuuFirstLevel', verbose_name='first level'),
        ),
        migrations.AlterField(
            model_name='koatuufourthlevel',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='koatuufourthlevel',
            name='second_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location_register.KoatuuSecondLevel', verbose_name='second level'),
        ),
        migrations.AlterField(
            model_name='koatuufourthlevel',
            name='third_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fourth_level_places', to='location_register.KoatuuThirdLevel', verbose_name='third level'),
        ),
        migrations.AlterField(
            model_name='koatuusecondlevel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location_register.KoatuuCategory', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='koatuusecondlevel',
            name='code',
            field=models.CharField(max_length=10, null=True, unique=True, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='koatuusecondlevel',
            name='first_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_level_places', to='location_register.KoatuuFirstLevel', verbose_name='first level'),
        ),
        migrations.AlterField(
            model_name='koatuusecondlevel',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='koatuuthirdlevel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location_register.KoatuuCategory', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='koatuuthirdlevel',
            name='code',
            field=models.CharField(max_length=10, null=True, unique=True, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='koatuuthirdlevel',
            name='first_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_register.KoatuuFirstLevel', verbose_name='first level'),
        ),
        migrations.AlterField(
            model_name='koatuuthirdlevel',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='koatuuthirdlevel',
            name='second_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='third_level_places', to='location_register.KoatuuSecondLevel', verbose_name='second level'),
        ),
        migrations.AlterField(
            model_name='ratucity',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location_register.KoatuuCategory', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='ratucity',
            name='code',
            field=models.CharField(max_length=200, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='ratucity',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location_register.RatuDistrict', verbose_name='district'),
        ),
        migrations.AlterField(
            model_name='ratucity',
            name='koatuu',
            field=models.CharField(max_length=10, null=True, unique=True, verbose_name='code KOATUU'),
        ),
        migrations.AlterField(
            model_name='ratucity',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='ratucity',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_register.RatuRegion', verbose_name='region'),
        ),
        migrations.AlterField(
            model_name='ratucitydistrict',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location_register.KoatuuCategory', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='ratucitydistrict',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_register.RatuCity', verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='ratucitydistrict',
            name='code',
            field=models.CharField(max_length=200, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='ratucitydistrict',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location_register.RatuDistrict', verbose_name='district'),
        ),
        migrations.AlterField(
            model_name='ratucitydistrict',
            name='koatuu',
            field=models.CharField(max_length=10, null=True, unique=True, verbose_name='code KOATUU'),
        ),
        migrations.AlterField(
            model_name='ratucitydistrict',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='ratucitydistrict',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_register.RatuRegion', verbose_name='region'),
        ),
        migrations.AlterField(
            model_name='ratudistrict',
            name='code',
            field=models.CharField(max_length=200, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='ratudistrict',
            name='koatuu',
            field=models.CharField(max_length=10, null=True, unique=True, verbose_name='code KOATUU'),
        ),
        migrations.AlterField(
            model_name='ratudistrict',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='ratudistrict',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_register.RatuRegion', verbose_name='region'),
        ),
        migrations.AlterField(
            model_name='raturegion',
            name='koatuu',
            field=models.CharField(max_length=10, null=True, unique=True, verbose_name='code KOATUU'),
        ),
        migrations.AlterField(
            model_name='raturegion',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='ratustreet',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_register.RatuCity', verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='ratustreet',
            name='citydistrict',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location_register.RatuCityDistrict', verbose_name='district of the city'),
        ),
        migrations.AlterField(
            model_name='ratustreet',
            name='code',
            field=models.CharField(max_length=200, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='ratustreet',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location_register.RatuDistrict', verbose_name='district'),
        ),
        migrations.AlterField(
            model_name='ratustreet',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='ratustreet',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_register.RatuRegion', verbose_name='region'),
        ),
        migrations.AlterField(
            model_name='zipcode',
            name='ato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_register.DrvAto', verbose_name='administrative-territorial unit'),
        ),
        migrations.AlterField(
            model_name='zipcode',
            name='code',
            field=models.CharField(max_length=6, unique=True, verbose_name='ZIP code'),
        ),
        migrations.AlterField(
            model_name='zipcode',
            name='council',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_register.DrvCouncil', verbose_name='council'),
        ),
        migrations.AlterField(
            model_name='zipcode',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_register.DrvDistrict', verbose_name='district'),
        ),
        migrations.AlterField(
            model_name='zipcode',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_register.DrvRegion', verbose_name='region'),
        ),
    ]
