# Generated by Django 3.0.7 on 2021-03-15 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_register', '0019_auto_20210305_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='drvcouncil',
            name='code',
            field=models.CharField(max_length=130, null=True, unique=True, verbose_name='code'),
        ),
        migrations.AddField(
            model_name='drvdistrict',
            name='code',
            field=models.CharField(max_length=80, null=True, unique=True, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='drvdistrict',
            name='name',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
    ]
