# Generated by Django 3.0.7 on 2021-04-15 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location_register', '0021_auto_20210330_1650'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ('name',), 'verbose_name': 'country', 'verbose_name_plural': 'countries'},
        ),
    ]
