# Generated by Django 3.1.8 on 2021-05-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_register', '0022_auto_20210415_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='name_uk',
            field=models.CharField(default='', max_length=100, verbose_name='ukrainian name'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=60, unique=True, verbose_name='english name'),
        ),
    ]
