# Generated by Django 3.1.8 on 2021-05-18 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_register', '0022_auto_20210415_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='nacp_id',
            field=models.PositiveIntegerField(default=None, null=True, unique=True, verbose_name='NACP id of country'),
        ),
        migrations.AddField(
            model_name='country',
            name='name_uk',
            field=models.CharField(default=None, max_length=100, null=True, unique=True, verbose_name='ukrainian name'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=60, unique=True, verbose_name='english name'),
        ),
    ]
