# Generated by Django 3.1.8 on 2021-05-26 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_register', '0023_auto_20210518_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name_uk',
            field=models.CharField(default='', max_length=100, verbose_name='ukrainian name'),
        ),
    ]
