import logging
from django.core.management import BaseCommand
from location_register.models.address_models import Country

logger = logging.getLogger(__name__)
logger.setLevel(logging.INFO)


class Command(BaseCommand):
    help = 'Add or update name and name_uk in Country model'

    def handle(self, *args, **options):
        countries = countries_dict()
        for country_name_en in countries.keys():
            country, created = Country.objects.update_or_create(
                name=country_name_en, defaults={'name_uk': countries[country_name_en]}
            )
            if created:
                logger.info(f'New country {country_name_en}')


def countries_dict():
    return {
        'afghanistan': 'афганістан',
        'albania': 'албанія',
        'algeria': 'алжир',
        'andorra': 'андорра',
        'anguilla': 'анґілла',
        'antarctica': 'антарктика',
        'antigua and barbuda': 'антиґуа і барбуда',
        'argentina': 'аргентина',
        'armenia': 'вірменія',
        'aruba': 'аруба',
        'australia': 'австралія',
        'austria': 'австрія',
        'azerbaijan': 'азербайджан',
        'bahamas': 'багами',
        'bahrain': 'бахрейн',
        'bangladesh': 'бангладеш',
        'barbados': 'барбадос',
        'belarus': 'білорусь',
        'belgium': 'бельгія',
        'belize': 'беліз',
        'benin': 'бенін',
        'bermuda': 'бермуда',
        'bhutan': 'бутан',
        'bolivia': 'болівія',
        'bosnia herzegovina': 'боснія і герцеґовина',
        'botswana': 'ботсвана',
        'brazil': 'бразилія',
        'brunei': 'бруней даруссалам',
        'bulgaria': 'болгарія',
        'burkina faso': 'буркіна фасо',
        'burundi': 'бурунді',
        'cambodia': 'камбоджа',
        'cameroon': 'камерун',
        'canada': 'канада',
        'cape verde': 'капо верде',
        'cayman islands': 'кайманові острови',
        'central african republic': 'центральна африканська республіка',
        'chad': 'чад',
        'chile': 'чилі',
        'china': 'китай',
        'christmas island': 'різдвяні острови',
        'colombia': 'колумбія',
        'comoros': 'комори',
        'congo': 'конго',
        'cook islands': 'кука, острови',
        'costa rica': 'коста ріка',
        'cote d\'ivoire': 'кот д\'івуар',
        'croatia': 'хорватія',
        'cyprus': 'кіпр',
        'czech republic': 'чеська республіка',
        'denmark': 'данія',
        'djibouti': 'джибуті',
        'dominica': 'домініка',
        'east timor': 'східний тимор',
        'ecuador': 'еквадор',
        'egypt': 'єгипет',
        'el salvador': 'ель сальвадор',
        'england': 'англія',
        'guinea': 'ґвінея',
        'guinea-bissau': 'ґвінея-бісау',
        'eritrea': 'еритрея',
        'spain': 'іспанія',
        'estonia': 'естонія',
        'ethiopia': 'ефіопія',
        'falkland islands': 'фолклендські острови',
        'faroe islands': 'фарерські острови',
        'fiji': 'фіджі',
        'finland': 'фінляндія',
        'france': 'франція',
        'gabon': 'ґабон',
        'gambia': 'ґамбія',
        'georgia': 'грузія',
        'germany': 'німеччина',
        'ghana': 'ґана',
        'gibraltar': 'ґібралтар',
        'great britain': 'велика британія',
        'greece': 'греція',
        'greenland': 'ґренландія',
        'grenada': 'ґренада',
        'guadeloupe': 'ґваделупа',
        'guam': 'ґуам',
        'guatemala': 'ґватемала',
        'guyana': 'ґвіана',
        'guernsey': 'гернсі',
        'haiti': 'гаїті',
        'honduras': 'гондурас',
        'hong kong': 'гон-конґ',
        'hungary': 'угорщина',
        'iceland': 'ісландія',
        'india': 'індія',
        'indonesia': 'індонезія',
        'iran': 'іран',
        'iraq': 'ірак',
        'ireland': 'ірландія',
        'israel': 'ізраїль',
        'italy': 'італія',
        'jamaica': 'ямайка',
        'japan': 'японія',
        'jordan': 'іорданія',
        'kazakhstan': 'казахстан',
        'kenya': 'кенія',
        'kiribati': 'кірібаті',
        'korea (republic of)': 'корейська республіка',
        'south korea': 'корея (південна)',
        'kuwait': 'кувейт',
        'kyrgyzstan': 'киргизстан',
        'lao people\'s democratic republic': 'лаоська народно-демократична республіка',
        'latvia': 'латвія',
        'lebanon': 'ливан',
        'lesotho': 'лесото',
        'liberia': 'ліберія',
        'liechtenstein': 'ліхтенштейн',
        'lithuania': 'литва',
        'luxembourg': 'люксембург',
        'macau': 'макао',
        'macedonia (the former yugoslav republic of)': 'македонія',
        'madagascar': 'мадагаскар',
        'malawi': 'малаві',
        'malaysia': 'малайзія',
        'maldives': 'мальдиви',
        'mali': 'малі',
        'malta': 'мальта',
        'marshall islands': 'маршаллові острови',
        'martinique': 'мартиніка',
        'mauritania': 'мавританія',
        'mauritius': 'маврикій',
        'mexico': 'мексика',
        'micronesia, federated states of': 'мікронезія (федеральні штати)',
        'moldova (republic of)': 'молдова, республіка',
        'monaco': 'монако',
        'mongolia': 'монголія',
        'morocco': 'марокко',
        'mozambique': 'мозамбік',
        'namibia': 'намібія',
        'nauru': 'науру',
        'nepal': 'непал',
        'netherlands': 'нідерланди',
        'new caledonia': 'нова каледонія',
        'new zealand': 'нова зеландія',
        'nicaragua': 'нікарагуа',
        'nigeria': 'нігерія',
        'northern ireland': 'північна ірландія',
        'norway': 'норвегія',
        'oman': 'оман',
        'pakistan': 'пакістан',
        'palau': 'палау',
        'panama': 'панама',
        'papua new guinea': 'папуа нова ґвінея',
        'paraguay': 'парагвай',
        'peru': 'перу',
        'philippines': 'філіппіни',
        'poland': 'польща',
        'portugal': 'португалія',
        'puerto rico': 'пуерто ріко',
        'qatar': 'катар',
        'reunion': 'реуніон',
        'romania': 'румунія',
        'russia': 'росія',
        'rwanda': 'руанда',
        'saint lucia': 'санта люсія',
        'st vincent': 'сент вінсент',
        'samoa': 'самоа',
        'san marino': 'сан маріно',
        'saudi arabia': 'саудівська аравія',
        'scotland': 'шотландія',
        'senegal': 'сенегал',
        'seychelles': 'сейшели',
        'sierra leone': 'сьєрра леоне',
        'singapore': 'сингапур',
        'slovakia': 'словаччина',
        'slovenia': 'словенія',
        'solomon islands': 'соломонові острови',
        'somalia': 'сомалі',
        'south africa': 'південна африка',
        'sri lanka': 'шрі ланка',
        'suriname': 'сурінам',
        'swaziland': 'свазиленд',
        'sweden': 'швеція',
        'switzerland': 'швейцарія',
        'taiwan': 'тайвань',
        'tajikistan': 'таджикістан',
        'tanzania': 'танзанія',
        'thailand': 'таїланд',
        'togo': 'тоґо',
        'tonga': 'тонґа',
        'trinidad': 'тринідад',
        'trinidad and tobago': 'тринідад і тобаґо',
        'tunisia': 'туніс',
        'turkey': 'туреччина',
        'turkmenistan': 'туркменістан',
        'tuvalu': 'тувалу',
        'uganda': 'уґанда',
        'ukraine': 'україна',
        'united arab emirates': 'об\'єднані арабські емірати',
        'united kingdom': 'об\'єднане королівство',
        'united states of america': 'сполучені штати америки',
        'uruguay': 'уругвай',
        'uzbekistan': 'узбекістан',
        'vanuatu': 'вануату',
        'vatican city state': 'ватикан, місто-держава',
        'venezuela': 'венесуела',
        'vietnam': 'в\'єтнам',
        'wales': 'уельс',
        'western sahara': 'західна сахара',
        'yemen': 'ємен',
        'yugoslavia': 'югославія',
        'zambia': 'замбія',
        'zimbabwe': 'зимбабве'
    }
