# Generated by Django 2.0.9 on 2020-06-01 09:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('data_ocean', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('source_register_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500, unique=True)),
                ('source_name', models.CharField(max_length=300)),
                ('url_address', models.URLField(max_length=500)),
                ('api_address', models.URLField(max_length=500, null=True)),
                ('source_last_update', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
