# Generated by Django 2.0.9 on 2020-04-13 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_ocean', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Founders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('founder', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rfop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=300, null=True)),
                ('kved', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_ocean.Kved')),
            ],
        ),
        migrations.CreateModel(
            name='Ruo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, null=True)),
                ('short_name', models.CharField(max_length=500, null=True)),
                ('edrpou', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=500, null=True)),
                ('boss', models.CharField(max_length=250, null=True)),
                ('kved', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_ocean.Kved')),
            ],
        ),
        migrations.CreateModel(
            name='Staterfop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stateruo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='ruo',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_ocean.Stateruo'),
        ),
        migrations.AddField(
            model_name='rfop',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_ocean.Staterfop'),
        ),
        migrations.AddField(
            model_name='founders',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_ocean.Ruo'),
        ),
    ]
