# Generated by Django 2.0.9 on 2020-05-31 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_ocean', '0002_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='last_update',
            field=models.DateTimeField(null=True),
        ),
    ]
