# Generated by Django 3.0.7 on 2020-06-18 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_ocean', '0002_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='source_register_id',
            field=models.CharField(max_length=36, unique=True),
        ),
    ]
