# Generated by Django 2.0.9 on 2020-04-13 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_ocean', '0004_auto_20200413_1448'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staterfop',
        ),
    ]