# Generated by Django 3.0.5 on 2020-04-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_ocean', '0006_auto_20200416_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
