# Generated by Django 3.0.7 on 2020-08-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_ocean', '0006_auto_20200724_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistryUpdaterModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registry_name', models.CharField(db_index=True, max_length=20)),
                ('download_start', models.DateTimeField(auto_now_add=True)),
                ('download_finish', models.DateTimeField(blank=True, null=True)),
                ('download_status', models.BooleanField(blank=True, default=False)),
                ('download_message', models.CharField(blank=True, max_length=255, null=True)),
                ('download_file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('download_file_length', models.PositiveIntegerField(blank=True, default=0)),
                ('update_start', models.DateTimeField(auto_now_add=True)),
                ('update_finish', models.DateTimeField(blank=True, null=True)),
                ('update_status', models.BooleanField(blank=True, default=False)),
                ('update_message', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
