# Generated by Django 3.0.7 on 2020-08-26 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_ocean', '0007_registryupdatermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registryupdatermodel',
            name='update_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
