# Generated by Django 3.0.7 on 2020-09-08 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_ocean', '0008_auto_20200826_1915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='data_ocean_list',
            new_name='list',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='data_ocean_retrieve',
            new_name='retrieve',
        ),
        migrations.AddField(
            model_name='register',
            name='name_eng',
            field=models.CharField(max_length=500, null=True, unique=True, verbose_name='назва англійською'),
        ),
        migrations.AlterField(
            model_name='register',
            name='source_register_id',
            field=models.CharField(max_length=36, null=True, unique=True, verbose_name='ID реєстру у джерелі даних'),
        ),
    ]
