# Generated by Django 3.0.7 on 2020-09-10 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('data_ocean', '0009_auto_20200908_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='list',
        ),
        migrations.RemoveField(
            model_name='register',
            name='retrieve',
        ),
        migrations.CreateModel(
            name='EndPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=500, unique=True, verbose_name='назва')),
                ('endpoint', models.CharField(max_length=300, unique=True, verbose_name='ендпоінт')),
                ('type', models.CharField(choices=[('list', 'Список'), ('retrieve', "Об'єкт за ID")], max_length=30,
                                          verbose_name='тип ендпоінту')),
                ('register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endpoints',
                                               to='data_ocean.Register', verbose_name='Реєстр')),
            ],
            options={
                'verbose_name': 'ендпойнт реєстру',
            },
        ),
    ]
