# Generated by Django 3.0.7 on 2020-09-16 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_ocean', '0011_auto_20200915_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='registryupdatermodel',
            name='unzip_file_arch_length',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='registryupdatermodel',
            name='unzip_file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='registryupdatermodel',
            name='unzip_file_real_length',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='registryupdatermodel',
            name='unzip_message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='registryupdatermodel',
            name='unzip_status',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
