# Generated by Django 3.0.7 on 2020-11-16 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_ocean', '0013_auto_20201029_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='status',
            field=models.CharField(blank=True, choices=[('relevant', 'Relevant'), ('outdated', 'Outdated'), ('not supported', 'Not supported')], default='relevant', max_length=15, verbose_name='статус'),
        ),
    ]
