# Generated by Django 3.0.7 on 2021-01-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_ocean', '0015_auto_20201117_1922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='api_address',
            new_name='source_api_address',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='url_address',
            new_name='source_url_address',
        ),
        migrations.RemoveField(
            model_name='register',
            name='source_last_update',
        ),
        migrations.AddField(
            model_name='register',
            name='api_detail',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name="ендпоінт об'єкта"),
        ),
        migrations.AddField(
            model_name='register',
            name='api_list',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='ендпоінт списку'),
        ),
        migrations.AddField(
            model_name='register',
            name='total_records',
            field=models.PositiveIntegerField(blank=True, default=1, verbose_name='кількість записів'),
        ),
        migrations.AlterField(
            model_name='register',
            name='source_register_id',
            field=models.CharField(max_length=36, null=True, verbose_name='ID реєстру у джерелі даних'),
        ),
        migrations.DeleteModel(
            name='Dataset',
        ),
    ]
