# Generated by Django 3.0.7 on 2021-02-15 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_ocean', '0017_auto_20210211_0935'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authority',
            options={'verbose_name': 'registration authority'},
        ),
        migrations.AlterModelOptions(
            name='register',
            options={'ordering': ['id'], 'verbose_name': 'dataset', 'verbose_name_plural': 'datasets'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'status'},
        ),
        migrations.AlterModelOptions(
            name='taxpayertype',
            options={'verbose_name': 'taxpayer type'},
        ),
        migrations.AlterField(
            model_name='authority',
            name='code',
            field=models.CharField(max_length=10, null=True, unique=True, verbose_name='number'),
        ),
        migrations.AlterField(
            model_name='authority',
            name='name',
            field=models.CharField(max_length=500, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='register',
            name='api_detail',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='API detail'),
        ),
        migrations.AlterField(
            model_name='register',
            name='api_list',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='API list'),
        ),
        migrations.AlterField(
            model_name='register',
            name='name',
            field=models.CharField(max_length=500, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='register',
            name='name_eng',
            field=models.CharField(max_length=500, null=True, unique=True, verbose_name='name eng'),
        ),
        migrations.AlterField(
            model_name='register',
            name='source_api_address',
            field=models.URLField(max_length=500, null=True, verbose_name='source API'),
        ),
        migrations.AlterField(
            model_name='register',
            name='source_name',
            field=models.CharField(max_length=300, verbose_name='source'),
        ),
        migrations.AlterField(
            model_name='register',
            name='source_register_id',
            field=models.CharField(max_length=36, null=True, verbose_name='source ID'),
        ),
        migrations.AlterField(
            model_name='register',
            name='source_url_address',
            field=models.URLField(max_length=500, verbose_name='source url'),
        ),
        migrations.AlterField(
            model_name='register',
            name='status',
            field=models.CharField(blank=True, choices=[('relevant', 'Relevant'), ('outdated', 'Outdated'), ('not supported', 'Not supported')], default='relevant', max_length=15, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='register',
            name='total_records',
            field=models.PositiveIntegerField(blank=True, default=1, verbose_name='total records'),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='taxpayertype',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='name'),
        ),
    ]
