# Generated by Django 3.0.7 on 2021-03-03 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_ocean', '0019_auto_20210302_0934'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegistryUpdaterModel',
            new_name='Report',
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['id'], 'verbose_name': 'data update report', 'verbose_name_plural': 'data update reports'},
        ),
    ]
