# Generated by Django 3.0.7 on 2021-03-09 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_ocean', '0021_auto_20210305_1702'),
        ('data_ocean', '0021_auto_20210305_1511'),
    ]

    operations = [
    ]
