# Generated by Django 3.0.7 on 2021-03-19 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_ocean', '0023_auto_20210312_1130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='errors',
            new_name='invalid_data',
        ),
        migrations.AlterField(
            model_name='report',
            name='update_message',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
