# Generated by Django 3.1.7 on 2021-03-30 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_ocean', '0024_auto_20210319_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='status',
            field=models.CharField(blank=True, choices=[('relevant', 'Up-to-date'), ('outdated', 'Outdated'), ('not supported', 'Not supported')], default='relevant', max_length=15, verbose_name='status'),
        ),
    ]
