# Generated by Django 3.1.8 on 2021-05-17 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_ocean', '0026_auto_20210330_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='long_time_converter',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
