# Generated by Django 3.1.8 on 2021-05-28 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_ocean', '0027_report_long_time_converter'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='name_in_daily_report',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
