# Generated by Django 2.0.9 on 2020-04-28 06:53

from django.db import migrations, models
import django.db.models.deletion
from django.apps import apps
from data_ocean.models.kved_models import Section, Division, Group, Kved


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# data_ocean.migrations.0036_auto_20200422_1225

class Migration(migrations.Migration):

    dependencies = [
        ('data_ocean', '0035_auto_20200422_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='kved',
            name='code',
            field=models.CharField(max_length=5, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kved',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_ocean.Division'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kved',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_ocean.Group'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kved',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_ocean.Section'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kved',
            name='name',
            field=models.CharField(max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ruo',
            name='kved',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_ocean.Kved'),
        ),
        migrations.DeleteModel(
            name='Kzed',
        ),
        migrations.AlterField(
            model_name='division',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='kved',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]