# Generated by Django 2.0.9 on 2020-04-28 06:53

from django.db import migrations, models
import django.db.models.deletion
from django.apps import apps
from data_ocean.models.kved_models import Section, Division, Group, Kved


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# data_ocean.migrations.0036_auto_20200422_1225

class Migration(migrations.Migration):

    dependencies = [
        ('data_ocean', '0036_squashed_1'),
    ]

    def add_kved_not_found (apps, schema_editor):
        Section = apps.get_model('data_ocean', 'Section')
        section = Section()
        section.code = "EMP"
        section.name = "EMPTY"
        section.save()

        Division = apps.get_model('data_ocean', 'Division')
        division = Division()
        division.section = section
        division.code = "EMP"
        division.name = "EMPTY"
        division.save()

        Group = apps.get_model('data_ocean', 'Group')
        group = Group() 
        group.section = section
        group.division = division
        group.code = "EMP"
        group.name = "EMPTY"
        group.save()

        Kved = apps.get_model('data_ocean', 'Kved')
        kved = Kved() 
        kved.section = section
        kved.division = division
        kved.group = group
        kved.code = "EMP"
        kved.name = "EMPTY"
        kved.save()

    operations = [
        migrations.RunPython(add_kved_not_found),
    ]