# Generated by Django 2.0.9 on 2020-05-08 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_ocean', '0043_authority_status_taxpayertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('start_date', models.DateField(null=True)),
                ('start_number', models.CharField(max_length=20, null=True)),
                ('end_date', models.DateField(null=True)),
                ('end_number', models.CharField(max_length=20, null=True)),
                ('authority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_ocean.Authority')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Fop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('fullname', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=500, null=True)),
                ('registration_date', models.DateField(null=True)),
                ('registration_info', models.CharField(max_length=300, null=True)),
                ('estate_manager', models.CharField(max_length=100, null=True)),
                ('termination_date', models.DateField(null=True)),
                ('terminated_info', models.CharField(max_length=300, null=True)),
                ('termination_cancel_info', models.CharField(max_length=100, null=True)),
                ('contact_info', models.CharField(max_length=100, null=True)),
                ('vp_dates', models.CharField(max_length=100, null=True)),
                ('authority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_ocean.Authority')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_ocean.Status')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FopToKved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('primary_kved', models.BooleanField(default=False)),
                ('fop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_ocean.Fop')),
                ('kved', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_ocean.Kved')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='exchangedata',
            name='fop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_ocean.Fop'),
        ),
        migrations.AddField(
            model_name='exchangedata',
            name='taxpayer_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_ocean.TaxpayerType'),
        ),
    ]