# Generated by Django 2.0.9 on 2020-05-08 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_ocean', '0044_auto_20200508_1412'),
    ]

    operations = [migrations.RunSQL("CREATE UNIQUE INDEX main ON data_ocean_foptokved (fop_id) WHERE primary_kved = True;")
    ]