UKR_TO_EN_FIRST_LETTER = {
    'є': 'ye',
    'ї': 'yi',
    'й': 'y',
    'ю': 'yu',
    'я': 'ya',
    'Й': 'Y',
    'Ю': 'Yu',
    'Я': 'Ya',
    'Ї': 'Yi',
    'Є': 'Ye',
}

UKR_TO_EN = {
    'а': 'a',
    'б': 'b',
    'в': 'v',
    'г': 'h',
    'ґ': 'g',
    'д': 'd',
    'е': 'e',
    'є': 'ie',
    'ё': 'jo',
    'ж': 'zh',
    'з': 'z',
    'и': 'y',
    'і': 'i',
    'ї': 'i',
    'й': 'i',
    'к': 'k',
    'л': 'l',
    'м': 'm',
    'н': 'n',
    'о': 'o',
    'п': 'p',
    'р': 'r',
    'с': 's',
    'т': 't',
    'у': 'u',
    'ф': 'f',
    'х': 'kh',
    'ц': 'ts',
    'ч': 'ch',
    'ш': 'sh',
    'щ': 'shch',
    'ъ': '',
    'ы': 'y',
    'ь': '',
    'э': 'e',
    'ю': 'iu',
    'я': 'ia',
    'А': 'A',
    'Б': 'B',
    'В': 'V',
    'Г': 'H',
    'Ґ': 'G',
    'Д': 'D',
    'Е': 'E',
    'Ё': 'Jo',
    'Ж': 'Zh',
    'З': 'Z',
    'И': 'Y',
    'Й': 'I',
    'К': 'K',
    'Л': 'L',
    'М': 'M',
    'Н': 'N',
    'О': 'O',
    'П': 'P',
    'Р': 'R',
    'С': 'S',
    'Т': 'T',
    'У': 'U',
    'Ф': 'F',
    'Х': 'Kh',
    'Ц': 'Ts',
    'Ч': 'Ch',
    'Ш': 'Sh',
    'Щ': 'Shch',
    'Ъ': '',
    'Ы': 'Y',
    'Ь': '',
    'Э': 'E',
    'Ю': 'Iu',
    'Я': 'Ia',
    '’': '',
    "'": '',
    '`': '',
    'І': 'I',
    'Ї': 'I',
    'Є': 'Ie'
}

COUNTRIES = {
    "україна (окупована територія)": "ukraine (occupied territory)",
    "об'єднане королівство": "united kingdom",
    "україна (окупована територія донецької області)": "ukraine (occupied territory of donetsk region)",
    "україна (окупована територія луганської області)": "ukraine (occupied territory of luhansk region)",
    "україна": "ukraine",
    "Тимчасово окуповані території України (Крим)": "Temporarily occupied territory of Ukraine (Crimea)",
    "Тимчасово окуповані території України (ОРДО)": "Temporarily occupied territory of Ukraine (ORDO)",
    "Тимчасово окуповані території України (ОРЛО)": "Temporarily occupied territory of Ukraine (ORLO)",
    "росія": "russia",
    "російська федерація": "russian federation",
    "афганістан": "afghanistan",
    "аландські острови": "aland islands",
    "албанія": "albania",
    "алжир": "algeria",
    "американське самоа": "american samoa",
    "андорра": "andorra",
    "ангола": "angola",
    "ангілья": "anguilla",
    "антарктида": "antarctica",
    "антигуа і барбуда": "antigua and barbuda",
    "аргентина": "argentina",
    "вірменія": "armenia",
    "аруба": "aruba",
    "австралія": "australia",
    "австрія": "austria",
    "азербайджан": "azerbaijan",
    "багамські острови": "bahamas",
    "бахрейн": "bahrain",
    "бангладеш": "bangladesh",
    "барбадос": "barbados",
    "білорусь": "belarus",
    "бельгія": "belgium",
    "беліз": "belize",
    "бенін": "benin",
    "бермудські острови": "bermuda",
    "бутан": "bhutan",
    "болівія": "bolivia",
    "боснія і герцеговина": "bosnia herzegovina",
    "ботсвана": "botswana",
    "острів буве": "bouvet island",
    "бразилія": "brazil",
    "британська територія в індійському океані": "british territory in the indian ocean",
    "віргінські острови (британські)": "british virgin islands",
    "бруней": "brunei",
    "болгарія": "bulgaria",
    "буркіна-фасо": "burkina faso",
    "бурунді": "burundi",
    "камбоджа": "cambodia",
    "камерун": "cameroon",
    "канада": "canada",
    "кабо-верде": "cape verde",
    "кайманові острови": "cayman islands",
    "центральноафриканська республіка": "central african republic",
    "чад": "chad",
    "нормандські острови": "channel islands",
    "чилі": "chile",
    "китай": "china",
    "острів різдва": "christmas island",
    "кокосові острови (кілінг)": "cocos (keeling) islands",
    "колумбія": "colombia",
    "коморські острови": "comoros",
    "конго": "congo",
    "др конго": "congo, (republic of)",
    "острови кука": "cook islands",
    "коста-рика": "costa rica",
    "кот-д'івуар": "ivory coast",
    "хорватія": "croatia",
    "куба": "cuba",
    "кюрасао": "curaçao",
    "кіпр": "cyprus",
    "чехословакія": "czechoslovakia",
    "чехія": "czech republic",
    "данія": "denmark",
    "джибуті": "djibouti",
    "домініка": "dominica",
    "домініканська республіка": "dominican republic",
    "східний тимор": "east timor",
    "еквадор": "ecuador",
    "єгипет": "egypt",
    "сальвадор": "el salvador",
    "англія": "england",
    "англія та уельс": "england and wales",
    "англія & уельс": "england & wales",
    "екваторіальна гвінея": "equatorial guinea",
    "еритрея": "eritrea",
    "естонія": "estonia",
    "ефіопія": "ethiopia",
    "фолклендські (мальвінські) острови": "falkland islands",
    "фарерські острови": "faroe is",
    "фіджі": "fiji",
    "фінляндія": "finland",
    "франція": "france",
    "французькі південні території": "french southern territories",
    "габон": "gabon",
    "гамбія": "gambia",
    "грузія": "georgia",
    "німеччина": "germany",
    "гана": "ghana",
    "гібралтар": "gibraltar",
    "велика британія": "great britain",
    "греція": "greece",
    "ґренландія": "greenland",
    "гренада": "grenada",
    "гваделупа": "guadeloupe",
    "гуам": "guam",
    "гватемала": "guatemala",
    "гернсі": "guernsey",
    "французька гвіана": "guiana (french)",
    "гвінея": "guinea",
    "гвінея-бісау": "guinea-bissau",
    "гаяна": "guyana",
    "гаїті": "haiti",
    "острови герд і макдональд": "heard island and mcdonald islands",
    "голландія": "holland",
    "гондурас": "honduras",
    "гонконг": "hong kong",
    "угорщина": "hungary",
    "ісландія": "iceland",
    "індія": "india",
    "індонезія": "indonesia",
    "іран": "iran",
    "ірак": "iraq",
    "ірландія": "ireland",
    "ірландія (республіка)": "ireland rep",
    "ірландська республіка": "irish rep",
    "острів мен": "isle of man",
    "ізраїль": "israel",
    "італія": "italy",
    "ямайка": "jamaica",
    "японія": "japan",
    "джерсі": "jersey",
    "йорданія": "jordan",
    "казахстан": "kazakhstan",
    "кенія": "kenya",
    "кірибаті": "kiribati",
    "північна корея": "korea (republic of)",
    "косово": "kosovo",
    "кувейт": "kuwait",
    "киргизстан": "kyrgyzstan",
    "лаоська народно-демократична республіка": "lao people's democratic republic",
    "латвія": "latvia",
    "ліван": "lebanon",
    "лесото": "lesotho",
    "ліберія": "liberia",
    "лівія": "libya",
    "ліхтенштейн": "liechtenstein",
    "литва": "lithuania",
    "люксембург": "luxembourg",
    "макао": "macau",
    "македонія": "macedonia (the former yugoslav republic of)",
    "мадагаскар": "madagascar",
    "малаві": "malawi",
    "малайзія": "malaysia",
    "мальдіви": "maldives",
    "малі": "mali",
    "мальта": "malta",
    "маршаллові острови": "marshall islands",
    "мартиніка": "martinique",
    "мавританія": "mauritania",
    "маврикій": "mauritius",
    "майотта": "mayotte",
    "мексика": "mexico",
    "федеративні штати мікронезії": "micronesia, federated states of",
    "молдова": "moldova",
    "молдова (окупована територія придністров'я)": "moldova (occupied territory of transnistria)",
    "молдова (республіка)": "moldova (republic of)",
    "монако": "monaco",
    "монголія": "mongolia",
    "чорногорія": "montenegro",
    "монтсеррат": "montserrat",
    "марокко": "morocco",
    "мозамбік": "mozambique",
    "м'янма": "myanmar",
    "намібія": "namibia",
    "науру": "nauru",
    "непал": "nepal",
    "нідерланди": "netherlands",
    "нідерландські антильські острови": "netherlands antilles",
    "нова каледонія": "new caledonia",
    "нова зеландія": "new zealand",
    "нікарагуа": "nikaragua",
    "нігерія": "nigeria",
    "нігер": "niger (republic of)",
    "ніуе": "niue",
    "острів норфолк": "norfolk island",
    "північна ірландія": "northern ireland",
    "північні маріанські острови": "northern mariana islands",
    "норвегія": "norway",
    "оман": "oman",
    "пакистан": "pakistan",
    "палау": "palau",
    "палестина": "palestine",
    "панама": "panama",
    "папуа - нова гвінея": "papua new guinea",
    "парагвай": "paraguay",
    "перу": "peru",
    "філіппіни": "philippines",
    "польща": "poland",
    "французька полінезія": "polynesia (french)",
    "португалія": "portugal",
    "пуерто-рико": "puerto rico",
    "катар": "qatar",
    "республіка ірландія": "roi",
    "нігерія (республіка)": "republic of nigeria",
    "реюньйон": "reunion",
    "румунія": "romania",
    "руанда": "rwanda",
    "сен-бартельмі": "saint barthelemy",
    "острови святої єлени, вознесіння і тристан-да-кунья": "saint helena, ascension and tristan da cunha",
    "сент кітс і невіс": "saint kitts and nevis",
    "сен-мартін": "saint-martin",
    "сен-п'єр і мікелон": "saint pierre and miquelon",
    "самоа": "samoa",
    "сан-марино": "san marino",
    "сан-томе і принсіпі": "sao tome and principe",
    "саудівська аравія": "saudi arabia",
    "сенегал": "senegal",
    "сербія та чорногорія": "serbia and montenegro",
    "сербія": "serbia (republic of)",
    "сейшельські острови": "seychelles",
    "сьєрра-леоне": "sierra leone",
    "сінгапур": "singapore",
    "словакія": "slovakia",
    "словаччина": "slovak republic",
    "словенія": "slovenia",
    "соломонові острови": "solomon islands",
    "сомалі": "somalia",
    "південно-африканська республіка": "south africa",
    "південна джорджія та південні сандвічеві острови": "south georgia and the south sandwich islands",
    "південна корея": "south korea",
    "південна осетія (окупована росією чатина грузії)": "south ossetia (russian-occupied part of georgia)",
    "південний судан": "south sudan (republic of)",
    "південно-західна африка": "south-west africa",
    "іспанія": "spain",
    "шрі-ланка": "sri lanka",
    "сент-кіттс і невіс": "st kitts-nevis",
    "сент-люсія": "st lucia",
    "сент-вінсент і гренадини": "st vincent",
    "судан": "sudan",
    "суринам": "suriname",
    "свальбард і ян-маєн": "svalbard and yang-mayen",
    "свазіленд": "swaziland",
    "швеція": "sweden",
    "швейцарія": "switzerland",
    "сирія": "syria",
    "таджикистан": "tajikistan",
    "тайвань": "taiwan",
    "танзанія": "tanzania",
    "таїланд": "thailand",
    "піткерн": "the pitcairn islands",
    "того": "togo",
    "токелау": "tokelau",
    "тонга": "tonga",
    "тринідад і тобаго": "trinidad and tobago",
    "туніс": "tunisia",
    "туреччина": "turkey",
    "туркменістан": "turkmenistan",
    "острови теркс і кайкос": "turks & caicos islands",
    "тувалу": "tuvalu",
    "уганда": "uganda",
    "об'єднані арабські емірати": "united arab emirates",
    "об'єднане королівство великої британії та північної ірландії": "united kingdom of great britain and northern ireland",
    "сполучені штати": "united states",
    "зовнішні малі острови сша": "united states minor outlying islands",
    "сполучені штати америки": "united states of america",
    "невідомо": "unknown",
    "уругвай": "uruguay",
    "союз радянських соціалістичних республік": "ussr",
    "узбекистан": "uzbekistan",
    "вануату": "vanuatu",
    "ватикан": "vatican city state",
    "венесуела": "venezuela",
    "в'єтнам": "viet nam",
    "віргінські острови": "virgin islands",
    "британські віргінські острови": "virgin islands (british)",
    "віргінські острови, британські": "virgin islands, british",
    "американські віргінські острови": "virgin islands (u.s.)",
    "віргінські о-ви американські": "virgin is-us",
    "уельс": "wales",
    "волліс і футуна": "wallis and futuna",
    "західна сахара": "western sahara",
    "західна німеччина": "west germany",
    "ємен": "yemen arab republic",
    "югославія": "yugoslavia",
    "замбія": "zambia",
    "зімбабве": "zimbabwe"
}

COMPANY_TYPES = {
    "товариство з обмеженою відповідальністю": "limited trade development",
    "дочірнє підприємство": "subsidiary undertaking",
    "приватне підприємство": "private enterprise",
    "релігійна організація": "religious organization",
    "закрите акціонерне товариство": "private company limited by shares",
    "державне підприємство": "state owned enterprise",
    "відкрите акціонерне товариство": "open joint stock market entity",
    "обслуговуючий кооператив": "service cooperative",
    "колективне підприємство": "employee-owned enterprise",
    "комунальне підприємство": "municipal enterprise",
    "політична партія": "political party",
    "підприємство споживчої кооперації": "consumers cooperative society",
    "орган місцевого самоврядування": "local government institution",
    "благодійна організація": "charitable organization",
    "іноземне підприємство": "foreign enterprise",
    "спільне підприємство": "joint enterprise",
    "споживче товариство": "consumer company",
    "фермерське господарство": "farm enterprise",
    "орган виконавчої влади": "government authority",
    "орган самоорганізації населення": "community council",
    "повне товариство": "unlimited partnership",
    "сільськогосподарський обслуговуючий кооператив": "agricultural service cooperative",
    "профспілка": "trade union",
    "кооперативи": "cooperatives",
    "селянське (фермерське) господарство": "farm",
    "організація (установа, заклад) об'єднання громадян": "citizens organization (enterprise, institution)",
    "приватна організація (установа, заклад)": "private organization (enterprise, institution)",
    "інші об'єднання юридичних осіб": "other associations of legal entities",
    "товарна біржа": "commodity exchange",
    "товариство з додатковою відповідальністю": "superadded liability company",
    "орендне підприємство": "rental company",
    "кредитна спілка": "credit union",
    "спілка споживчих товариств": "community of consumer cooperatives",
    "командитне товариство": "limited partnership",
    "організація роботодавців": "employers' organisation",
    "концерн": "concern",
    "відокремлені підрозділи без статусу юридичної особи": "branches",
    "споживчий кооператив": "consumer cooperative",
    "організації (установи, заклади)": "organizations (enterprises, institutions)",
    "підприємства": "enterprises",
    "об'єднання підприємств (юридичних осіб)": "association of enterprises",
    "консорціум": "consortium",
    "спілка об'єднань громадян": "union of associations of citizens",
    "філія (інший відокремлений підрозділ)": "branch (separate unit)",
    "недержавний пенсійний фонд": "private pension fund",
    "державна акціонерна компанія (товариство)": "state-controlled joint-stock company",
    "господарські товариства": "business partnership",
    "представництво": "agency",
    "гаражний кооператив": "garage cooperative",
    "приватне акціонерне товариство": "private joint-stock company",
    "садівниче товариство": "gardeners partnership",
    "творча спілка (інша професійна організація)": "creative union (professional organization)",
    "житлово-будівельний кооператив": "house construction cooperative",
    "казенне підприємство": "state-run enterprise",
    "сімейне підприємство": "family enterprise",
    "підприємець-фізична особа": "private entrepreneur",
    "індивідуальне підприємство": "sole proprietorship",
    "інші організаційно-правові форми": "other company type",
    "компанія суспільних інтересів": "community interest company",
    "державна організація (установа, заклад)": "state organization (enterprise, institution)",
    "громадська організація": "non-governmental organization",
    "комунальна організація (установа, заклад)": "municipal organization (enterprise, institution)",
    "орган державної влади": "public authority",
    "сільськогосподарський виробничий кооператив": "agricultural production cooperative",
    "об'єднання співвласників багатоквартирного будинку": "association of co-owners of apartment house",
    "підприємство об'єднання громадян (релігійної організації,профспілки)": "citizens enterprise association (religious organization, trade unions)",
    "об'єднання громадян, профспілки, благодійні організації та інші подібні організації": "citizens` associations, trade unions, charitable and other organizations",
    "організація орендарів": "organization of tenants",
    "об'єднання профспілок": "trade union association",
    "публічне акціонерне товариство": "public joint-stock company",
    "організація покупців": "consumers association",
    "органи адвокатського самоврядування": "lawyers` self-government body",
    "холдингова компанія": "holding company",
    "адвокатське об'єднання": "lawyers` union",
    "адвокатське бюро": "law firm",
    "судова система": "judiciary",
    "асоціації органів місцевого самоврядування та їх добровільні обєднання": "associations of local government bodies and their voluntary associations",
    "кооперативний банк": "cooperative bank",
    "аудиторська палата україни": "the auditors chamber of ukraine",
    "приватна компанія з відповідальністю, обмеженою гарантіями її членів": "pri/ltd by guar/nsc (private, limited by guarantee, no share capital)",
    "шотландське партнерство": "scottish partnership",
    "обмежене партнерство": "limited partnership 2",
    "компанія з розділеними портфелями": "protected cell company",
    "інвестиційна компанія зі змінним капіталом": "investment company with variable capital",
    "зареєстроване товариство": "registered society",
    "інвестиційна компанія зі змінним капіталом (цінні папери)": "investment company with variable capital (securities)",
    "перероблена/закрита": "converted/closed",
    "давно існуюча публічна компанія": "old public company",
    "інвестиційна компанія зі змінним капіталом ('парасолькова компанія')": "investment company with variable capital(umbrella)",
    "партнерство з обмеженою відповідальністю": "limited liability partnership",
    "благодійне товариство": "charitable incorporated organisation",
    "приватна компанія з обмеженою відповідальністю згідно підрозділу 30 закону о компаніях": "priv ltd sect. 30 (private limited company, section 30 of the companies act)",
    "європейське публічне товариство з обмеженою відповідальністю": "european public limited-liability company (se)",
    "приватна компанія з обмеженою відповідальністю": "private limited company",
    "шотландське благодійне товариство": "scottish charitable incorporated organisation",
    "королівська статутна компанія": "royal charter company",
    "приватна компанія з необмеженою відповідальністю": "private unlimited company",
    "промислове товариство взаємного кредиту": "industrial and provident society",
    "публічна акціонерна компанія з обмеженою відповідальністю": "public limited company",
    "додаткова освіта та передуніверситетський коледж/коледжний корпус": "further education and sixth form college corps",
    "приватна/компанія з відповідальністю, обмеженою гарантіями її членів/без акціонерного капіталу, використання \"обмеженої\" пільги (або привілегії)": "pri/lbg/nsc (private, limited by guarantee, no share capital, use of 'limited' exemption)",
    "публічна компанія великобританії з обмеженою відповідальністю": "united kingdom societas",
    "консорціум великобританії": "united kingdom economic interest grouping",
    "акціонерне товариство": "joint stock company",
    "товариство": "private unlimited",
    "корпорація": "corporation",
    "асоціація": "association",
    "виробничий кооператив": "industrial cooperative",
}
